### PR TITLE
Import docker/docker/pkg/mount into runc

### PR DESCRIPTION
**Pull request by vdemeester**
This will help get rid of docker/docker dependency in runc 👼

With https://github.com/opencontainers/runc/pull/1622 it should remove the `docker/docker` "cycle" dependency

/cc @jhowardmsft @crosbymichael @hqhq @mrunalp @cpuguy83 @dqminh @cyphar 

(A follow could be to make `docker/docker use this package for those func instead of it's own impl.)

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Comment by crosbymichael** [comment]
needs a rebase

**Comment by vdemeester** [comment]
@crosbymichael rebased 👼

**Comment by crosbymichael** [comment]
LGTM

**Comment by dqminh** [comment]
LGTM

**Pull request merged**
