### PR TITLE
remove placeholder for non-linux platforms

### PR DESCRIPTION
**Pull request by dqminh**
runc currently only support Linux platform, and since we dont intend to expose
the support to other platform, removing all other platforms placeholder code.

`libcontainer/configs` still being used in https://github.com/moby/moby/blob/master/daemon/daemon_windows.go so
keeping it for now.

cc @opencontainers/runc-maintainers @justincormack @jhowardmsft

### CODE REVIEW

**Comment by mrunalp** [comment]
:+1:

**Comment by dqminh** [comment]
Rebased. I think this should be fine to look at.

I will send the rename of `*_linux.go` to `*.go` and a few general cleanup in another changeset.

**Comment by hqhq** [comment]
LGTM

**Comment by gireeshpunathil** [comment]
@dqminh:
> and since we dont intend to expose the support to other platform

Is this by policy / lack of contributor support / lack of infra / logistics or something else? can you please elaborate on this please? 

I would like to see the feasibility of porting runc on AIX. I am interested and willing to contribute, if someone can provide little guidance. thanks!

**Comment by gireeshpunathil** [comment]
thanks @dqminh , I will digest the linked docs and see how and where to start. Will look forward for your support an guidance!

**Comment by dqminh** [comment]
ping @cyphar @crosbymichael @mrunalp

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
