### PR TITLE
travis: use alternate commit range

### PR DESCRIPTION
**Pull request by vbatts**
cc @mrunalp 
I'm also going to try this as the upstream default https://github.com/vbatts/git-validation/pull/15

Signed-off-by: Vincent Batts <vbatts@redhat.com>

### CODE REVIEW

**Comment by vbatts** [comment]
oh boo. the new range includes merge commits ... hrm

**Comment by vbatts** [comment]
@mrunalp restart the travis check. I think i fixed it upstream

**Comment by mrunalp** [comment]
@vbatts restarted build.

**Comment by vbatts** [comment]
@mrunalp it's green now

**Comment by mrunalp** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Comment by cyphar** [comment]
It looks like this broke the Travis CI builds...

**Comment by vbatts** [comment]
@wking has opened issues to fix this

**Comment by wking** [comment]
On Tue, Mar 21, 2017 at 01:53:01PM -0700, Aleksa Sarai wrote:
> It looks like this broke the Travis CI builds...

I think #1383 and vbatts/git-validation#17 will fix that, although
it's hard to test if TRAVIS_COMMIT_RANGE is only occasionally unset.

**Pull request merged**
