### PR TITLE
Release 1.1.7

### PR DESCRIPTION
**Pull request by kolyshkin**
~~_Currently a draft pending #3845 merge._~~

~~_Currently a draft pending #3838 merge._~~

An excerpt from the changelog is below.

----

## [1.1.7] - 2023-04-26

> Ночевала тучка золотая на груди утеса-великана.

### Fixed

* When used with systemd v240+, systemd cgroup drivers no longer skip
  `DeviceAllow` rules if the device does not exist (a regression introduced
  in runc 1.1.3). This fix also reverts the workaround added in runc 1.1.5,
  removing an extra warning emitted by runc run/start. (#3845, #3708, #3671)
  
### Added

* The source code now has a new file, `runc.keyring`, which contains the keys
  used to sign runc releases. (#3838)

### CODE REVIEW

**Comment by kolyshkin** [comment]
No longer a draft. The release date is (tentatively) set for tomorrow.

**Comment by cyphar** [comment]
LGTM once we merge #3838.

**Review by AkihiroSuda — APPROVED** [review]

**Comment by kolyshkin** [comment]
> LGTM once we merge #3838.

You probably mean #3838 (which is now merged).

Now, I also have #3843 (which I think is more like a feature than a bugfix) and #3847 (which is too risky to be backported).

So, I think, we're good to release 1.1.7 today.

**Review by cyphar — APPROVED** [review]
LGTM.

**Comment by cyphar** [comment]
Released: https://github.com/opencontainers/runc/releases/tag/v1.1.7

**Pull request merged**
