### PR TITLE
Check that cwd is absolute

### PR DESCRIPTION
**Pull request by mrunalp**
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by mrunalp** [comment]
Handle https://github.com/opencontainers/specs/pull/312
cc: @duglin

**Comment by crosbymichael** [comment]
LGTM

**Comment by duglin** [comment]
@mrunalp looks good - thanks!

**Comment by hqhq** [comment]
LGTM

**Pull request merged**
