### PR TITLE
Release 1.0.0-rc91

### PR DESCRIPTION
**Pull request by mrunalp**
We have closed all the issues and pull requests for 1.0.0-rc91, so time for a release :)

@opencontainers/runc-maintainers PTAL.

### CODE REVIEW

**Comment by dims** [comment]
👍

**Comment by AkihiroSuda** [comment]
@kolyshkin Please vote on the dev ML as well?

**Comment by crosbymichael** [comment]
LGTM

**Comment by mrunalp** [comment]
@cyphar We have votes from everyone on the list and here so this is good to go.

**Comment by cyphar** [comment]
Alright, preparing the release now.

**Comment by cyphar** [comment]
Release finished (https://github.com/opencontainers/runc/releases/tag/v1.0.0-rc91) and I've already submitted it to openSUSE.

**Pull request merged**
