### PR TITLE
Add hooks for passing explicit veth pairs for forwarding to CRIU

### PR DESCRIPTION
**Pull request by boucher**
Signed-off-by: Hui Kang <hkang.sunysb@gmail.com>

### CODE REVIEW

**Comment by crosbymichael** [comment]
what does this do? just wondering?

**Comment by boucher** [comment]
Previously the network state was all stored in the libcontainer config, but with libnetwork that's no longer the case. This is just a hook that lets us pass down an explicit veth pair from the docker level.

**Comment by crosbymichael** [comment]
Are there better names than `InName` and `OutName`?  Maybe `Parent/Host` and `Container`?

**Comment by boucher** [comment]
Perhaps HostInterface/ContainerInterface?

**Comment by crosbymichael** [comment]
+1

**Comment by crosbymichael** [comment]
LGTM

**Comment by mrjana** [comment]
@boucher I am not sure if this going to be useful in general. I am not going to comment on how an api should look like in runc. But with libnetwork there may not always be a veth pair present to pass it down to runc. It will depend on the driver

**Comment by boucher** [comment]
I think there's an intent at the libcontainer level to expose as much of the criu option API as possible, most of which won't become options at the higher (docker) level. This seems inline with that -- anyone wanting to path the --veth-pairs flag without using the libcontainer network configuration could use this. 

Separately, this is, for the moment, the only way I currently know how to get networking working on container restore, so it's pretty useful until another/better solution has been worked out.

**Comment by laijs** [comment]
I think the commits should be merged as one commit.
One good commit is better than multiple draft-style commits.
The refactor commit is good if it performs on pervious code.
The refactor commit is bad if it performs on the previous code in the same PR.

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
