### PR TITLE
Fix some typos

### PR DESCRIPTION
**Pull request by JoeWrightss**
Fix some typos:
1. "Dont" to "Don't".
2. "identiy" to "identify".

### CODE REVIEW

**Comment by JoeWrightss** [comment]
Sorry，zhoulin is my real name

**Comment by Ace-Tang** [comment]
@JoeWrightss , I think you should sign-off like 
```
Signed-off-by: zhoulin xie <zhoulin.xie@daocloud.io>
```

**Comment by crosbymichael** [comment]
LGTM

**Comment by cyphar** [comment]
LGTM.

**Pull request merged**
