### PR TITLE
Call Prestart hooks before restoring processes

### PR DESCRIPTION
**Pull request by avagin**
Docker uses Prestart hooks to call a libnetwork hook to configure container's network namespace. When we are restoring a container, we need to call the libnetwork hook too.

I had an idea to add Prerestore hooks, but then I decided that it isn't actually required.

Cc: @boucher

### CODE REVIEW

**Comment by crosbymichael** [comment]
What version of criu should I be testing with?

**Comment by boucher** [comment]
I believe you need to build from master right now. I think 2.0 is shipping
relatively soon which should maybe become the new minimum required version?
Though, are protobufs are backwards compatible? In which case perhaps only
Docker needs to enforce the minimum version.

**Comment by boucher** [comment]
The Criu binary on this page should work, but the docker binary is not the
same code.

https://github.com/boucher/docker/releases/tag/v1.10_2-16-16-experimental

**Comment by avagin** [comment]
@crosbymichael CRIU 2.0 is required only if EmptyNs is set. Otherwise it can work with previous versions of criu.

**Comment by boucher** [comment]
@crosbymichael Any thoughts on this? CRIU 2.0 is now released, and has the empty_ns stuff in it.

**Comment by crosbymichael** [comment]
LGTM

**Comment by crosbymichael** [comment]
ping @LK4D4 @mrunalp

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
