### PR TITLE
Release v1.2.0-rc.3

### PR DESCRIPTION
**Pull request by lifubang**
## [1.2.0-rc.3] - 2024-09-02

> The supreme happiness of life is the conviction that we are loved.

### Added

 * Document build prerequisites for different platforms. (#4353)

### Fixed

 * Try to delete exec fifo file when failure in creation. (#4319)
 * Revert "libcontainer: seccomp: pass around *os.File for notifyfd". (#4337)
 * Fix link to gvariant documentation in systemd docs. (#4369)

### Changed

 * Remove pre-go1.17 build-tags. (#4329)
 * libct/userns: assorted (godoc) improvements (#4330)
 * libct/userns: split userns detection from internal userns code. (#4331)
 * rootfs: consolidate mountpoint creation logic. (#4359)
 * Add Go 1.23, drop 1.21. (#4360)
 * Revert "allow overriding VERSION value in Makefile" and add EXTRA_VERSION. (#4370)
 * Mv contrib/cmd tests/cmd (except memfd-bind). (#4377)
 * Makefile: Don't read COMMIT, BUILDTAGS, EXTRA_BUILDTAGS from env vars. (#4380)

### CODE REVIEW

**Review by AkihiroSuda — APPROVED** [review]

**Review by rata — APPROVED** [review]
LGTM, thanks!

I'll be afk next week.

**Comment by cyphar** [comment]
We still need to merge the private branch though. I guess I can push it before merging this. (This is why I suggested I do the release this time.)

**Comment by lifubang** [comment]
Yes, it’s indeed more convenient to do it by yourself, feel free to close this one.

**Comment by cyphar** [comment]
Since you've already done the changelog (thanks!), I'll just rebase this.

**Comment by cyphar** [comment]
Actually, it's easier to push it manually. I'll cherry-pick your release commits.

**Pull request closed without merging**
