### PR TITLE
Fix cgroups again

### PR DESCRIPTION
**Pull request by LK4D4**
I did previous fix based on data from `/proc/1/cgroup` in PID namespace of host, which was totally wrong. Now there is no panics in docker when I run tests in old docker with dind-based cgroups mounts.

### CODE REVIEW

**Comment by ibuildthecloud** [comment]
I can confirm this fixed my issue.

**Comment by LK4D4** [comment]
Also maybe makes sense to ask @calavera try as first discoverer of panic in docker.

**Comment by calavera** [comment]
The problem running the docker integration tests is also fixed with this patch. @LK4D4 do we have a way to add other tests to this or should we merge it?

**Comment by LK4D4** [comment]
@calavera at least I can add test with PIDHost and cgroup mounting.

**Comment by mrunalp** [comment]
@LK4D4 some tests will be good :+1:

**Comment by LK4D4** [comment]
@mrunalp @calavera I'm failing in imagining of test :) maybe someone could help me

**Comment by mrunalp** [comment]
@LK4D4 I guess we can test this manually for now. Could you describe what scenarios should be tested with dind?

**Comment by LK4D4** [comment]
@mrunalp spawn container without mounted cgroups and mount them with cgroups, then inside spawn container with mounted cgroups

**Comment by mrunalp** [comment]
Alright w/o --pid=host I see the cgroups in the inner container as
```
228 227 0:32 /system.slice/docker-832347d7c121c2ff0600d59210d66e9f7e510941f4602eaed1122bd667fa0688.scope/docker/44bca6fb0826f6148e50f2aba05c211244441124a65a696611fad1052d638873 /sys/fs/cgroup/cpuset ro,nosuid,nodev,noexec,relatime - cgroup cgroup rw,cpuset
```
which looks correct to me.

**Comment by mrunalp** [comment]
With --pid=host it is
```
223 222 0:32 /docker/d3082c37eec1ac1b2cb60cdf885d912a43742fdd6f2a8e369b2458a59bfa074d /sys/fs/cgroup/devices ro,nosuid,nodev,noexec,relatime - cgroup cgroup rw,devices
```

**Comment by LK4D4** [comment]
@mrunalp what is `d3082c37eec1ac1b2cb60cdf885d912a43742fdd6f2a8e369b2458a59bfa074d` in second case, outer or inner container ID?

**Comment by mrunalp** [comment]
@LK4D4 yeah, it was for the inner container. However, something was wrong with my setup and your patch wasn't in play. I rebuilt and now it looks the same in both the cases i.e. inner container is nested within the outer which looks good.

**Comment by mrunalp** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
