### PR TITLE
Update build dependencies in Dockerfile

### PR DESCRIPTION
**Pull request by dqminh**
This upgrade golang version in dockerfile to 1.10, image version from jessie to stretch, and criu version to v3.7. Because of the bump from jessie -> stretch, libseccomp is also bumped to 2.3.1-2.1

### CODE REVIEW

**Comment by cyphar** [comment]
DCOs are missing.

**Comment by dqminh** [comment]
@cyphar updated :man_facepalming: Also updated golang version to 1.10 instead of 1.9.

**Comment by cyphar** [comment]
LGTM.

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
