### PR TITLE
vendor: bump mountinfo to v0.4.0

### PR DESCRIPTION
**Pull request by kolyshkin**
Release notes:
- https://github.com/moby/sys/releases/tag/mountinfo%2Fv0.4.0

In particular, this fixes a regression introduced in commit b8bf572812 (PR #2647)
which checked the `mountinfo.Root` field in a `FilterFunc`, while `Root` was
not (yet) set when calling the filter.

Also add "runc run --no-pivot must not expose bare /proc" test by @AkihiroSuda
to prevent future regressions like this one.

Closes: #2655

### CODE REVIEW

**Comment by cyphar** [comment]
We can probably close #2655 in favour of this if you cherry-pick 3a452590d1960f99443b4b821ff54bb505d285ec. Or you can LGTM that and merge it, and we can re-add the `info.Root != "/"` check here.

**Comment by kolyshkin** [comment]
> if you cherry-pick 3a45259

done

**Comment by kolyshkin** [comment]
Took a liberty to make a minor change in the test case:

```diff
-       [[ ${lines[*]} == *"mount: permission denied"* ]]
+       [[ "$output" == *"mount: permission denied"* ]]
```

**Comment by kolyshkin** [comment]
@AkihiroSuda @mrunalp @cyphar PTAL

**Review by AkihiroSuda — APPROVED** [review]

**Review by cyphar — APPROVED** [review]
LGTM.

**Pull request closed without merging**
