### PR TITLE
Revert "update date in README"

### PR DESCRIPTION
**Pull request by hqhq**
Signed-off-by: Qiang Huang <h.huangqiang@huawei.com>

### CODE REVIEW

**Comment by hqhq** [comment]
revert https://github.com/opencontainers/runc/pull/441

**Comment by thaJeztah** [comment]
LGTM

for those interested why, see https://github.com/opencontainers/runc/pull/441#issuecomment-174379897

**Comment by cyphar** [comment]
I'd argue that claiming the software is `Copyright <year> Docker, Inc.` isn't technically correct, as contributors that don't work for "Docker Inc" haven't given "Docker Inc" their copyrights. It should probably read `Copyright <> The Authors` or similar.

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
