### PR TITLE
Add godoc links to README.md files

### PR DESCRIPTION
**Pull request by stevenh**
Add godoc links to README.md files for runc and libcontainer so its easy to access the golang documentation.

### CODE REVIEW

**Comment by stevenh** [comment]
Pretty sure the jenkins failure cant have been caused by these changes.

**Comment by cyphar** [comment]
No, the Jenkins failure is because of another bug we have at the moment (#1236).

**Comment by hqhq** [comment]
LGTM

**Comment by caniszczyk** [comment]
looks like janky is failing but Travis CI is not cc: @crosbymichael

**Comment by cyphar** [comment]
@caniszczyk You don't need to CC him -- anyone in the `#docker-maintainers` channel (which is public) on freenode can say `!rebuild runc#<pr>` to restart a Janky run.

**Comment by caniszczyk** [comment]
@cyphar thanks TIL, I had no idea!

**Comment by cyphar** [comment]
Oh, actually only voiced people in the channel can talk. So really only myself and Michael can kick off jobs (plus a few others from the Docker community).

**Comment by stevenh** [comment]
Still failing due to #1236 :(

**Comment by cyphar** [comment]
I can kick of the job until it succeeds. We can also just LGTM and merge it without Janky passing because it wasn't a code change.

**Comment by cyphar** [comment]
LGTM.

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
