### PR TITLE
libcontainer: rewrite cmsg to use sys/unix

### PR DESCRIPTION
**Pull request by cyphar**
The original implementation is in C, which increases cognitive load and
possibly might cause us problems in the future. Since sys/unix is better
maintained than the syscall standard library switching makes more sense.

Signed-off-by: Aleksa Sarai <asarai@suse.de>

### CODE REVIEW

**Comment by cyphar** [comment]
@crosbymichael This is at least the start of the "switch everything to `sys/unix`" transition. I'm really surprised how big `sys/unix` is (it's ~122k lines).

**Comment by cyphar** [comment]
@crosbymichael This is at least the start of the "switch everything to `sys/unix`" transition. I'm really surprised how big `sys/unix` is (it's ~122k lines).

**Comment by crosbymichael** [comment]
LGTM

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
