### PR TITLE
VERSION: release 1.0.0~rc93

### PR DESCRIPTION
**Pull request by cyphar**
<details>
<summary>Release Notes</summary>

v1.0.0~rc93

This is the last feature-rich RC release and we are in a feature-freeze until
1.0. 1.0.0~rc94 will be released in a few weeks with minimal bug fixes only,
and 1.0.0 will be released soon afterwards.

 * runc's cgroupv2 support is no longer considered experimental. It is now
   believed to be fully ready for production deployments. In addition, runc's
   cgroup code has been improved:
   - The systemd cgroup driver has been improved to be more resilient and
     handle more systemd properties correctly.
   - We now make use of openat2(2) when possible to improve the security of
     cgroup operations (in future runc will be wholesale ported to libpathrs to
     get this protection in all codepaths).

 * runc's mountinfo parsing code has been reworked significantly, making
   container startup times significantly faster and less wasteful in general.

 * runc now has special handling for seccomp profiles to avoid making new
   syscalls unusable for glibc. This is done by installing a custom prefix to
   all seccomp filters which returns -ENOSYS for syscalls that are newer than
   any syscall in the profile (meaning they have a larger syscall number).

   This should not cause any regressions (because previously users would simply
   get -EPERM rather than -ENOSYS, and the rule applied above is the most
   conservative rule possible) but please report any regressions you find as a
   result of this change -- in particular, programs which have special fallback
   code that is only run in the case of -EPERM.

 * runc now supports the following new runtime-spec features:
   - The umask of a container can now be specified.
   - The new Linux 5.9 capabilities (CAP_PERFMON, CAP_BPF, and
     CAP_CHECKPOINT_RESTORE) are now supported.
   - The "unified" cgroup configuration option, which allows users to explicitly
     specify the limits based on the cgroup file names rather than abstracting
     them through OCI configuration. This is currently limited in scope to
     cgroupv2.

 * Various rootless containers improvements:
   - runc will no longer cause conflicts if a user specifies a custom device
     which conflicts with a user-configured device -- the user device takes
     precedence.
   - runc no longer panics if /sys/fs/cgroup is missing in rootless mode.

 * runc --root is now always treated as local to the current working directory.

 * The --no-pivot-root hardening was improved to handle nested mounts properly
   (please note that we still strongly recommend that users do not use
   --no-pivot-root -- it is still an insecure option).

 * A large number of code cleanliness and other various cleanups, including
   fairly large changes to our tests and CI to make them all run more
   efficiently.

For packagers the following changes have been made which will have impact on
your packaging of runc:

 * The "selinux" and "apparmor" buildtags have been removed, and now all runc
   builds will have SELinux and AppArmor support enabled. Note that "seccomp"
   is still optional (though we very highly recommend you enable it).

 * make install DESTDIR= now functions correctly.

Thanks to the following people who made this release possible:

 * acetang <aceapril@126.com>
 * Adrian Reber <areber@redhat.com>
 * Akihiro Suda <akihiro.suda.cz@hco.ntt.co.jp>
 * Aleksa Sarai <cyphar@cyphar.com>
 * Amim Knabben <amim.knabben@gmail.com>
 * An Long <aisk1988@gmail.com>
 * Aos Dabbagh <aosdab@gmail.com>
 * Ashok Pon Kumar <ashokponkumar@gmail.com>
 * Cesar Talledo <ctalledo@nestybox.com>
 * Chaitanya Bandi <kbandi@cs.stonybrook.edu>
 * Cory Bennett <cbennett@netflix.com>
 * Daniel J Walsh <dwalsh@redhat.com>
 * Eduardo Vega <edvegavalerio@gmail.com>
 * Feng Sun <loyou85@gmail.com>
 * Giuseppe Scrivano <gscrivan@redhat.com>
 * Jeff Zvier <zvier20@gmail.com>
 * Kenta Tada <Kenta.Tada@sony.com>
 * Kir Kolyshkin <kolyshkin@gmail.com>
 * Manabu Sugimoto <Manabu.Sugimoto@sony.com>
 * Mauricio Vásquez <mauricio@kinvolk.io>
 * Michael Crosby <crosbymichael@gmail.com>
 * Mrunal Patel <mrunalp@gmail.com>
 * Paweł Szulik <pawel.szulik@intel.com>
 * Peter Hunt <pehunt@redhat.com>
 * Piotr Wagner <piotr.wagner@intel.com>
 * Sascha Grunert <sgrunert@suse.com>
 * SataQiu <1527062125@qq.com>
 * Sebastiaan van Stijn <github@gone.nl>
 * Shengjing Zhu <zhsj@debian.org>
 * Shukui Yang <keloyangsk@gmail.com>
 * wangtianxia <sometimesnaive@sjtu.edu.cn>
 * Wei Fu <fuweid89@gmail.com>
 * Xiaochen Shen <xiaochen.shen@intel.com>
 * Xiaodong Liu <liuxiaodong@loongson.cn>

</details>

Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>

### CODE REVIEW

**Comment by cyphar** [comment]
https://groups.google.com/a/opencontainers.org/g/dev/c/iTHGf2eywXo is the ML thread for the vote.

**Review by AkihiroSuda — APPROVED** [review]

**Comment by kolyshkin** [comment]
(I blatantly fixed the second-level item list markdown formatting in release notes).

> The "unified" cgroup configuration option, which allows users to explicitly
specify the limits based on the cgroup file names rather than abstracting
them through OCI configuration.

Maybe mention this functionality is for cgroup v2 only.

Might also add
* improved support for systemd cgroup driver (#2727, #2614, #2774)
* more secure cgroup drivers via use of openat2 (where available) (#2668) -- maybe not as it's an implementation detail
* rootless fixes and improvements (#2522, #2634)
* notable changes for distro packagers:
  * removal of selinux/apparmor build tags (#2709)
  * fix for make install DESTDIR= (#2578)

**Comment by kolyshkin** [comment]
> Maybe mention this functionality is for cgroup v2 only.

And provide a link to spec (https://github.com/opencontainers/runtime-spec/blob/master/config-linux.md#unified)

**Comment by kolyshkin** [comment]
> And provide a link to spec (https://github.com/opencontainers/runtime-spec/blob/master/config-linux.md#unified)

Upon (re-)reading which I suddenly realized its scope is NOT limited to cgroup v2 like I imagined (but nevertheless the runc implementation is).

**Review by kolyshkin — APPROVED** [review]
LGTM (and yay! :dog:)

**Comment by cyphar** [comment]
Yup, I'll add notes for those. I usually don't link directly to bugs because it's too many things to track (in future we're going to have a `CHANGELOG.md` so I don't have to write these by hand each time).

**Comment by cyphar** [comment]
Alright we have 4/7, but I'll wait until tomorrow before merging to give @crosbymichael @hqhq and @dqminh a chance to review as well.

**Comment by kolyshkin** [comment]
> in future we're going to have a CHANGELOG.md so I don't have to write these by hand each time).

I'd say add each bug to the milestone, so we don't have to write anything at all! For example (this is obviously incomplete now): [v1.0.0-rc93 issues](https://github.com/opencontainers/runc/issues?q=is%3Aissue+milestone%3A1.0.0-rc93+).

**Comment by cyphar** [comment]
I still think it's better to have a changelog file which has a user-understandable description so that PR authors do the writing and I can just copy the section. This is how I do umoci releases.

**Review by dqminh — APPROVED** [review]

**Pull request closed without merging**
