### PR TITLE
cgroupv2: allow to set EnableAllDevices=true

### PR DESCRIPTION
**Pull request by kolyshkin**
In this case we just do not install any eBPF rules
checking the devices.

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
Can we have integration test for devices?

**Comment by kolyshkin** [comment]
@giuseppe PTAL

> Can we have integration test for devices?

Do you mean for this particular case, or setting permission for devices in general?

In case of latter, can you describe what you want to test?

**Comment by AkihiroSuda** [comment]
The latter in the long term, but I think we can begin with the former one

**Comment by giuseppe** [comment]
@mrunalp PTAL

**Comment by mrunalp** [comment]
LGTM

**Comment by AkihiroSuda** [comment]
LGTM, integration test can be added later.

**Pull request merged**
