### PR TITLE
deps: update to github.com/cyphar/filepath-securejoin@v0.3.5

### PR DESCRIPTION
**Pull request by cyphar**
This fixes a regression in use of securejoin.MkdirAll, where multiple
runc processes racing to create the same mountpoint in a shared rootfs
would result in spurious EEXIST errors. In particular, this regression
caused issues with BuildKit.

Fixes: https://github.com/opencontainers/runc/commit/dd827f7b715ac1d48a336d101fce00dca6e20f9b ("utils: switch to securejoin.MkdirAllHandle")
Fixes opencontainers/runc#4543
Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>

### CODE REVIEW

**Review by austinvazquez — APPROVED** [review]

**Review by tonistiigi — APPROVED** [review]

**Review by kolyshkin — APPROVED** [review]
LGTM (also reviewed https://github.com/cyphar/filepath-securejoin/pull/35, which also LGTM).

**Review by lifubang — APPROVED** [review]

**Comment by lifubang** [comment]
I think we can make v1.2.3 release now!

Another thing, maybe we also need to backport to `release-1.1`, because it's also a regression in that branch, and we have not announced EOL of v1.1 yet.
Maybe we need to add a `RELEASE.md` to announce of our release policy?

**Comment by cyphar** [comment]
@lifubang 1.1.x doesn't use `securejoin.MkdirAll`, it still uses the hotfix implementation which doesn't have this regression.

Regarding `RELEASE.md`, I sent an email to all the maintainers a few months ago to try to get some agreement on the policy we want before we write it down. I can open a PR with my proposal if you like.

**Comment by lifubang** [comment]
> I can open a PR with my proposal if you like.

Yes, thanks.

**Comment by cyphar** [comment]
Hmmm, that's odd. I would've expected the race window to be much smaller...

**Pull request merged**
