### PR TITLE
Fix cgroup parent searching

### PR DESCRIPTION
**Pull request by LK4D4**
I had pretty convenient input data to miss this bug.

ping @mrunalp @crosbymichael @ibuildthecloud

### CODE REVIEW

**Comment by mrunalp** [comment]
LGTM

**Comment by crosbymichael** [comment]
is there a test for this?

**Comment by LK4D4** [comment]
@crosbymichael It'll require pretty intense script inside container as I see.

**Comment by crosbymichael** [comment]
This method is something that can be unit tested

**Comment by LK4D4** [comment]
@crosbymichael oh, okay, I forgot about unit-tests at all :)

**Comment by calavera** [comment]
LGTM

**Comment by LK4D4** [comment]
@crosbymichael Added test

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
