### PR TITLE
ci/gha: use v3 tag for actions/cache

### PR DESCRIPTION
**Pull request by kolyshkin**
This tag points to the latest v3 version (currently v3.0.11).

Mainly done to avoid cluttering git history with multiple minor v3 upgrades (see e.g. #3634, #3624, #3621, #3566, #3557, #3528, #3505, #3458).

This (using the x.y.z version format) has happened due to #3444; I guess there was no `v3` tag back then.

NB: do not accept dependabot PRs that switch from `vN` to `vX.Y.Z`

### CODE REVIEW

**Comment by kolyshkin** [comment]
@opencontainers/runc PTAL

**Comment by kolyshkin** [comment]
@opencontainers/runc-maintainers PTAL this is your simplest PR ever to LGTM

**Review by AkihiroSuda — APPROVED** [review]
Generally I’d rather argue that we should pin a specific version (with the hash) for supply chain security, but I guess we can treat GitHub-official actions exceptionally, so LGTM

**Review by hqhq — APPROVED** [review]

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
> Generally I’d rather argue that we should pin a specific version (with the hash) for supply chain security, but I guess we can treat GitHub-official actions exceptionally, so LGTM

agreed on this one

**Pull request merged**
