### PR TITLE
Minor wording enhancement in readme

### PR DESCRIPTION
**Pull request by glikson**
Clarifying a bit the explanation why fine-grained control is benefitial.

### CODE REVIEW

**Comment by crosbymichael** [comment]
@glikson Hi, you need to have your DCO in the commit message, not in the PR comment.  A simple `git commit -s --amend` would resolve this and then force pushing your change to your branch. 

Thanks for the change!

**Comment by glikson** [comment]
@crosbymichael thanks! done.

**Comment by crosbymichael** [comment]
LGTM

**Comment by cyphar** [comment]
LGTM.

**Pull request merged**
