### PR TITLE
Add pause/resume commands

### PR DESCRIPTION
**Pull request by tonistiigi**

### CODE REVIEW

**Comment by rajasec** [comment]
@tonistiigi 
I've noticed the issue in docker pause and checkpoint.. not sure whether runc with the pause handles this situation
https://github.com/xemul/criu/issues/20

**Comment by mrunalp** [comment]
LGTM

**Comment by tonistiigi** [comment]
Just so that everything is clear, this does not solve the issue of checkpoint conflicting with pause.

**Comment by crosbymichael** [comment]
@tonistiigi can you change `pause` `resume`?

**Comment by tonistiigi** [comment]
@crosbymichael done

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
