### PR TITLE
[debug] checking why cirrus ci fails on almalinux-9

### PR DESCRIPTION
**Pull request by kolyshkin**

### CODE REVIEW

**Comment by kolyshkin** [comment]
It is stuck in "update paused container" test, here it is:

https://github.com/opencontainers/runc/blob/d82235c9d0e249c89f136811b97c9277eae80f8c/tests/integration/update.bats#L830C1-L853C1

This is either caused by a recently merged PR, or by a recent change in Alma Linux 9.

**Comment by kolyshkin** [comment]
> This is either caused by a recently merged PR, or by a recent change in Alma Linux 9.

Might be a kernel update. It worked with previous kernel (5.14.0-427.33.1.el9_4.x86_64) but started failing with the latest one (5.14.0-427.37.1.el9_4.x86_64).

Trying to reproduce locally in a vagrant, no luck so far.

**Comment by kolyshkin** [comment]
Managed to run cirrus-ci with a terminal. Here's `ps axf` after the hang (but for some reason terminal has frozen right after this, too).

```
   2439 ?        Ss     0:00 /usr/lib/systemd/systemd-logind
   2461 ?        Ssl    0:00 /usr/bin/google_metadata_script_runner startup
   2550 ?        S      0:00  \_ /bin/sh /tmp/metadata-scripts2594802517/startup-script
   2840 ?        Sl     0:05      \_ ./cirrus agent -task-id 4667260143403008 -client-token 50d941f56a554856be4124dc705066
   3030 pts/0    Ss     0:00          \_ /usr/bin/bash
   4092 pts/0    S+     0:00          |   \_ top
   3884 pts/1    Ss     0:00          \_ /usr/bin/bash
 129361 pts/1    R+     0:00          |   \_ ps axf
  92962 ?        Ss     0:00          \_ /usr/bin/bash /tmp/scriptsf485f3b9d5d1e0826377641b90b7b0ca.sh
  92963 ?        S      0:00              \_ ssh -tt localhost make -C /home/runc localintegration RUNC_USE_SYSTEMD=yes
   2801 ?        Ss     0:00 /usr/sbin/crond -n
  10895 ?        Ss     0:00 sshd: /usr/sbin/sshd -D [listener] 2 of 10-100 startups
  92964 ?        Ss     0:00  \_ sshd: root [priv]
  92967 ?        S      0:00  |   \_ sshd: root@pts/2
  92968 pts/2    Ss+    0:00  |       \_ make -C /home/runc localintegration RUNC_USE_SYSTEMD=yes
  93813 pts/2    S+     0:00  |           \_ bash /usr/local/libexec/bats-core/bats -t tests/integration
  93835 pts/2    S+     0:00  |               \_ bash /usr/local/libexec/bats-core/bats-exec-suite --dummy-flag /home/runc
 125837 pts/2    S+     0:00  |               |   \_ bash /usr/local/libexec/bats-core/bats-exec-file --dummy-flag /home/r
 129243 pts/2    S+     0:00  |               |       \_ bash /usr/local/libexec/bats-core/bats-exec-test --dummy-flag /ho
 129351 pts/2    S+     0:00  |               |           \_ bash /usr/local/libexec/bats-core/bats-exec-test --dummy-flag
 129352 pts/2    Sl+    0:00  |               |               \_ /home/runc/tests/integration/../../runc --systemd-cgroup 
  93836 pts/2    S+     0:00  |               \_ bash /usr/local/libexec/bats-core/bats -t tests/integration
  93837 pts/2    S+     0:00  |               \_ bash /usr/local/libexec/bats-core/bats-format-cat --dummy-flag
  93838 pts/2    S+     0:00  |                   \_ cat
 128809 ?        Ss     0:00  \_ sshd: [accepted]
 129360 ?        Ss     0:00  \_ sshd: [accepted]
  16347 ?        Ss     0:00 /usr/libexec/sssd/sssd_kcm --uid 0 --gid 0 --logger=files
  16493 ?        Ss     0:00 /usr/lib/systemd/systemd --user
  16513 ?        S      0:00  \_ (sd-pam)
 129268 pts/2    Sl+    0:00 /home/runc/tests/integration/../../tests/cmd/recvtty/recvtty --pid-file /tmp/bats-run-oxo7hO/
 129306 ?        Ds     0:00 [sh]
[root@cirrus-task-4667260143403008 runc]# 
```

**Comment by lifubang** [comment]
My PR(#4452) has been green now, maybe it has been fixed?

**Comment by kolyshkin** [comment]
It's working again so I guess this was some misconfiguration in GHA dept.

**Pull request closed without merging**
