### PR TITLE
Reorder checks in Walk to avoid panics

### PR DESCRIPTION
**Pull request by LK4D4**
ping @tibor @ibuildthecloud

### CODE REVIEW

**Comment by tiborvass** [comment]
This PR fixes the issues we were having with docker.

**Comment by mrunalp** [comment]
I am seeing some errors in other tests running locally

```
=== RUN TestEnter
--- FAIL: TestEnter (0.32s)
        exec_test.go:251: unexpected number of processes [] 395 401
```

**Comment by crosbymichael** [comment]
Same error locally

**Comment by LK4D4** [comment]
Yup, I see.

**Comment by LK4D4** [comment]
@mrunalp @crosbymichael fixed

**Comment by mrunalp** [comment]
okay tests are passing for me now. @tiborvass @ibuildthecloud. Do you guys want to try the updated patch as well?

**Comment by ibuildthecloud** [comment]
I'll try tonight

**Comment by ibuildthecloud** [comment]
@imikushin can you test this too?

**Comment by tiborvass** [comment]
@mrunalp this is basically blocking docker 1.9 so if someone could test/review/merge I would greatly appreciate it :)

**Comment by crosbymichael** [comment]
LGTM

**Comment by mrunalp** [comment]
@tiborvass I am good with it from runc perspective ;) LGTM

**Comment by crosbymichael** [comment]
@tiborvass what is this docker u speak of?

**Comment by mrunalp** [comment]
Heh :laughing:

**Comment by icecrime** [comment]
@crosbymichael

**Comment by ibuildthecloud** [comment]
We applied this to docker 1.8 and it worked.  Docker 1.9 blows up for us for different reasons, but this patch seems good.

**Pull request merged**
