### PR TITLE
Fix update cpuset on single processor box

### PR DESCRIPTION
**Pull request by hqhq**
Fixes: #1050

Signed-off-by: Qiang Huang <h.huangqiang@huawei.com>

### CODE REVIEW

**Comment by cyphar** [comment]
LGTM

**Comment by cyphar** [comment]
Why not just set the `cpuset` to `0`, which would work on a single processor?

**Comment by hqhq** [comment]
@cyphar There is no need to test it on single processor because you can't verify it by checking cgroup values anyway. And this is basically the reason we set to `1`.

**Comment by cyphar** [comment]
LGTM. Fair enough.

**Comment by mikebrow** [comment]
Works for me as well!

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
