### PR TITLE
Add CAP prefix for capabilities

### PR DESCRIPTION
**Pull request by mrunalp**
See https://github.com/opencontainers/specs/pull/160

Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by mrunalp** [comment]
@LK4D4 @crosbymichael @dqminh ping

**Comment by LK4D4** [comment]
It's sorta breaking change for libcontainer :) Also capability library using words without `CAP` for their `String()` method.

**Comment by mrunalp** [comment]
@LK4D4 One option is to allow it in the config but strip it out while passing to libcontainer for now.

**Comment by dqminh** [comment]
Or maybe we can accept both. Detect if the old caps are started with `CAP_`, accepts them and rewrite the state to have `CAP_` prefix.

**Comment by crosbymichael** [comment]
LGTM

**Comment by mrunalp** [comment]
Rebased @LK4D4 ping.

**Comment by dqminh** [comment]
If we merge this, we will still require a compatibility layer in docker to add `CAP_` for now right @mrunalp ?

**Comment by mrunalp** [comment]
@dqminh Yes, but I think that should be okay given all the other changes that we have made. @crosbymichael can correct me.

**Comment by dqminh** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
