### PR TITLE
tests/integration/get-images.sh: fix busybox.tar.xz URL

### LINKED ISSUE #3699: CI: `404  Failed to get https://github.com/docker-library/busybox/raw/dist-amd64/stable/glibc/busybox.tar.xz`
```
panic: getImages error exit status 1 (output: curl: (22) The requested URL returned error: 404 
Failed to get https://github.com/docker-library/busybox/raw/dist-amd64/stable/glibc/busybox.tar.xz
)

goroutine 1 [running]:
github.com/opencontainers/runc/libcontainer/integration.init.1()
	/home/runner/work/runc/runc/libcontainer/integration/utils_test.go:37 +0x2c5
FAIL	github.com/opencontainers/runc/libcontainer/integration	0.133s
```

https://github.com/opencontainers/runc/actions/runs/3896184715/jobs/6652404118

Thanks to @egernst for finding this in https://github.com/opencontainers/runc/pull/3698

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Fix #3699

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
Or should we pin to a commit, as suggested in the ticket? busy box has had some breaking changes recently, so it may be worth pinning to a version.

**Comment by AkihiroSuda** [comment]
> Or should we pin to a commit, as suggested in the ticket? busy box has had some breaking changes recently, so it may be worth pinning to a version.

That can be complicated for multi-arch branches.
Eventually we should just use skopeo or something to fetch an OCI image from a registry with a fixed digest.

**Comment by tianon** [comment]
Yeah, I started down that road with something like this:

```bash
arch=$(go env GOARCH)
case $arch in
	# https://github.com/docker-library/busybox/tree/dist-amd64
	amd64) commit=31d342ad033e27c18723a516a2274ab39547be27 ;;

	arm)
		arm=$(go env GOARM)
		arch=$arch${arm:+v$arm}
		case $arm in
			# https://github.com/docker-library/busybox/tree/dist-arm32v5
			5) commit=96ea82ea25565f78b50bd032d5768d64985d6e11 ;;
			# https://github.com/docker-library/busybox/tree/dist-arm32v7
			7 | '' | *) commit=5cb6c347469e86e4468e5e248de751b3598bb577 ;;
		esac
		;;

	# https://github.com/docker-library/busybox/tree/dist-arm64v8
	arm64) commit=94c664b5ca464546266bce54be0082874a44c7b2 ;;

	# https://github.com/docker-library/busybox/tree/dist-i386
	386) commit=461a473aef31b7726ea99909a24551bf44565c05 ;;

	# https://github.com/docker-library/busybox/tree/dist-mips64le
	mips64le) commit=47f73f7c735dcd6760a976bfe0012d251b6ef0a9 ;;

	# https://github.com/docker-library/busybox/tree/dist-ppc64le
	ppc64le) commit=9ca13bc214717966383cf97e08606b444b7300e4 ;;

	# https://github.com/docker-library/busybox/tree/dist-s390x
	s390x) commit=a03814d21bcf97767121bb9422a742ec237a09e2 ;;

	*) echo >&2 "error: unsupported architecture: '$arch'"; exit 1 ;;
esac
BUSYBOX_URL="https://github.com/docker-library/busybox/raw/$commit/stable/glibc/busybox.tar.xz"
```

but then I noticed this `$arch` is used for downloading Debian `rootfs.tar.xz` files too, which is _also_ going to break soon :confused:

**Comment by tianon** [comment]
It's more verbose, but alternative approach in https://github.com/opencontainers/runc/pull/3701

**Comment by AkihiroSuda** [comment]
@opencontainers/runc-maintainers 
To unblock merging other PRs, can we merge this as-is and revisit #3701 (or another approach) separately?

**Comment by thaJeztah** [comment]
I'm okay with merging this one as-is, and work on improving after that

**Review by kolyshkin — APPROVED** [review]
LGTM

**Comment by kolyshkin** [comment]
Backport to 1.1 is in #3729.

**Pull request merged**
