### PR TITLE
[1.0] Use Cirrus CI for Vagrant tests

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Cherry-pick https://github.com/opencontainers/runc/pull/3088 #3104

### CODE REVIEW

**Review by kolyshkin — DISMISSED** [review]
LGTM

**Comment by adrianreber** [comment]
No need to run CentOS 7 or 8 in Vagrant on Cirrus CI. You can directly use the CentOS images to boot:

https://github.com/checkpoint-restore/criu/blob/criu-dev/.cirrus.yml

For Fedora you probably need Vagrant (or something) as I have not found Fedora images for Google Cloud Engine.

**Comment by AkihiroSuda** [comment]
> No need to run CentOS 7 or 8 in Vagrant on Cirrus CI. 

PR is appreciated (for the master branch)

**Comment by adrianreber** [comment]
> > No need to run CentOS 7 or 8 in Vagrant on Cirrus CI.
> 
> PR is appreciated (for the master branch)

See #3104

**Comment by kolyshkin** [comment]
Switching to draft until https://github.com/opencontainers/runc/pull/3104 is merged; when we need to port both (I guess).

**Review by kolyshkin — APPROVED** [review]
Assuming it's a clean cherry-pick, LGTM

**Comment by AkihiroSuda** [comment]
Yes, cherry-picks were clean

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
