### PR TITLE
Fix MAJ:MIN io.stat parsing order

### LINKED ISSUE #2191: io.stat: MAJ:MIN parsing order is wrong
According to the https://www.kernel.org/doc/Documentation/cgroup-v2.txt
```
  io.stat
	A read-only nested-keyed file which exists on non-root
	cgroups.

	Lines are keyed by $MAJ:$MIN device numbers and not ordered.
	The following nested keys are defined.
```
In code we see the opposite order in `io.stat` file parsing function:
https://github.com/opencontainers/runc/blob/master/libcontainer/cgroups/fs/io_v2.go#L105

### PR DESCRIPTION
**Pull request by Zyqsempai**
Fix #2191 

Fix MAJ:MIN io.stat parsing order
 
Signed-off-by: Boris Popovschi <zyqsempai@mail.ru>

### CODE REVIEW

**Comment by Zyqsempai** [comment]
@AkihiroSuda, @crosbymichael  Take a look at this one, please.

**Comment by Zyqsempai** [comment]
@crosbymichael Can we merge it?

**Comment by AkihiroSuda** [comment]
sorry this needs rebase

**Comment by AkihiroSuda** [comment]
Please retry CI?

**Comment by Zyqsempai** [comment]
@AkihiroSuda Sorry, currently I am in vacation, without laptop, so i am not able to do that. Sorry.

**Comment by AkihiroSuda** [comment]
Any maintainer can restart CI?

**Comment by Zyqsempai** [comment]
@AkihiroSuda PTAL, CI is ok now

**Comment by Zyqsempai** [comment]
@hqhq PTAL

**Comment by caniszczyk** [comment]
ping @opencontainers/runc-maintainers

**Comment by hqhq** [comment]
LGTM

**Comment by cyphar** [comment]
LGTM.

**Pull request closed without merging**
