### PR TITLE
Remove lk4d4 as a maintainer

### LINKED ISSUE #1361: Remove "Alexander Morozov" as a MAINTAINER
https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/JvN8jWhS55c

### PR DESCRIPTION
**Pull request by crosbymichael**
Closes #1361

Signed-off-by: Michael Crosby <crosbymichael@gmail.com>

### CODE REVIEW

**Comment by duglin** [comment]
I think the failures in https://github.com/opencontainers/runc/pull/1362#issuecomment-284864739 means he's not allowed to leave.

**Comment by crosbymichael** [comment]
bot atomic loves @LK4D4

**Comment by avagin** [comment]
LBFM

**Comment by cyphar** [comment]
LGTM. Thanks for all your contributions @LK4D4, I'm sure we'll still see you around!

**Comment by mrunalp** [comment]
LGTM you will be missed here @LK4D4

**Comment by hqhq** [comment]
Thanks @LK4D4 for all your contributions!

**Pull request merged**
