### PR TITLE
Don't set cross-compilation variables in Makefile

### PR DESCRIPTION
**Pull request by kolyshkin**
This is an alternative to #4345, fixing the issue with using new runc for Docker (https://github.com/moby/moby/pull/47666)

---

This feature (cc_platform.mk and its sourcing from Makefiles) was added by commit dac4171746546 ("runc-dmz: reduce memfd binary cloning cost with small C binary") as part of dmz work.

From what I see, this is not needed for `make releaseall` as we already set these variables using `set_cross_vars` shell function. My best guess is this was mostly needed for testing.

The big issue though is these variables are guessed based on our cross-compilation environment, meaning they won't work in other cases (such as native compilation on non-x86_64 platforms, or using other cross-compilation tools). One such example is Moby build which uses https://github.com/tonistiigi/xx.

Besides, it's a duplication of effort in scripts/lib.sh, which is prone to error.

Let's remove this from the Makefiles, and rework the script which sets those variables so it can be used for other scenarios as well.

For example, to test cross-compilation locally, use

	make $TARGET -- $(./script/cross.sh $ARCH)

### CODE REVIEW

**Comment by kolyshkin** [comment]
ptal @cyphar

**Comment by cyphar** [comment]
Grrr, GitHub ate my comment.

<hr>

I added `cc_platform.mk` in order to keep cross-compilation with `GOARCH=xxx make` working.
This was needed for the CI as well, but trying to avoid breaking that was something that I wanted if possible. It seems quite unfortunate to break that and instead require 'make $TARGET -- $(./script/cross.sh $ARCH)' (though it seems that didn't end up working -- the CI now has `sh -c "$(./script/cross.sh 386); make localunittest"`).

To be clear, I agree that the duplication is annoying. Maybe we could remove `cc_platform.mk` and make our Makefile use `./script/cross.sh` internally (I tried to figure out a way to do this when doing the `runc-dmz` work, but it seemed that there wasn't a reasonable way of doing it.)

For the `xx` compatibility issue, I'm a little confused. There almost certainly are bugs in `cc_platform.mk` but the `xx` docs seem to indicate they provide `triple-...` aliases which `cc_platform.mk` would use. I even suspect that doing `export CC=xx-gcc` (or `xx-clang`) would work. What does `xx-go --wrap` do?

**Comment by kolyshkin** [comment]
Hmm, I had a wrong assumption that `cc_platform.mk` overwrites the value of `CC`. It does not.

What's wrong is it assumes native compilation here:
https://github.com/opencontainers/runc/blob/3778ae603c706494fd1e2c2faf83b406e38d687d/cc_platform.mk#L14

It doesn't work when xx-go --wrap sets up `~/.config/go.env`.

To work around this, we can check the origin of GOENV like @tonistiigi suggested in https://github.com/moby/moby/pull/48160#issuecomment-2227434835. Opened #4349.

**Comment by kolyshkin** [comment]
> To work around this, we can check the origin of GOENV like @tonistiigi suggested in [moby/moby#48160 (comment)](https://github.com/moby/moby/pull/48160#issuecomment-2227434835). Opened #4349.

It's even easier -- use xx to set CC and CFLAGS explicitly, this way cc_platform doesn't do any guessing. See https://github.com/moby/moby/pull/48160

**Pull request closed without merging**
