### PR TITLE
Move to cmd/runc

### PR DESCRIPTION
**Pull request by gwoo**
Here are some pretty big changes
 - Moved to cmd/runc
 - Remove libcontainer subdirectory in favor of modified GOPATH and Godeps.
 - Abstract spec loading and provide SpecConfig interface

### CODE REVIEW

**Comment by mrunalp** [comment]
The plan as of now that libcontainer itself will be discontinued, hence it wasn't vendored in.

**Comment by gwoo** [comment]
Vendoring it in still seems like an easier path to it's replacement. Where will it go?

**Comment by gwoo** [comment]
I broke apart the commits to make it easier to see the major changes.

**Comment by stevvooe** [comment]
I'm a big :+1: on moving to this style of layout. Maybe splitting the vendoring out into another PR will let us better discuss each point.

**Comment by crosbymichael** [comment]
Yes, we will be redirecting `docker/libcontainer` to this repository and the work will be done in this one place.  It's mostly to make it easy for people contributing to the project to be able to update implementation and `runc` in one PR and not have to manage the dependency between multiple repositories.

**Comment by gwoo** [comment]
@stevvooe @crosbymichael We can probably close this in favor of https://github.com/opencontainers/runc/pull/19

**Pull request closed without merging**
