### PR TITLE
Take out readonly restriction on mounting container cgroups

### PR DESCRIPTION
**Pull request by mrunalp**
See #91 
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by crosbymichael** [comment]
You should check for the RDONLY flag in `m.Flags` for the data passed by the user.

**Comment by mrunalp** [comment]
Yeah, of course. Fixing.

**Comment by mrunalp** [comment]
Added check for RDONLY. Should we care about other stuff in m.Flags or just checking for RDONLY is good here?

**Comment by mrunalp** [comment]
Closing this as we have too many dupes for this.

**Comment by hqhq** [comment]
Thanks @mrunalp

**Pull request closed without merging**
