### PR TITLE
release: add runc.keyring file

### PR DESCRIPTION
**Pull request by cyphar**
In order to allow any of the maintainers to cut releases for runc,
create a keyring file that distributions can use to verify that releases
are signed by one of the maintainers.

The format matches the gpg-offline format used by openSUSE packaging,
but it can be easily imported with `gpg --import` so any distribution
should be able to handle this keyring format wtihout issues.

Each key includes the GitHub handle of the associated user, and a new
verification step is added to CI to ensure that the key is actually one
of the keys the user has registered with GitHub (as well as being a
maintainer).

Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>

### CODE REVIEW

**Comment by cyphar** [comment]
Unfortunately it looks like you cannot give actions write access using `GITHUB_TOKEN` from a pull request. The only way to get this to work would be to create a personal access token to store as a secret, but unfortunately I cannot create a scoped one for opencontainers (I could create a classic personal access token for myself but those aren't scoped).

(It's also a bit ugly that `trstringer/manual-approval` creates a new issue. Ideally it would all be contained in this pull request. Maybe we can fork `manual-approval` for this purpose? Idk.)

All of the other logic works, so maybe we can just get the core bits in and then work on a GHA setup later?

**Comment by cyphar** [comment]
I've dropped the special review system (arguably it doesn't match the governance rules of runc anyway). Instead, we now have a validation step which ensures that each key in `runc.keyring` actually matches the publicly-listed GPG keys of the specified GitHub user (and that the user is actually a maintainer in `MAINTAINERS`).

Note that if you wish to add your key to the keyring, you need to make sure that it was uploaded recently (otherwise GitHub won't list the key in `https://github.com/username.gpg` which means it will fail the validation checks) and it doesn't contain any subkeys not present in the GitHub version of the key.

**Review by AkihiroSuda — APPROVED** [review]

**Review by kolyshkin — APPROVED** [review]
LGTM

**Comment by kolyshkin** [comment]
1.1 backport: #3838

**Pull request merged**
