### PR TITLE
[1.1 backport] build(deps): bump github.com/cyphar/filepath-securejoin

### PR DESCRIPTION
**Pull request by thaJeztah**
- backport of https://github.com/opencontainers/runc/pull/4011
- addresses GHSA-6xv5-86q9-7xr8

Bumps [github.com/cyphar/filepath-securejoin](https://github.com/cyphar/filepath-securejoin) from 0.2.3 to 0.2.4.
- [Release notes](https://github.com/cyphar/filepath-securejoin/releases)
- [Commits](https://github.com/cyphar/filepath-securejoin/compare/v0.2.3...v0.2.4)

---
updated-dependencies:
- dependency-name: github.com/cyphar/filepath-securejoin dependency-type: direct:production update-type: version-update:semver-patch ...

(cherry picked from commit c7ad2749fde1445b627b53a568aa85e3ca50fbd2)

### CODE REVIEW

**Comment by thaJeztah** [comment]
As we're not targeting Windows, GHSA-6xv5-86q9-7xr8 is mostly "optics"; I noticed security scanners were flagging use of the dependency.

**Review by cyphar — APPROVED** [review]
LGTM, and yeah the issue doesn't affect us.

**Review by kolyshkin — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
Not sure if we do (at least, I wouldn't do it for this dependency update 😂), but I found myself updating this "indirect" dependency, and thought I might as well update it where it's used (in case there's gonna be more 1.1.x releases)

**Pull request merged**
