### PR TITLE
testcase code was refactored in `func TestValidate(t *testing.T)`

### PR DESCRIPTION
**Pull request by chchliang**
Signed-off-by: chchliang <chen.chuanliang@zte.com.cn>

### CODE REVIEW

**Comment by crosbymichael** [comment]
LGTM

**Comment by cyphar** [comment]
I don't really like this because it means that it's no longer obvious what test actually failed. Also, `expected` should be a boolean not a string.

**Comment by chchliang** [comment]
@cyphar 
I don't think so. because every attributes have validated,if fail then return different error, add comments to each test mock.

image

**Comment by hqhq** [comment]
What about expected error to occur but it was nil?

**Comment by chchliang** [comment]
@hqhq 
Expected value reversal, i haved changed, thanks.

**Comment by hqhq** [comment]
@chchliang You might've read me wrong, my question is following your answer to @cyphar 's question, if test failed because it expected error to occur but it was not, in your code, it's not obvious what test actually failed.

And neither `true` means return error or not are bad ideas, because `expected` variable is bad, your can use something like `expectError` to be explicit.

**Comment by chchliang** [comment]
@hqhq 
Yes, variable expected means only return error or not, i will change the variable name,so  easy  to understand what it means.

**Comment by cyphar** [comment]
@chchliang 

> I don't think so. because every attributes have validated,if fail then return different error, add comments to each test mock.

Okay, but the error doesn't necessarily tell you what test failed. For example, you could get multiple tests that produce the same error -- how am I (as a developer) meant to disambiguate them?

If you want  to refactor this code, make a common function that's shared between the different `TestXxx` functions so that `go test` remains sane (I'm NACK on this PR at the moment). Thanks.

**Comment by cyphar** [comment]
Maybe something like this:

```
func testValidateHelper(t *testing.T, config *configs.Config, shouldFail bool) {
  // ...
}
```

Which means you could reduce most of the tests into a one-liner.

**Comment by chchliang** [comment]
@cyphar 
I think that add attribute `testcase` to illustrate  function when test fail. WDYT?

image


image

**Comment by cyphar** [comment]
@chchliang You could do that, but I think a helper would be much easier to read.

**Comment by cyphar** [comment]
Another benefit of having separate functions is that you can specify which test to run with `go test` (`got test -run TestBlah`). Combining the tests makes you lose that benefit.

**Comment by chchliang** [comment]
@cyphar 
Yes, each has its advantages and disadvantages, after refactored, developer only set test data.

**Comment by cyphar** [comment]
While that might be true, it's only like 4 extra lines of boilerplate that a developer has to copy. I'll just be blunt -- I NACK this because it's not actually helpful as-is IMO. Maybe if you used sub-tests this would be more acceptable, but I still don't understand why "separate tests in separate functions, as per idiomatic Go" is a disadvantage.

**Comment by chchliang** [comment]
@cyphar 
I have modified, refactored with sub-tests.

**Comment by crosbymichael** [comment]
Lets keep the tests the same way.  There are advantages to having separate tests and as @cyphar pointed out its not that much more boilerplate to add them.

Thanks for the PR @chchliang

**Pull request closed without merging**
