### PR TITLE
validator: unbreak sysctl net.* validation

### PR DESCRIPTION
**Pull request by cyphar**
When changing this validation, the code actually allowing the validation
to pass was removed. This meant that any net.* sysctl would always fail
to validate.

Fixes: bc84f83344fd ("fix docker/docker#27484")
Reported-by: Justin Cormack <justin.cormack@docker.com>
Signed-off-by: Aleksa Sarai <asarai@suse.de>

Fixes #1138

/cc @justincormack Does this fix the issue you mentioned?

### CODE REVIEW

**Comment by cyphar** [comment]
I've also added a test -- it turns out we weren't testing that `sysctl` validation ever succeeded.

**Comment by gaocegege** [comment]
Ah, sorry about it. I was too careless.

LGTM

**Comment by cyphar** [comment]
Don't sweat it.

/cc @opencontainers/runc-maintainers

**Comment by hqhq** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
