### PR TITLE
VERSION: release 1.0.0-rc94

### PR DESCRIPTION
**Pull request by cyphar**
This PR needs 5 votes to pass:

- [ ] Michael Crosby <michael@docker.com> (@crosbymichael)
- [x] Mrunal Patel <mpatel@redhat.com> (@mrunalp)
- [x] Daniel, Dao Quang Minh <dqminh89@gmail.com> (@dqminh)
- [x] Qiang Huang <h.huangqiang@huawei.com> (@hqhq)
- [x] Aleksa Sarai <cyphar@cyphar.com> (@cyphar)
- [x] Akihiro Suda <akihiro.suda.cz@hco.ntt.co.jp> (@AkihiroSuda)
- [x] Kir Kolyshkin <kolyshkin@gmail.com> (@kolyshkin)

Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>

### CODE REVIEW

**Review by AkihiroSuda — APPROVED** [review]

**Review by AkihiroSuda — CHANGES_REQUESTED** [review]
Moby CI is failing: https://github.com/opencontainers/runc/issues/2928

**Review by AkihiroSuda — APPROVED** [review]
https://github.com/opencontainers/runc/issues/2928 is an issue of Moby, not runc, so still LGTM

**Comment by kolyshkin** [comment]
A couple of minor PRs we might want to merge before are:
* https://github.com/opencontainers/runc/pull/2913 (fixes a test case for the next criu release, 3.16)
* https://github.com/opencontainers/runc/pull/2902 (fixes a c/r bug with external bind mount with a symlink)

Not super important though, so this LGTM.

**Comment by cyphar** [comment]
I've also noticed that `scripts/release.sh` appears to not work on my machine so I might want to debug that before we do a release...

**Comment by kolyshkin** [comment]
> EDIT: We need to do a go clean -cache in script/release.sh because apparently Go now caches pkg-config...

The alternative is adding `-a` to `go build` flags. I haven't tested it, but if it works, we can do something like
```diff
diff --git a/script/release.sh b/script/release.sh
index 2156fca3..d2190ce8 100755
--- a/script/release.sh
+++ b/script/release.sh
@@ -62,7 +62,7 @@ EOF
        )
        mv "$tarball"{,.asc} "$builddir"
 
-       make -C "$root" PKG_CONFIG_PATH="${prefix}/lib/pkgconfig" COMMIT_NO= static
+       make -C "$root" PKG_CONFIG_PATH="${prefix}/lib/pkgconfig" COMMIT_NO= EXTRA_FLAGS="-a" static
        rm -rf "$prefix"
        mv "$root/$project" "$1"
 }
```

**Comment by kolyshkin** [comment]
Source for the above: https://github.com/golang/go/issues/24544#issuecomment-410127446

**Comment by mrunalp** [comment]
LGTM

**Review by kolyshkin — APPROVED** [review]
LGTM

**Comment by cyphar** [comment]
Alright, that's the 4-vote threshold passed. I'll prepare the release today.

**Comment by cyphar** [comment]
/ping @opencontainers/runc-maintainers 

It would be nice if I could do the release tomorrow.

**Review by dqminh — APPROVED** [review]

**Comment by dqminh** [comment]
LGTM

**Comment by kolyshkin** [comment]
I think I found a regression which better be fixed before we release rc94; will have a PR ready shortly (and changed this one to draft so we won't merge it earlier).

**Comment by kolyshkin** [comment]
> I think I found a regression which better be fixed before we release rc94; will have a PR ready shortly

https://github.com/opencontainers/runc/pull/2936

**Comment by hqhq** [comment]
> > I think I found a regression which better be fixed before we release rc94; will have a PR ready shortly
> 
> #2936

I figured the alternative fix #2937 is merged, so LGTM now.

**Comment by hqhq** [comment]
LGTM

**Review by hqhq — APPROVED** [review]

**Comment by cyphar** [comment]
I will rebase this and we can just take all the LGTMs as a pass for this release. :sweat_smile:

**Comment by AkihiroSuda** [comment]
@cyphar Can we fix cgroup2 CI before rc94? https://github.com/opencontainers/runc/pull/2944

**Comment by cyphar** [comment]
Yeah let's do that first. I'll review it on Monday.

**Comment by cyphar** [comment]
I've rebased this again -- @opencontainers/runc-maintainers can I get two LGTMs to be able to merge the release PR? Thanks.

**Review by hqhq — APPROVED** [review]

**Review by AkihiroSuda — APPROVED** [review]

**Pull request closed without merging**
