### PR TITLE
Update criu to 3.1

### PR DESCRIPTION
**Pull request by crosbymichael**
This updates criu to the latest release to help resolve some of the
issues we are seeing on the CI.

Signed-off-by: Michael Crosby <crosbymichael@gmail.com>

### CODE REVIEW

**Comment by crosbymichael** [comment]
Well that didn't work

**Comment by avagin** [comment]
I will take a look at this.

**Comment by avagin** [comment]
It isn't reproduced each time: https://travis-ci.org/avagin/runc/builds/241371998

**Comment by avagin** [comment]
The problem is that runc state CRID returned 0 for a checkpointed container

```
38:          # after checkpoint busybox is no longer running
39:           runc state test_busybox
40:          [ "$status" -ne 0 ]
```

```
# runc state test_busybox (status=0):

# {

#   "ociVersion": "1.0.0-rc5-dev",

#   "id": "test_busybox",

#   "pid": 0,

#   "status": "stopped",

#   "bundle": "/tmp/busyboxtest",

#   "rootfs": "/tmp/busyboxtest/rootfs",

#   "created": "2017-06-09T17:49:06.676553754Z",

#   "owner": ""

# }
```

**Comment by avagin** [comment]
ct.Destroy() is always called after cr.Checkpoint()
```
                defer destroy(container)
                options := criuOptions(context)
                // these are the mandatory criu options for a container
                setPageServer(context, options)
                setManageCgroupsMode(context, options)
                if err := setEmptyNsMask(context, options); err != nil {
                        return err
                }
                if err := container.Checkpoint(options); err != nil {
                        return err
                }
```

**Comment by avagin** [comment]
I don't think that a problem is in CRIU 3.1, so we can accept this changes.

**Comment by avagin** [comment]
I redirected runc log messages to stderr and now we can see that runc reports msg="container is not destroyed".

```
# runc --criu /usr/local/sbin/criu checkpoint test_busybox (status=0):
# time="2017-06-09T23:54:19Z" level=error msg="container is not destroyed" 
# runc state test_busybox (status=0):
# {
#   "ociVersion": "1.0.0-rc5-dev",
#   "id": "test_busybox",
#   "pid": 0,
#   "status": "stopped",
#   "bundle": "/tmp/busyboxtest",
#   "rootfs": "/tmp/busyboxtest/rootfs",
#   "created": "2017-06-09T23:54:18.502863726Z",
#   "owner": ""
# }
# runc list (status=0):
# ID             PID         STATUS      BUNDLE             CREATED                          OWNER
# test_busybox   0           stopped     /tmp/busyboxtest   2017-06-09T23:54:18.502863726Z   root
# runc kill test_busybox KILL (status=1):
# time="2017-06-09T23:54:19Z" level=error msg="container_linux.go:308: signaling init process caused \"os: process already finished\"\n" 
# container_linux.go:308: signaling init process caused "os: process already finished"
# runc delete test_busybox (status=0):
```

**Comment by crosbymichael** [comment]
Must be a race in bats around destroy

**Comment by avagin** [comment]
It can be a problem is in runType(). There we call unix.Kill(pid, 0) to check whether a process is alive or not. But kill() returns zero for zombies too.
```
[root@fc24 runc]# ps -p 9392
  PID TTY          TIME CMD
 9392 pts/1    00:00:00 sleep <defunct>
[root@fc24 runc]# strace -e kill kill -0 9392
kill(9392, SIG_0)                       = 0
+++ exited with 0 +++
```

**Comment by avagin** [comment]
doesInitProcessExist() checks a start time for a process. Maybe we should check a process state there too?

**Comment by wking** [comment]
With #1489 landed, I expect kicking Travis will get your tests passing here.

**Comment by crosbymichael** [comment]
@avagin @wking the CI is still failing.  We need to get this fixed or disable the test temporarily.  I have checkpoint tests running on containerd and they are robust and work fine so I'm leaning towards an issue with either bats, our test setup, or the runc handling on the CLI.

**Pull request closed without merging**
