### PR TITLE
libcontainer: rm windows pieces (carry #2700)

### PR DESCRIPTION
**Pull request by thaJeztah**
carry of https://github.com/opencontainers/runc/pull/2700
closes https://github.com/opencontainers/runc/pull/2700

Rebased the branch, and included https://github.com/kolyshkin/runc/pull/9.

I also opened draft PR's to run CI in moby and containerd with this branch in https://github.com/moby/moby/pull/42143 and https://github.com/containerd/containerd/pull/5301

### CODE REVIEW

**Comment by thaJeztah** [comment]
centos failed to start, so closed/reopened to trigger again

**Comment by thaJeztah** [comment]
All green now 🎉 

@kolyshkin @AkihiroSuda PTAL

**Review by cyphar — APPROVED** [review]
LGTM.

**Review by kolyshkin — APPROVED** [review]
LGTM

**Pull request merged**
