### PR TITLE
Makefile: `make install` requires ./runc

### PR DESCRIPTION
**Pull request by vbatts**
as if it weren't already implied. :-)

Signed-off-by: Vincent Batts <vbatts@redhat.com>

### CODE REVIEW

**Comment by crosbymichael** [comment]
Nooooo! ;)

This would mean that when I do `sudo make install` it will search for `go` in my system path that does not exist.

**Comment by vbatts** [comment]
@crosbymichael only if `./runc`

**Comment by crosbymichael** [comment]
Personally I would like to keep it as `make` makes and `make install` installs and keep the split.

**Comment by vbatts** [comment]
right on

**Pull request closed without merging**
