### PR TITLE
Modifying cpu attribute data type as per specs

### PR DESCRIPTION
**Pull request by rajasec**
As per specs, modified cpu subsystem attributes to uint64 instead of int64

Signed-off-by: rajasec <rajasec79@gmail.com>

### CODE REVIEW

**Comment by hqhq** [comment]
There is still discussion on going, https://github.com/opencontainers/specs/pull/233 we are thinking about change the settings to points. I think we should hold on this PR for a while?

**Comment by mrunalp** [comment]
Yes, we should wait for the spec discussion to conclude.

**Comment by cyphar** [comment]
I think we should transition all of the cgroup types, as per opencontainers/specs#233 (once it's merged), in one PR so we make sure we've covered everything upfront.

**Comment by crosbymichael** [comment]
This was fixed in the recent spec update

**Pull request closed without merging**
