### PR TITLE
README.md: simplify Docker image example

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by cyphar** [comment]
LGTM. Build failures are completely unrelated to this PR.

**Comment by mrunalp** [comment]
Closing/reopening to trigger rebuild.

**Comment by mrunalp** [comment]
That did not work :/

**Comment by runcom** [comment]
I'll rebase it and push force :smile:

**Comment by runcom** [comment]
rebased and triggered

**Comment by mrunalp** [comment]
Thanks! LGTM

**Pull request merged**
