### PR TITLE
specconv: avoid skipping gidmappings applied when uidmappings is empty

### PR DESCRIPTION
**Pull request by Mashimiao**
Signed-off-by: Ma Shimiao <mashimiao.fnst@cn.fujitsu.com>

### CODE REVIEW

**Comment by wking** [comment]
This sounds like the cause [of this validation failure][1].

[1]: https://github.com/opencontainers/runtime-tools/pull/439#issuecomment-348090087

**Comment by Mashimiao** [comment]
Yes, it is.

**Comment by crosbymichael** [comment]
LGTM

**Comment by crosbymichael** [comment]
@mrunalp pullapprove is not registering your lgtm

**Comment by mrunalp** [comment]
LGTM

**Comment by mrunalp** [comment]
@crosbymichael Fixed. I think it doesn't like the lgtm from code review submit form.

**Comment by wking** [comment]
On Mon, Dec 11, 2017 at 05:50:48PM +0000, Mrunal Patel wrote:
> I think it doesn't like the lgtm from code review submit form.

That's because runc is still using a v1 PullApprove config [1].  If
you want to count GitHub approvals, you need to migrate to v2
(e.g. opencontainers/project-template#29,
opencontainers/runtime-spec#902).

[1]: https://github.com/opencontainers/runc/blob/c6e4a1ebeb1a72b529c6f1b6ee2b1ae5b868b14f/.pullapprove.yml

**Pull request merged**
