### PR TITLE
Add recvtty to install path

### PR DESCRIPTION
**Pull request by rajasec**
install & uninsnstall recvtty from /usr/local/sbin.
Signed-off-by: rajasec <rajasec79@gmail.com>

### CODE REVIEW

**Comment by cyphar** [comment]
Rejected. We discussed this in #1018. `recvtty` is more of a testing tool (and example tool) than something that users are actually meant to use.

**Comment by rajasec** [comment]
@cyphar 
Though it is used to create the console sockets, can we use other options to create the sockets instead of recvtty ?

**Comment by cyphar** [comment]
@rajasec Yes. The plan is to make the console socket API part of the spec, and that other people will implement more "enterprise" implementations -- `recvtty` is just used for our own integration tests (and also for messing around inside a shell).

**Comment by rajasec** [comment]
@cyphar 
Thanks for clarification, I'm closing the PR now.

**Pull request closed without merging**
