### PR TITLE
make localintegration fails on Ubuntu 17.04

### PR DESCRIPTION
**Pull request by leitwolf7**
Fix 2 string comparision issues in output validation.

Output before:

```
not ok 24 runc exec ls -la with --cwd
# (in test file tests/integration/exec.bats, line 88)
#   `[[ ${output} == "/bin" ]]' failed
```

```
not ok 26 runc exec --user
# (in test file tests/integration/exec.bats, line 113)
#   `[[ ${output} == "uid=1000 gid=1000" ]]' failed
```

Signed-off-by: leitwolf7 <leitwolf@wolke7.net>

### CODE REVIEW

**Comment by hqhq** [comment]
What output did you get exactly? Can you paste the full error logs?

**Comment by leitwolf7** [comment]
This is the full log when running without the patch:
```root@box:~/go/src/github.com/opencontainers/runc# make localintegration
go build -i  -ldflags "-X main.gitCommit="5b995d9570a4bcbd5c0135be5312046ccacdd23c" -X main.version=1.0.0-rc3 " -tags "seccomp" -o contrib/cmd/recvtty/recvtty ./contrib/cmd/recvtty
bats -t tests/integration
1..62
ok 1 runc update --kernel-memory (initialized)
ok 2 runc update --kernel-memory (uninitialized)
ok 3 # skip (test requires criu) checkpoint and restore
ok 4 # skip (test requires criu) checkpoint --pre-dump and restore
ok 5 runc create
ok 6 runc create exec
ok 7 runc create --pid-file
ok 8 runc create --pid-file with new CWD
ok 9 global --debug
ok 10 global --debug to --log
ok 11 global --debug to --log --log-format 'text'
ok 12 global --debug to --log --log-format 'json'
ok 13 runc delete
ok 14 runc delete --force
ok 15 runc delete --force ignore not exist
ok 16 events --stats
ok 17 events --interval default 
ok 18 events --interval 1s 
ok 19 events --interval 100ms 
ok 20 runc exec
ok 21 runc exec --pid-file
ok 22 runc exec --pid-file with new CWD
ok 23 runc exec ls -la
not ok 24 runc exec ls -la with --cwd
# (in test file tests/integration/exec.bats, line 88)
#   `[[ ${output} == "/bin" ]]' failed
# runc list (status=0):
# ID          PID         STATUS      BUNDLE      CREATED     OWNER
# runc spec (status=0):
# 
# runc run -d --console-socket /tmp/console.sock test_busybox (status=0):
# 
# runc exec --cwd /bin test_busybox pwd (status=0):
# /bin
# runc list (status=0):
# ID             PID         STATUS      BUNDLE             CREATED                          OWNER
# test_busybox   0           stopped     /tmp/busyboxtest   2017-07-19T20:05:57.962461912Z   root
# runc kill test_busybox KILL (status=1):
# time="2017-07-19T16:05:58-04:00" level=error msg="container_linux.go:308: signaling init process caused \"os: process already finished\"\n" 
# container_linux.go:308: signaling init process caused "os: process already finished"
# runc delete test_busybox (status=0):
# 
ok 25 runc exec --env
not ok 26 runc exec --user
# (in test file tests/integration/exec.bats, line 113)
#   `[[ ${output} == "uid=1000 gid=1000" ]]' failed
# runc list (status=0):
# ID          PID         STATUS      BUNDLE      CREATED     OWNER
# runc spec (status=0):
# 
# runc run -d --console-socket /tmp/console.sock test_busybox (status=0):
# 
# runc exec --user 1000:1000 test_busybox id (status=0):
# uid=1000 gid=1000
# runc list (status=0):
# ID             PID         STATUS      BUNDLE             CREATED                         OWNER
# test_busybox   0           stopped     /tmp/busyboxtest   2017-07-19T20:05:59.20354116Z   root
# runc kill test_busybox KILL (status=1):
# time="2017-07-19T16:05:59-04:00" level=error msg="container_linux.go:308: signaling init process caused \"os: process already finished\"\n" 
# container_linux.go:308: signaling init process caused "os: process already finished"
# runc delete test_busybox (status=0):
# 
ok 27 runc -h
ok 28 runc command -h
ok 29 runc foo -h
ok 30 kill detached busybox
ok 31 list
ok 32 mask paths [file]
ok 33 mask paths [directory]
ok 34 runc pause and resume
ok 35 runc pause and resume with nonexist container
ok 36 ps
ok 37 ps -f json
ok 38 ps -e -x
ok 39 global --root
ok 40 spec generation cwd
ok 41 spec generation --bundle
ok 42 spec validator
ok 43 runc start
ok 44 runc run detached
ok 45 runc run detached ({u,g}id != 0)
ok 46 runc run detached --pid-file
ok 47 runc run detached --pid-file with new CWD
ok 48 runc run
ok 49 runc run ({u,g}id != 0)
ok 50 runc run with rootfs set to .
ok 51 runc run --pid-file
ok 52 state (kill + delete)
ok 53 state (pause + resume)
ok 54 runc run [tty ptsname]
ok 55 runc run [tty owner]
ok 56 runc run [tty owner] ({u,g}id != 0)
ok 57 runc exec [tty ptsname]
ok 58 runc exec [tty owner]
ok 59 runc exec [tty owner] ({u,g}id != 0)
ok 60 update
ok 61 # skip (Test requires cgroups_rt.) update rt period and runtime
ok 62 runc version
Makefile:97: recipe for target 'localintegration' failed
make: *** [localintegration] Error 1```

**Comment by leitwolf7** [comment]
What do you think, does the output show the problem?

**Comment by leitwolf7** [comment]
Latest changes merged, ready for integration again.

**Comment by crosbymichael** [comment]
LGTM

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
