### PR TITLE
Bump runc version to 0.0.7

### PR DESCRIPTION
**Pull request by LK4D4**

### CODE REVIEW

**Comment by mrunalp** [comment]
@LK4D4 Do we want to wait for a resoluton of #508 ?

**Comment by crosbymichael** [comment]
Don't we need to bump the specs dep also?

**Comment by mrunalp** [comment]
I have create #514 for spec bump.

**Comment by cyphar** [comment]
/me would like to wait until #511 is merged.

**Comment by jimmidyson** [comment]
One problem is that there's now a v0.0.7 tag with incorrect version in [main.go](https://github.com/opencontainers/runc/blob/v0.0.7/main.go#L13). If you're going to bump the version like this what are you going to do for this existing & the next tag?

**Comment by LK4D4** [comment]
@jimmidyson I'm going to do it for existing tag. Do you think I should remove tag for now?

**Comment by mrunalp** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Comment by jimmidyson** [comment]
@LK4D4 Yeah retag is probably best.

**Pull request merged**
