### PR TITLE
Fix .Fatalf() error message

### PR DESCRIPTION
**Pull request by JoeWrightss**
Fix a small typo "recevied" to "received" in [container_linux_test.go](https://github.com/opencontainers/runc/compare/master...JoeWrightss:patch-3?expand=1#diff-241fad5897efafe2687db97efcef0757)

### CODE REVIEW

**Comment by cyphar** [comment]
You need to add a `Signed-off-by:` line to your commit(s) which indicates that you attest the [Developer Certificate of Origin](https://developercertificate.org/) a statement about your contributions that you *must read* before signing (don't worry, it's quite short and easy-to-read). You can add it to your commits with `git commit --amend -s`, and then doing a `git push --force`.

**Comment by JoeWrightss** [comment]
Thank you for your reminding.

**Comment by cyphar** [comment]
Please squash and rebase (and modify the original commit using `git commit --amend -s`) -- the merge commit shouldn't be included either.

**Comment by thaJeztah** [comment]
oh! I missed there's no separate DCO-check in this repo; sorry 😊 perhaps adding https://github.com/apps/dco to this repo would make it stand out better?

**Comment by cyphar** [comment]
I've requested it be added, I don't have permissions to add it myself.

**Comment by thaJeztah** [comment]
@crosbymichael you an admin / have permissions for that?

**Comment by mikebrow** [comment]
rebase presuming you've setup an upstream pointing to this repo and origin is your local clone of your fork:
git checkout master
git fetch upstream master --tags
git merge upstream/master
git push origin master
git checkout yourBranch
git rebase master
follow instructions

make sure you signed your commit:
git commit -s --amend 

force push it up:
git push -f origin test-fix

squash the last 3 commits into 1:
git rebase -i HEAD~3
replace "pick" with "squash" for the last two commits.. save and force push it up..

**Pull request closed without merging**
