### PR TITLE
Always remount for bind mount

### PR DESCRIPTION
**Pull request by hqhq**
Signed-off-by: Qiang Huang <h.huangqiang@huawei.com>

### CODE REVIEW

**Comment by hqhq** [comment]
On my host, cgroup mounted as:
```
$ cat /proc/mounts | grep cgroup
none /sys/fs/cgroup tmpfs rw,rootcontext=system_u:object_r:sysfs_t:s0,seclabel,relatime,size=4k,mode=755 0 0
cgroup /sys/fs/cgroup/cpu cgroup rw,relatime,cpu 0 0
cgroup /sys/fs/cgroup/cpuacct cgroup rw,relatime,cpuacct 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,relatime,memory 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,relatime,devices 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,relatime,freezer 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,relatime,blkio 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,relatime,hugetlb 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset 0 0
```

make test would always fail,
```
--- FAIL: TestMountCgroupRW (0.41s)
        exec_test.go:889: Mode expected to contain 'rw,nosuid,nodev,noexec': cgroup on /sys/fs/cgroup/cpu type cgroup (rw,relatime,cpu)
```

This PR fixes this.

**Comment by mrunalp** [comment]
@hqhq Thanks! Taking a look.

**Comment by crosbymichael** [comment]
LGTM

**Comment by crosbymichael** [comment]
ping @LK4D4 @mrunalp

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
