### PR TITLE
Add validation for sysctl

### PR DESCRIPTION
**Pull request by mrunalp**
/proc/sys isn't completely namespaced and only some properties are allowed
per linux namespace.

The list has been compiled from namespaces(7)

Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by mrunalp** [comment]
@crosbymichael @LK4D4 ping
cc: @rhatdan

**Comment by crosbymichael** [comment]
is it even worth having this field when only a few are valid?

**Comment by mrunalp** [comment]
@crosbymichael We have a lot of customers asking for this. net itself gives a lot of options.

**Comment by crosbymichael** [comment]
oh, right, i see the prfixes now

**Comment by mrunalp** [comment]
Also, more options will be made configurable over time from what I gathered talking to kernel engineers.

**Comment by rhatdan** [comment]
@jeder PTAL

**Comment by rhatdan** [comment]
@jeremyeder PTAL 

Are all of these network sysctls actually Namespace aware?

**Comment by rhatdan** [comment]
Would we want to make this available to docker as a public interface so that it could catch these early in the parse commands?

**Comment by mrunalp** [comment]
@rhatdan Yes, we could do that and docker could validate early. Also, @jeder's input will be useful to make sure this list is sane. I am going to look at kernel source code to see if I missed any settings. There is no other way unfortunately.

**Comment by rhatdan** [comment]
I think jeder should be @jeremyeder.

**Comment by jeremyeder** [comment]
@mrunal No, we can't just pass in the whole "net" sysctl space.  Even though some might actually work, there's some strange side-effects; for example you can adjust net.ipv4.tcp_mem in a container but the stack actually respects what's set on the host's kernel.

**Comment by rhatdan** [comment]
vm.nr_hugepages

Does not blow up, however not sure it worked correctly. 
```
docker run --privileged -ti --sysctl vm.nr_hugepages=2000 fedora sh
cat /proc/sys/vm/nr_hugepages
285
```

```
docker run --privileged -ti --sysctl vm.nr_hugepages=5000 fedora sh
# cat /proc/sys/vm/nr_hugepages
310
```

**Comment by mrunalp** [comment]
@jeremyeder Thanks for your input. I will get input from the right folks to create a better list for net and things that may be missing here.

**Comment by jeder** [comment]
I'm not @jeremyeder, so if he is not responding, you may have an address
wrong.

-John Eder

On Tue, Sep 29, 2015 at 4:43 AM, Mrunal Patel <notifications@github.com>
wrote:

> @jeremyeder <https://github.com/jeremyeder> Thanks for your input. I will
> get input from the right folks to create a better list for net and things
> that may be missing here.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencontainers/runc/pull/303#issuecomment-143854310>.
>



-- 
J. Eder

+1 619.847.5579  |  +81 80.8903.2817  |  j@eder.ws

**Comment by crosbymichael** [comment]
Should we validate at all?  If you asked for something we just try to do it?

**Comment by rhatdan** [comment]
I don't think we should validate. We should leave his up to the user to validate whether it works or not, as we explain in the man pages and docs.  Perhaps it would be helpful to have a page where we list sysctls that we know work with a particular kernel version.

Going forward this check is going to be very kernel specific, so verification is often going to be wrong.

**Comment by mrunalp** [comment]
@crosbymichael @rhatdan Sounds good. If we find a better way we could add it in the future.

**Comment by mrunalp** [comment]
Re-opening to see if there is interest in merging this so sysctl could be enabled safely in docker

**Comment by mrunalp** [comment]
@crosbymichael @LK4D4 WDYT? There are quite a few use cases that are blocked by not enabling this feature in docker.

**Comment by vishh** [comment]
From a community sense, it makes sense to curate a list of safe procfs tunables as part of runc. Until we have a complete list, we could possibly allow a backdoor.

**Comment by crosbymichael** [comment]
Is there a way were we can move this out of the specs and into hooks/ create/ start lifecycle?

**Comment by mrunalp** [comment]
It would be possible but a very roundabout way. Any concerns with doing it like in this PR? We could go by the man page and support what is documented.

**Comment by rhatdan** [comment]
@crosbymichael Why do  you think it would be better in one of those?

**Comment by crosbymichael** [comment]
@mrunalp do you just want to do the validation at the higher level so that we don't have to recompile or update libcontainer/runc when something changes?

**Comment by rhatdan** [comment]
Not sure you want to do this, if we want to prevent users from shooting themselves in the foot, when doing runc/oci type apps.  If we want to protect them, we should protect them in all tools.

One thing we are doing in runc is also looking at whether they disabled the host or ipc namespace, which is pretty difficult to do in the docker cli.

**Comment by crosbymichael** [comment]
LGTM

**Comment by mrunalp** [comment]
If we do run into an issue where we have to frequently modify this list then we could add configuration for it. I think we can merge this and then see how it goes.

**Comment by hqhq** [comment]
So after this, container will never be as privileged as host, isn't this gonna break some users who use container to hack with host, like rancherOS? ping @ibuildthecloud

The validation looks reasonable to me, just think maybe we should make it optional.

**Comment by mrunalp** [comment]
We could make it optional in privileged mode as the file system is made read only in non privileged anyways.

**Comment by rhatdan** [comment]
Of course in --privileged mode you can just execute sysctl directly.

**Comment by mrunalp** [comment]
I think we don't need to modify this PR. One can go and set /proc/sys when in privileged mode and there is no harm in the validation when using the CLI so one distinguish  between what is safe in container vs being set on the host.

**Comment by rhatdan** [comment]
I agree.  We are only allowing what we know of as "Namespaced sysctls"

**Comment by hqhq** [comment]
@mrunalp Do you mean we can make the sysctl validation optional now without any furture modification? Can you explain how to do that?

**Comment by mrunalp** [comment]
I mean that this patch is sufficient. No special handling of privileged is necessary as /proc/sys is write able under privileged and allows the user to set sysctls that are not container specific.

**Comment by hqhq** [comment]
@mrunalp Thanks for clarification, I'm worry about people might want use sysctl with CLI in `--privileged` mode which is forbidden by the validation (these non-namespaced sysctls). Anyway we can do that in follow PRs if it do bother some users.

LGTM.

**Comment by rhatdan** [comment]
@hqhq I think the current assumption is that --privileged does not change other behaviour in the system.  We were discussing similar behaviour with UserNamespace and it was decided that --privileged does not effect userNamespace but a --userns=host is being added to turn off user namespace.  I think that precedent would follow here.  In that you can do priv ops in the container, but we will continue to block you doing something accidentally.

**Pull request merged**
