### PR TITLE
[ci test] resource limit set in cgroup v2

### PR DESCRIPTION
**Pull request by lifubang**
Relate to #4225

### CODE REVIEW

**Comment by lifubang** [comment]
```
not ok 243 update cpu period and memory
# (from function `check_cgroup_value' in file tests/integration/helpers.bash, line [270](https://github.com/opencontainers/runc/actions/runs/8314599169/job/22751989577?pr=4226#step:10:271),
#  from function `check_cpu_quota' in file tests/integration/helpers.bash, line 297,
#  in test file tests/integration/update.bats, line 376)
#   `check_cpu_quota 504000 900000 "560ms"' failed
# runc spec (status=0):
#
# runc run -d --console-socket /tmp/bats-run-7NfWT9/runc.Oi6Vb2/tty/sock test_update (status=0):
#
# current max 100000 !? max 100000
# runc update test_update --cpu-period 900000 --cpu-quota 504000 (status=0):
#
# current 504000 900000 !? 504000 900000
# runc update test_update --cpu-period 900000 (status=0):
#
# current 504000 900000 !? 504000 900000
# runc update test_update --memory 500M (status=0):
#
# current 504000 900000 !? 504000 900000
# runc update test_update --cpu-period 900000 (status=0):
#
# current max 900000 !? 504000 900000
```

**Comment by lifubang** [comment]
cgroup v2 (systemd)
```
not ok 242 update cpu period and memory with no quota
# (from function `check_cgroup_value' in file tests/integration/helpers.bash, line 270,
#  from function `check_cpu_quota' in file tests/integration/helpers.bash, line 300,
#  in test file tests/integration/update.bats, line 350)
#   `check_cpu_quota -1  900000 "infinity"' failed
# runc spec (status=0):
#
# runc run -d --console-socket /tmp/bats-run-N7qHrP/runc.QIXe63/tty/sock test_update (status=0):
#
# current -1 !? -1
# current 100000 !? 100000
# systemd CPUQuotaPerSecUSec: current infinity !? infinity
# runc update test_update --cpu-period 900000 (status=0):
#
# current -1 !? -1
# current 900000 !? 900000
# systemd CPUQuotaPerSecUSec: current infinity !? infinity
# runc update test_update --memory 500M (status=0):
#
# current -1 !? -1
# current 100000 !? 900000
not ok 243 update cpu period and memory
# (from function `check_cgroup_value' in file tests/integration/helpers.bash, line 270,
#  from function `check_cpu_quota' in file tests/integration/helpers.bash, line 299,
#  in test file tests/integration/update.bats, line 372)
#   `check_cpu_quota 504000 900000 "560ms"' failed
# runc spec (status=0):
#
# runc run -d --console-socket /tmp/bats-run-N7qHrP/runc.dbIUt4/tty/sock test_update (status=0):
#
# current -1 !? -1
# current 100000 !? 100000
# systemd CPUQuotaPerSecUSec: current infinity !? infinity
# runc update test_update --cpu-period 900000 --cpu-quota 504000 (status=0):
#
# current 504000 !? 504000
# current 900000 !? 900000
# systemd CPUQuotaPerSecUSec: current 560ms !? 560ms
# runc update test_update --cpu-period 900000 (status=0):
#
# current 504000 !? 504000
# current 900000 !? 900000
# systemd CPUQuotaPerSecUSec: current 560ms !? 560ms
# runc update test_update --memory 500M (status=0):
#
# current 56000 !? 504000
```

**Comment by lifubang** [comment]
cgroup v1(fs driver):
```
not ok 242 update cpu period and memory with no quota
# (from function `check_cgroup_value' in file tests/integration/helpers.bash, line 270,
#  from function `check_cpu_quota' in file tests/integration/helpers.bash, line 300,
#  in test file tests/integration/update.bats, line 350)
#   `check_cpu_quota -1  900000 "infinity"' failed
# runc spec (status=0):
#
# runc run -d --console-socket /tmp/bats-run-6yJDud/runc.UstIVI/tty/sock test_update (status=0):
#
# current -1 !? -1
# current 100000 !? 100000
# systemd CPUQuotaPerSecUSec: current infinity !? infinity
# systemd CPUQuotaPeriodUSec: current infinity !? 100ms infinity
# runc update test_update --cpu-period 900000 (status=0):
#
# current -1 !? -1
# current 900000 !? 900000
# systemd CPUQuotaPerSecUSec: current infinity !? infinity
# systemd CPUQuotaPeriodUSec: current 900ms !? 900ms
# runc update test_update --memory 500M (status=0):
#
# current -1 !? -1
# current 100000 !? 900000
not ok 243 update cpu period and memory
# (from function `check_cgroup_value' in file tests/integration/helpers.bash, line 270,
#  from function `check_cpu_quota' in file tests/integration/helpers.bash, line [299](https://github.com/opencontainers/runc/actions/runs/8314599169/job/22751987306?pr=4226#step:11:300),
#  in test file tests/integration/update.bats, line 376)
#   `check_cpu_quota 504000 900000 "560ms"' failed
# runc spec (status=0):
#
# runc run -d --console-socket /tmp/bats-run-6yJDud/runc.nP5Fwn/tty/sock test_update (status=0):
#
# current -1 !? -1
# current 100000 !? 100000
# systemd CPUQuotaPerSecUSec: current infinity !? infinity
# systemd CPUQuotaPeriodUSec: current infinity !? 100ms infinity
# runc update test_update --cpu-period 900000 --cpu-quota 504000 (status=0):
#
# current 504000 !? 504000
# current 900000 !? 900000
# systemd CPUQuotaPerSecUSec: current 560ms !? 560ms
# systemd CPUQuotaPeriodUSec: current 900ms !? 900ms
# runc update test_update --cpu-period 900000 (status=0):
#
# current 504000 !? 504000
# current 900000 !? 900000
# systemd CPUQuotaPerSecUSec: current 560ms !? 560ms
# systemd CPUQuotaPeriodUSec: current 900ms !? 900ms
# runc update test_update --memory 500M (status=0):
#
# current 504000 !? 504000
# current 900000 !? 900000
# systemd CPUQuotaPerSecUSec: current 560ms !? 560ms
# systemd CPUQuotaPeriodUSec: current 900ms !? 900ms
# runc update test_update --cpu-period 900000 (status=0):
#
# current -1 !? 504000
```

**Comment by kolyshkin** [comment]
@lifubang do you still need this?

**Comment by kolyshkin** [comment]
@lifubang feel free to reopen if you still need this.

**Pull request closed without merging**
