### PR TITLE
update to github.com/sirupsen/logrus v1.0.0

### PR DESCRIPTION
**Pull request by mcandre**
Signed-off-by: Andrew Pennebaker <apennebaker@datapipe.com>

Fix some dependencies by updating to latest logrus, now hosted at github.com/sirupsen/logrus.

### CODE REVIEW

**Comment by mcandre** [comment]
Odd, the unit tests are passing in CI, but the Makefile appears to fail the local task anyway.

**Comment by cyphar** [comment]
They're not passing. [Here's the highlighted failure](https://travis-ci.org/opencontainers/runc/jobs/250959798#L3372).

**Comment by dqminh** [comment]
yah, this is because logrus switch the default log output to stderr, while the execintest code only set the buffer to stdout. Change https://github.com/opencontainers/runc/blob/master/libcontainer/integration/execin_test.go#L237 to Stderr should make the test pass.

**Comment by crosbymichael** [comment]
@mcandre you can revert your last commit to fix the shell changes.  If you rebase on master the validation will pass.  Sorry for the trouble.

**Comment by dqminh** [comment]
@mcandre i can carry this change if you need help for it. Just need a few small fixes i think.

**Comment by dqminh** [comment]
Closed in favor of #1526

**Pull request closed without merging**
