### PR TITLE
libcontainer: Add a helper func to set CriuPath

### PR DESCRIPTION
**Pull request by macrosheep**
Added a helper func to set CriuPath for LinuxFactory.

Signed-off-by: Yang Hongyang <imhy.yang@gmail.com>

### CODE REVIEW

**Comment by hqhq** [comment]
Sorry but I don't see the benefit, why would we do this?

**Comment by macrosheep** [comment]
@hqhq thanks for your attention. I think CriuPath is like InitArgs and other members of linuxContainer struct, we'd better provide an option func within libcontainer package for users to set CriuPath like what we've done for InitArgs, cgroupManagers etc. Instead of let every libcontainer consumers to implement their own option func to directly access and set linuxContainer.CriuPath.

**Comment by hqhq** [comment]
Sorry for the late. OK, although I think the option function for setting criuPath is simple enough, I don't mind adding this either.

LGTM

**Comment by cyphar** [comment]
LGTM

**Pull request merged**
