### PR TITLE
cleancode: clean code for utils_linux.go

### PR DESCRIPTION
**Pull request by zvier**
Signed-off-by: Jeff Zvier <zvier20@gmail.com>

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
Please sign with full name

**Comment by zvier** [comment]
> Please sign with full name

OK, I already did it. Thank you for you review again

**Comment by kolyshkin** [comment]
> OK, I already did it

I think @AkihiroSuda meant this (from the commit message):

> Signed-off-by: zvier <zvier20@gmail.com>

**Comment by zvier** [comment]
> > OK, I already did it
> 
> I think @AkihiroSuda meant this (from the commit message):
> 
> > Signed-off-by: zvier [zvier20@gmail.com](mailto:zvier20@gmail.com)

Uh-huh, 

> > OK, I already did it
> 
> I think @AkihiroSuda meant this (from the commit message):
> 
> > Signed-off-by: zvier [zvier20@gmail.com](mailto:zvier20@gmail.com)

Oh, yes, I get it. Thanks for reminding me.

**Pull request merged**
