### PR TITLE
Disallow self-LGTMs

### PR DESCRIPTION
**Pull request by hqhq**
As https://github.com/opencontainers/project-template/pull/13
is merged, change pullapprove accordingly.

Signed-off-by: Qiang Huang <h.huangqiang@huawei.com>

### CODE REVIEW

**Comment by cyphar** [comment]
LGTM

**Comment by cyphar** [comment]
Can you also include the `MAINTAINERS_GUIDE.md` changes from that PR as well?

**Comment by hqhq** [comment]
@cyphar I think the plan should not be that we sync these docs to every projects of OCI when they changed, if we want to maintain these docs in one place, we might need some action like we did in runtime-spec for [code-of-conduct.md](https://github.com/opencontainers/runtime-spec/blob/master/Makefile#L56), that's something we need to figure out.

**Comment by cyphar** [comment]
If we're going to do that, we should link the files IMO. But in that case LGTM.

**Comment by dqminh** [comment]
LGTM

**Pull request merged**
