### PR TITLE
Revert to non-recursive GetPids, add recursive GetAllPids

### LINKED ISSUE #457: Add non-recursive GetPids?
We are migrating from `docker/libcontainer` to here & one issue for us is the implementation of `GetPids` is now recursive. In Kubernetes we use this project's cgroups functionality to get pids from a particular cgroup & move (`Apply`) them to another one, but we don't want to do this recursively.

How would you feel in adding a non-recursive `GetPids`? Pretty trivial implementation wise, but not sure how you'd feel about that?

### PR DESCRIPTION
**Pull request by jimmidyson**
Fixes #457 

/cc @LK4D4 @vishh

### CODE REVIEW

**Comment by jimmidyson** [comment]
Would appreciate fairly quick review if possible @LK4D4 @vishh so I can get this pulled in to Kubernetes if accepted.

**Comment by vishh** [comment]
LGTM. Thanks @jimmidyson!

**Comment by mrunalp** [comment]
I've restarted the build.

**Comment by mrunalp** [comment]
@jfrazelle There is some issue with the builds. Could you please take a look? Thanks!

**Comment by mrunalp** [comment]
nvm, this just turned green :)

**Comment by LK4D4** [comment]
LGTM

**Comment by jimmidyson** [comment]
Thanks! Any chance of a tag?

**Comment by LK4D4** [comment]
@jimmidyson I want to merge pids cgroup before tagging.

**Comment by jimmidyson** [comment]
@LK4D4 Is there a PR for that that I can track?

**Comment by jimmidyson** [comment]
#446?

**Comment by cyphar** [comment]
@jimmidyson Yes.

**Pull request merged**
