### PR TITLE
Update spec

### PR DESCRIPTION
**Pull request by mrunalp**
@LK4D4 @crosbymichael ping

Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by vbatts** [comment]
closes #170

**Comment by vbatts** [comment]
LGTM

**Comment by LK4D4** [comment]
@mrunalp can we make it in one commit to not break `git bisect`?

**Comment by mrunalp** [comment]
@LK4D4 done.

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
