### PR TITLE
s390x: fix big endian issue

### PR DESCRIPTION
**Pull request by alicefr**
_Note: this is a carry of https://github.com/opencontainers/runc/pull/2350_

This PR fixes a big endian issue and modify the tests accordingly.

The solution is based on the same fix as containers/crun@07bae05

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
Needs https://github.com/cilium/ebpf/pull/91 as well?

**Comment by alicefr** [comment]
yes, otherwise the ebpf library still generates the wrong position for src and dst registers on s390x. I'll check with @iii-i, what is blocking or the TODOs for that PR

**Comment by AkihiroSuda** [comment]
https://github.com/cilium/ebpf/pull/91 seems merged.

**Comment by AkihiroSuda** [comment]
Was this closed by mistake?

**Comment by alicefr** [comment]
oh my god. I have something wrong with my git setup. When I force push, it wrongly updates this PR. Not sure why?!

**Comment by alicefr** [comment]
@AkihiroSuda sorry, I had some wrong setup in my github.

**Comment by AkihiroSuda** [comment]
LGTM

**Comment by alicefr** [comment]
Merged PR #2389

**Comment by AkihiroSuda** [comment]
LGTM

**Comment by cyphar** [comment]
LGTM.

**Pull request merged**
