### PR TITLE
Remove the workaround which add a -- flag to runc ps command

### PR DESCRIPTION
**Pull request by keloyang**
https://github.com/opencontainers/runc/pull/1051 has been merged to fix ps/exec parameter error, so we can remove the redundant workaround for runc ps.

Signed-off-by: Shukui Yang <yangshukui@huawei.com>

### CODE REVIEW

**Comment by hqhq** [comment]
Can exec work around be removed as well?

**Comment by keloyang** [comment]
@hqhq I'm sorry I missed exec, it has been added, thank you.

**Comment by hqhq** [comment]
@keloyang I noticed we didn't add any test cases for this multi arguments case when add ps and exec work around, can you add some test cases to cover these?

**Comment by keloyang** [comment]
@hqhq I have add the integrations for ps/exec command to test the removal of workaround. https://github.com/opencontainers/runc/pull/784 has integrations for ps command already, so I only add the case for workaround removal.

**Comment by crosbymichael** [comment]
LGTM

**Comment by keloyang** [comment]
ping @hqhq

**Comment by hqhq** [comment]
LGTM

**Pull request merged**
