### PR TITLE
libct/cg/fs: fix setting rt_period vs rt_runtime

### PR DESCRIPTION
**Pull request by kolyshkin**
The problem/fix is similar to one in #3084/#3090.

A test case (by @ls-ggg) is copied from #4235.

Fixes: #4094.
Closes: #4235.

### CODE REVIEW

**Comment by lifubang** [comment]
@ls-ggg PTAL

**Comment by ls-ggg** [comment]
@lifubang LGTM

**Comment by kolyshkin** [comment]
@AkihiroSuda PTAL 🙏🏻

**Comment by kolyshkin** [comment]
This needs to be backported to 1.1 and I want this to be included into 1.1.13, but before doing a backport this needs to be merged; so PTAL @opencontainers/runc-maintainers

**Review by AkihiroSuda — APPROVED** [review]

**Pull request merged**
