### PR TITLE
Don't make modifications to /dev when it is bind mounted

### LINKED ISSUE #80: Sharing /dev/ with the container breaks /dev/ptmx on the host
When a container is launched with a bind mount between /dev (on the host) and /dev (in the container), all subsequent attempts to open /dev/ptmx fail.

`setupPtmx()` in `libcontainer/rootfs_linux.go` will unconditionally remove `/dev/ptmx` and then symlink it to `/dev/pts/ptmx` , which is a character file that is untouchable by unprivileged users. This prevents unprivileged programs which rely on `getpt` from running on the host (such as X terminals, screen, and tmux).

I discovered this via docker, but it happens in any libcontainer app if /dev/ is shared with the container before `setupPtmx`. Is there a reason for libcontainer to touch /dev (at all) if it's mounted directly from the host? I have tested this on Fedora 22 and 21, SELinux is set to permissive, as well as Arch Linux without SELinux.

I can reproduce this consistently.

`uname -a`: `Linux wtemple.localdomain 4.0.6-300.fc22.x86_64 #1 SMP Tue Jun 23 13:58:53 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

`config.json`:
```
{
    "version": "0.1.1",
    "platform": {
        "os": "linux",
        "arch": "amd64"
    },
    "process": {
        "terminal": true,
        "user": "root",
        "args": [
            "/bin/sh"
        ],
        "env": [
            "PATH=/bin,/sbin"
        ],
        "cwd": ""
    },
    "root": {
        "path": "rootfs",
        "readonly": true
    },
    "hostname": "shell",
    "mounts": [
        {
            "type": "proc",
            "source": "proc",
            "destination": "/proc",
            "options": ""
        },
        {
            "type": "sysfs",
            "source": "sysfs",
            "destination": "/sys",
            "options": "nosuid,noexec,nodev"
        },
        {
            "type": "bind",
            "source": "/dev",
            "destination": "/dev",
            "options": "bind"
        }
    ],
    "linux": {
        "namespaces": [
            {
                "type": "process"
            },
            {
                "type": "network"
            },
            {
                "type": "mount"
            },
            {
                "type": "ipc"
            },
            {
                "type": "uts"
            }
        ],
        "capabilities": [
            "AUDIT_WRITE",
            "KILL",
            "NET_BIND_SERVICE"
        ],
        "devices": [
            "null"
        ]
    }
}
```

### PR DESCRIPTION
**Pull request by mrunalp**
Fixes #80 

Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by mrunalp** [comment]
@willmtemple See if this fixes your issue trying to bind mount /dev

**Comment by rhatdan** [comment]
I have seen this happen, but was not sure why.  nice work @willmtemple on finding it.

**Comment by rhatdan** [comment]
@mrunalp would the destination be /dev/ or /dev?

**Comment by LK4D4** [comment]
@rhatdan @mrunalp maybe should be both?

**Comment by rhatdan** [comment]
@LK4D4 Yes I think so.

**Comment by willmtemple** [comment]
@mrunalp Yes this fixes #80. @rhatdan @LK4D4 libcontainer will automatically add the trailing '/' for directory mounts. No need to check '/dev'. I just tested this with the bind mount into '/dev' and it worked fine.

IMHO, however, I think this isn't the best solution. I'm not a fan of the fact that it silently disregards devices listed from the devices array in `config.json`. I think it should error out. Also, is there any reason I couldn't mount some other tmpfs on my system e.g. `/foo/container_dev/:/dev/` in the container? Maybe in that case I want libcontainer to do all the normal setup even though /dev/ is bind-mounted in. At the least, I think that we should check to make sure that both the mount source and mount target are /dev/.

**Comment by rhatdan** [comment]
Yes I think we should check on ```source=/dev dest=/dev```.  Users could attempt to do other wierd stuff with ```-v /foo/container_dev/:/dev/```

We should just check if the user specified a device to be created with --device and -v /dev:/dev and throw an error.  A real corner case, but it could happen.

**Comment by mrunalp** [comment]
I did consider the case of the source not being /dev and argued that runc couldn't assume anything when /dev is being provided to it hence checked for just the destination. I am not against adding a check for the source as well if we all agree it makes sense.

**Comment by willmtemple** [comment]
@mrunalp I think you're probably right. If the user wants to mount something into /dev, it should be the users responsibility to set it up.

**Comment by mrunalp** [comment]
@LK4D4 @crosbymichael PTAL.

**Comment by CameronNemo** [comment]
Maybe a better solution is to bind mount `/dev/ptmx` to `/dev/pts/ptmx` so it only applies to the container, whether `/dev` is bind mounted or not. Then you can bind mount `/dev` and mount `/dev/pts` with the newinstance option and it would work well.

**Comment by LK4D4** [comment]
@CameronNemo sounds good for `ptmx`, but overall messing with bind-mounted `/dev/` should be prohibited.

**Comment by mrunalp** [comment]
@CameronNemo https://www.kernel.org/doc/Documentation/filesystems/devpts.txt recommends using the symlink instead of a bind mount.

**Comment by mrunalp** [comment]
@LK4D4 @rjnagal ping

**Comment by LK4D4** [comment]
LGTM

**Comment by mrunalp** [comment]
@crosbymichael ping

**Comment by crosbymichael** [comment]
Would a more robust way to handle this is to have a flag to say if we should setup dev or not instead of looking at paths in the mounts array?

**Comment by mrunalp** [comment]
@crosbymichael That will be cleaner but not sure if such a flag would be allowed to be exposed in docker CLI.

**Comment by crosbymichael** [comment]
well docker can determine if it should set the flag or not and not do the complex things here

**Comment by mrunalp** [comment]
Sounds good to me. I will update the patch.

**Comment by crosbymichael** [comment]
i would say don't setup dev if the devices array len() == 0

**Comment by mrunalp** [comment]
@crosbymichael That works for me. We can avoid introducing a new config. I have updated the patch. Let me know if that's what you had in mind.

**Comment by crosbymichael** [comment]
seems simple to me, 

LGTM

**Pull request merged**
