### PR TITLE
Ignore changing /dev/null permissions if used in STDIO

### PR DESCRIPTION
**Pull request by crosbymichael**
Whenever dev/null is used as one of the main processes STDIO, do not try
to change the permissions on it via fchown because we should not do it
in the first place and also this will fail if the container is supposed
to be readonly.

Signed-off-by: Michael Crosby <crosbymichael@gmail.com>

### CODE REVIEW

**Comment by gitido** [comment]
Was just about to push a patch to address the same issue (https://github.com/gitido/runc/commit/cbd3fe7c2488c8f17f0b11de69bc80a8c374bedf), but took a different approach.

Just wondering if changing permissions of any device file is desirable, not just /dev/null.
In any case, for /dev/null, I guess both fixes should work.

**Comment by crosbymichael** [comment]
@gitido what about when things are `/dev/pts/1`?  

```bash
stat /dev/pts/1
  File: ‘/dev/pts/1’
  Size: 0               Blocks: 0          IO Block: 1024   character special file
Device: dh/13d  Inode: 4           Links: 1     Device type: 88,1
Access: (0620/crw--w----)  Uid: ( 1000/ michael)   Gid: (    5/     tty)
Access: 2015-09-22 12:32:39.794966534 -0700
Modify: 2015-09-22 12:32:39.794966534 -0700
Change: 2015-09-22 10:25:04.794966534 -0700
```

**Comment by gitido** [comment]
@crosbymichael that's a good question.

Not sure we'd want to change ownership there either however - it could have some implications on the process owning that pts, couldn't it?

**Comment by crosbymichael** [comment]
@gitido i think we would in the case of pts devices because they need to match the perms of the process that will own them.

**Comment by gitido** [comment]
@crosbymichael just wondering if there aren't any security implications of doing something like this.

I realize that not chowning the pts might break the process in the container, but doing so might have some implications on the host. Question is if libcontainer should be the one taking that decision.

**Comment by crosbymichael** [comment]
@gitido it's ok because we make the pty and libcontainer owns it.

**Comment by gitido** [comment]
@crosbymichael that's true for runc, but not necessarily for other users of libcontainer, no?

**Comment by crosbymichael** [comment]
ping @LK4D4 @mrunalp

**Comment by LK4D4** [comment]
LGTM
too sad that criu was deleted from debian

**Comment by crosbymichael** [comment]
@LK4D4 ahh, i guess we can build from source in the dockerfile then to fix this?

**Comment by LK4D4** [comment]
@crosbymichael Yup, #287

**Comment by runcom** [comment]
@LK4D4 @crosbymichael I'm finishing a PR to build from source just now

**Comment by mrunalp** [comment]
LGTM

**Comment by mrunalp** [comment]
Are we waiting for the build to come back before merging?

**Comment by crosbymichael** [comment]
i rebased on master so you can run the tests locally

**Comment by mrunalp** [comment]
okay

**Comment by mrunalp** [comment]
Test passed locally. Merging.

**Pull request merged**
