### PR TITLE
add timeout set freeze to fix exec with update make set freeze step o…

### PR DESCRIPTION
**Pull request by gaopeiliang**
sometimes we found runc init  and container process step on Disk Sleep status when use runc-rc92 version

we found runc exec run with runc update concurrence，will make cgroup freezing incomplete,  we should retry set freezer status or cancel set  not block forever as kernel freezer-subsystem.txt said

even though kernel freezing status will not step on more time , but we found it forever on Ubuntu 16.04, kernel 4.19 

when unix execv(2) replace self and write cgroup freezen make cgroup step on freezing forever ,, maybe kernel something ,, but we should around it , not stop the world .....

### CODE REVIEW

**Comment by kolyshkin** [comment]
Thank you for your contribution @gaopeiliang. Can you please describe the issue you're trying to fix in more details?

**Comment by kolyshkin** [comment]
> Can you please describe the issue you're trying to fix in more details?

Ideally, a code / test case that demonstrates it.

**Comment by thaJeztah** [comment]
related to / addresses https://github.com/opencontainers/runc/issues/2753

**Comment by kolyshkin** [comment]
> we should retry set freezer status or cancel set not block forever as kernel freezer-subsystem.txt said

Here's the relevant portion:

<blockquote>
It's important to note that freezing can be incomplete. In that case we return
EBUSY. This means that some tasks in the cgroup are busy doing something that
prevents us from completely freezing the cgroup at this time. After EBUSY,
the cgroup will remain partially frozen -- reflected by freezer.state reporting
"FREEZING" when read. The state will remain "FREEZING" until one of these
things happens:

	1) Userspace cancels the freezing operation by writing "THAWED" to
		the freezer.state file
	2) Userspace retries the freezing operation by writing "FROZEN" to
		the freezer.state file (writing "FREEZING" is not legal
		and returns EINVAL)
	3) The tasks that blocked the cgroup from entering the "FROZEN"
		state disappear from the cgroup's set of tasks.
</blockquote>

**Comment by kolyshkin** [comment]
@gaopeiliang I'm still working on that stuff, no need to replace your implementation with mine. Once ready I'll open an PR.

**Comment by gaopeiliang** [comment]
> @gaopeiliang I'm still working on that stuff, no need to replace your implementation with mine. Once ready I'll open an PR.

OK ,,  maybe it will come soon ,,,   we have about 2k node in risk status ......

**Comment by gaopeiliang** [comment]
https://github.com/opencontainers/runc/pull/2774

**Pull request closed without merging**
