### PR TITLE
add type casting for uint64 parameter

### PR DESCRIPTION
**Pull request by sangyun-han**
Add type casting for major.unix method. Its input parameter is uint64, but the parameter in unix.Stat_t is int32.

### CODE REVIEW

**Comment by cyphar** [comment]
You need to add a `Signed-off-by:` line to your commit(s) which indicates that you attest the [Developer Certificate of Origin](https://developercertificate.org/) a statement about your contributions that you *must read* before signing (don't worry, it's quite short and easy-to-read). You can add it to your commits with `git commit --amend -s`, and then doing a `git push --force`.

**Comment by sangyun-han** [comment]
I added `Signed-off-by`. 
Thank you for the comment.

**Comment by dqminh** [comment]
LGTM.

I believe this is only uint32 for MIPS though.

**Comment by cyphar** [comment]
Closing since #1824 was merged (which is basically the same thing). Thanks.

**Pull request closed without merging**
