### PR TITLE
[1.1] Fix CI

### PR DESCRIPTION
**Pull request by rata**
When I opened PR #3721 the CI fails due to downloading the busybox image. This PR should fix that.

I'm backporting #3700 #3701 and #3526 for this. The fist two are fixes for this (and is simpler to backport both than to bakport one and fix the conflicts). The last one (#3526) I've backported it too, so I can apply the first two without conflicts. It only changes tests, so it seems safe to backport.

I think backporting all of these makes it simpler also to backport any more change needed in the future (as these files are in sync between 1.1 branch and main), and as they only change the tests it seems fine IMHO. Let me know if you prefer more chirurgical changes and to deal with conflicts when backporting.

### CODE REVIEW

**Review by thaJeztah — DISMISSED** [review]
LGTM

(assuming the CI failure is related; looks like a hiccup, so needs to be triggered again later)

**Comment by rata** [comment]
I'm not sure if the vagrant failure is valid (but not caused by this). Seems weird it doesn't happen on main, though. Will repush

**Comment by rata** [comment]
@kolyshkin @thaJeztah Do you want to carry forward this PR and fix vagrant (vagrant failure seems legit, the other fails seems like azure downtime or some more fixes needed :-/)

**Comment by kolyshkin** [comment]
Re: vagrant, it seems that the F35 image was removed, we need to switch to a newer version. This means backporting #3442 and maybe #3670.

**Comment by kolyshkin** [comment]
I have added the commits from here to https://github.com/opencontainers/runc/pull/3729, so closing this one. Thanks @rata!

**Pull request closed without merging**
