### PR TITLE
Set oom_score_adj before we send the config to avoid race

### PR DESCRIPTION
**Pull request by mrunalp**
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by mrunalp** [comment]
@mikebrow Can you check if this fixes #662 for you? Thanks!

**Comment by mrunalp** [comment]
Fix for the broken test is in #669

**Comment by mikebrow** [comment]
Yes, running with that change, the error is no longer reproducible with runc exec test_busybox echo Hello.

**Comment by mrunalp** [comment]
@mikebrow Thanks! Basically with this change we are relying on the synchronization for passing down config. We also set the cgroups before passing the config for the same reason. This escaped under the radar during review.

**Comment by mikebrow** [comment]
Ok!  I'll write up some stress test cases to try and catch bootstrap issues for start and exec.  Cheers

**Comment by hqhq** [comment]
Test failed.

**Comment by cyphar** [comment]
@hqhq Test failure is fixed in #669. It's not related to this PR.

**Comment by hqhq** [comment]
All right, I see https://github.com/opencontainers/runc/pull/669 fixed this.

**Comment by hqhq** [comment]
LGTM

**Comment by cyphar** [comment]
LGTM

**Pull request merged**
