### PR TITLE
Vagrantfile.fedora: bump Fedora to 39

### PR DESCRIPTION
**Pull request by kolyshkin**

### CODE REVIEW

**Comment by kolyshkin** [comment]
Guess what, @AkihiroSuda, it works fine now without any additional fixes. I think they've rolled back some of the incompatible changes.

Feel free to either merge this one or revise #4121.

**Comment by kolyshkin** [comment]
btw Fedora 40 also works (tested locally).

**Review by AkihiroSuda — APPROVED** [review]
👀

**Review by lifubang — APPROVED** [review]

**Comment by AkihiroSuda** [comment]
> btw Fedora 40 also works (tested locally).

Do you plan to open this PR too?

**Pull request merged**
