### PR TITLE
go.mod, libct: switch to google.golang.org/protobuf

### PR DESCRIPTION
**Pull request by kolyshkin**
Switch from github.com/golang/protobuf (which appears to be obsoleted)
to google.golang.org/protobuf (which appears to be a replacement).

This needs a bump of checkpoint-restore/go-criu to include
https://github.com/checkpoint-restore/go-criu/pull/43.

Addresses: #2627 (https://github.com/opencontainers/runc/issues/2627#issuecomment-777092686)

~~*NOTE: this is a draft since it uses an untagged version of go-criu. Once a tagged release is available, I'll update this PR and move it out of draft*~~

### CODE REVIEW

**Comment by kolyshkin** [comment]
The binary size has actually decreased a bit:

For go 1.15:
```console
[kir@kir-rhat runc]$ size runc.*15
   text	   data	    bss	    dec	    hex	filename
7790881	3968272	 221488	11980641	 b6cf61	runc.goog.go115
7806321	3972945	 221584	12000850	 b71e52	runc.master.go115
```
For go 1.16:
```console
[kir@kir-rhat runc]$ size runc.*16
   text	   data	    bss	    dec	    hex	filename
7176335	3658240	 222488	11057063	 a8b7a7	runc.goog.go116
7199983	3664080	 222616	11086679	 a92b57	runc.master.go116
```

**Comment by kolyshkin** [comment]
No longer a draft. @adrianreber @AkihiroSuda @mrunalp PTAL

**Comment by kolyshkin** [comment]
cross-i386 failed with:

```
panic: getImages error exit status 1 (output: curl: (22) The requested URL returned error: 502 
Failed to get https://github.com/docker-library/busybox/raw/dist-i386/stable/glibc/busybox.tar.xz
)

goroutine 1 [running]:
github.com/opencontainers/runc/libcontainer/integration.init.1()
	/home/runner/work/runc/runc/libcontainer/integration/utils_test.go:39 +0x378
FAIL	github.com/opencontainers/runc/libcontainer/integration	9.407s
```

This is a temp github issue :( which I'm seeing for the first time, and I think we can use curl's retry to mitigate. Opened https://github.com/opencontainers/runc/pull/2833

**Review by adrianreber — APPROVED** [review]
Looks good to me

**Review by AkihiroSuda — APPROVED** [review]

**Comment by kolyshkin** [comment]
Ughm... I have almost reimplemented the first commit of this PR from scratch when I was looking into the checkpointing code today -- thought I never finished it.

**Review by mrunalp — APPROVED** [review]

**Comment by kolyshkin** [comment]
close/open to re-kick ci

**Pull request merged**
