### PR TITLE
VERSION: release v1.0.0-rc5

### PR DESCRIPTION
**Pull request by cyphar**
This is planned to be the final -rc release of runc. While we really
haven't followed the rules for release candidates (with huge features
introduced each release, and with massive gaps between releases) the
hope is that once we've release 1.0.0 we will be much more liberal with
releases in future. Let's see how that pans out. :P

[ omitted changelog for brevity. ]

Signed-off-by: Aleksa Sarai <asarai@suse.de>

### CODE REVIEW

**Comment by crosbymichael** [comment]
LGTM

**Comment by mrunalp** [comment]
LGTM

**Comment by cyphar** [comment]
Needs new LGTMs after the rebase.

**Comment by dqminh** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
