### PR TITLE
Use Eventfd() from golang.org/x/sys/unix

### PR DESCRIPTION
**Pull request by tklauser**
Update golang.org/x/sys/unix to get Eventfd() and the corresponding EFD_* flags introduced in golang/sys@0b25a408) and switch libcontainer to use Eventfd() instead of manually reimplementing it.  Also use the correct corresponding unix.EFD_CLOEXEC flag instead of unix.FD_CLOEXEC (which can have a different value on some architectures and thus might lead to unexpected behavior).

### CODE REVIEW

**Comment by crosbymichael** [comment]
LGTM

**Comment by crosbymichael** [comment]
@tklauser Thanks for working on these.  It really helps.

**Comment by mrunalp** [comment]
LGTM

**Comment by cyphar** [comment]
I second @crosbymichael -- thanks a lot for these @tklauser!

**Pull request merged**
