### PR TITLE
Removing pause state from container errors

### PR DESCRIPTION
**Pull request by rajasec**
Removing pausing state from error conditions, as container pause(freeze) state of the container

Signed-off-by: Rajasekaran <rajasec79@gmail.com>

### CODE REVIEW

**Comment by crosbymichael** [comment]
why?

**Comment by rajasec** [comment]
@crosbymichael 
While I was doing checkpoint for paused container, it use to freeze for sometime. Once the container is resumed, it will start dumping. I thought it will applicable to start of another process too.
Also I have seen this error variable is not consumed in the code.

**Comment by crosbymichael** [comment]
@rajasec it is an error condition if you are trying to exec another process in a paused container.  

i.e.
1. Start container
2. Pause it
3 . Start another process in container
4 . Should get the error.

**Comment by crosbymichael** [comment]
@rajasec in #311 we are actually using the paused error code correctly now so I don't think we need to remove it.  Its was just a bug that it was not being consumed.

**Pull request closed without merging**
