### PR TITLE
libcontainer/cgroups: do not enable kmem on broken kernels     

### PR DESCRIPTION
**Pull request by kolyshkin**
Commit fe898e7862f94 (PR #1350) enables kernel memory accounting for all cgroups created by libcontainer even if kmem limit is not configured.
    
Kernel memory accounting is known to be broken in RHEL7 kernels,
including the latest RHEL 7.5 kernel. It does not support reclaim
and can lead to kernel oopses while removing cgroup (merging it
with its parent). Unconditionally enabling kmem acct on RHEL7
leads to bugs:
   
* https://github.com/opencontainers/runc/issues/1725
* https://github.com/kubernetes/kubernetes/issues/61937
* https://github.com/moby/moby/issues/29638
    
I am not aware of any good way to figure out whether the kernel
memory accounting in the given kernel is working or broken.
For the lack of a better way, let's check if the running kernel
is RHEL7, and disable initial setting of kmem.

Alternative to https://github.com/opencontainers/runc/issues/1898

### CODE REVIEW

**Comment by thaJeztah** [comment]
Wondering if it should be a compile time option, so that packagers for a specific distro can enable/disable it

**Comment by crosbymichael** [comment]
cc @mrunalp

**Comment by kolyshkin** [comment]
Apparently the kernel bug(s) we work around here are **not** fixed in latest-n-greatest RHEL7.6 kernels (see latest comments in https://bugzilla.redhat.com/show_bug.cgi?id=1507149).

**Comment by kolyshkin** [comment]
> Alternative to #1898

cc @ryarnyah

**Comment by mrunalp** [comment]
I prefer #1921 and have LGTM'ed it. Thanks!

**Comment by cyphar** [comment]
NACK. I prefer #1921 as well.

**Comment by kolyshkin** [comment]
Closed in favor of #1921

**Pull request closed without merging**
