### PR TITLE
Convert to use opencontainers/selinux

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
This pull request should replace https://github.com/opencontainers/runc/pull/1365

**Comment by dqminh** [comment]
@rhatdan can you vendor github.com/opencontainers/selinux/go-selinux ?

**Comment by rhatdan** [comment]
@dqminh Hopefully I did it right.

**Comment by hqhq** [comment]
Ha, didn't see you opened a new PR earlier, I already updated #1365 , we can close this one, thanks for working on this.

**Pull request closed without merging**
