### PR TITLE
Update spec to v0.3.0

### LINKED ISSUE #528: config: Single, unified config file
Per the changes to the spec... we need to move to a single config file see: 
https://github.com/opencontainers/specs/pull/284

### PR DESCRIPTION
**Pull request by crosbymichael**
Closes #528
Closes #534

This takes @mikebrow 's commit from #534 and implements the device whitelist and all that stuff that changed in the spec and adds the default list as well.

### CODE REVIEW

**Comment by crosbymichael** [comment]
ping @jfrazelle wanna check this one out?

**Comment by crosbymichael** [comment]
We still need to update the README and some docs for this change.  I'll continue working on that

**Comment by mrunalp** [comment]
Looks fine from a quick test and review; will wait for the update to README.

**Comment by mikebrow** [comment]
@crosbymichael Heads up... I had to rebase my #534 commit to fix conflicts from #525

**Comment by crosbymichael** [comment]
@mrunalp update readme.  should be good to go

**Comment by mrunalp** [comment]
LGTM

**Comment by LK4D4** [comment]
Great
LGTM

**Comment by cyphar** [comment]
The `Set` code causes issues when you vendor it into Docker (this is on Arch Linux):

```
docker: Error response from daemon: Cannot start container 6894f735eac4f742a2f1389dff3f347ed0f0349c037e874ef5f23d5bea1b7812: [10] System error: write /sys/fs/cgroup/devices/devices.deny: invalid argument.
```

**Comment by jfrazelle** [comment]
ah man i gotta change all my things now

**Pull request merged**
