### PR TITLE
Remove duplicated included head file

### PR DESCRIPTION
**Pull request by hqhq**
Signed-off-by: Qiang Huang <h.huangqiang@huawei.com>

### CODE REVIEW

**Comment by hqhq** [comment]
They are all included twice, ping @dqminh @mlaventure is this intentional? Maybe some head file hack like #609 that I don't realize yet?

**Comment by mlaventure** [comment]
No, no reasons that I can think of. They should be able to be removed correctly.

**Comment by mrunalp** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
