### PR TITLE
libct/cg/sd: use systemd v240+ new MAJOR:* syntax

### PR DESCRIPTION
**Pull request by kolyshkin**
Since systemd v240 ([systemd commit 8e8b5d2e6d91180a](https://github.com/systemd/systemd/commit/8e8b5d2e6d91180a)), one can use
`/dev/{char,block}-MAJOR` syntax to specify that all `MAJOR:*`
devices of the type are allowed.
    
Use it, if available, since it's more straightforward, plus
we can skip somewhat expensive parsing of /proc/devices
~~(which also reminds me we need to merge #3357).~~

### CODE REVIEW

**Comment by kolyshkin** [comment]
@opencontainers/runc-maintainers PTAL

**Review by AkihiroSuda — APPROVED** [review]

**Comment by kolyshkin** [comment]
@opencontainers/runc-maintainers PTAL

**Comment by kolyshkin** [comment]
rebased

**Comment by kolyshkin** [comment]
@lifubang PTAL

**Review by lifubang — APPROVED** [review]

**Pull request merged**
