### PR TITLE
Get runc to build clean on Solaris

### PR DESCRIPTION
**Pull request by amitkris**
This is a build clean PR for runc on Solaris.
This is a part of a larger effort for a native port of Docker on Solaris.

Signed-off-by: Amit Krishnan <krish.amit@gmail.com>

### CODE REVIEW

**Comment by cyphar** [comment]
Nice. :D

**Comment by crosbymichael** [comment]
LGTM

**Comment by cyphar** [comment]
LGTM. Merging.

**Comment by amitkris** [comment]
@cyphar @crosbymichael: thanks! :)

**Pull request merged**
