### PR TITLE
Adapt spec 96bcd043aa8a28f6f64c95ad61329765f01de1ba

### LINKED ISSUE #274: multiple devices for blkio cgroup resource not working
By declaring in `runtime.json` a `linux.resources` like the following:
```json
"resources": {
	[omitted]
	"blockIO": {
		"blkioWeight": 0,
		"blkioWeightDevice": "8:0 500\n8:16 500",
		"blkioThrottleReadBpsDevice": "",
		"blkioThrottleWriteBpsDevice": "",
		"blkioThrottleReadIopsDevice": "",
		"blkioThrottleWriteIopsDevice": ""
	},
	[omitted]
},
```
`blkio.weight_device` (and `blkioThrottle*`) isn't populated with both the devices but only the first one is correctly added.
Current code is directly writing `8:0 500\n8:16 500` to the cgroup file which isn't clearly working. To fix this, multiple `ioutil.WriteFile()` should be done for each device declared.
The same applies to the others fields defined above as a string.

proposed spec changes https://github.com/opencontainers/specs/pull/193
this PR https://github.com/docker/docker/pull/13959 and two other are wrongly assuming the above format will work

Once/If the proposed changes to the spec lands I'll gladly take care of this here if it's ok

### PR DESCRIPTION
**Pull request by runcom**
Fixes #274

### CODE REVIEW

**Comment by tiborvass** [comment]
Ping @LK4D4 @crosbymichael

**Comment by crosbymichael** [comment]
LGTM

**Comment by runcom** [comment]
I've rebased this, though it seems the specs version I'm importing here is quite old now. I'll vendor the latest commit and adapt code if it's ok for you @crosbymichael @LK4D4 @mrunalp

**Comment by thaJeztah** [comment]
Looks like this is blocking two PR's in docker (https://github.com/docker/docker/pull/13959#issuecomment-141655935), any chance of moving this forward? :heart:

**Comment by crosbymichael** [comment]
ping @LK4D4 @vishh @mrunalp could u guys checkout these changes.  It's pretty straight forward.

**Comment by mrunalp** [comment]
Reviewing...

**Comment by mrunalp** [comment]
LGTM

**Comment by runcom** [comment]
I'll update docker now

**Comment by thaJeztah** [comment]
Thanks all!

**Pull request merged**
