### PR TITLE
script: test_Dockerfile: install criu from source

### PR DESCRIPTION
**Pull request by runcom**
Fix https://github.com/opencontainers/runc/issues/287

ping @LK4D4 @crosbymichael @mrunalp 

Signed-off-by: Antonio Murdaca <runcom@linux.com>

### CODE REVIEW

**Comment by runcom** [comment]
janky's down, but this builds fine locally and tests pass

**Comment by crosbymichael** [comment]
LGTM

**Comment by mrunalp** [comment]
Looking

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
