### PR TITLE
fix "libcontainer/cgroups/fs/cpuset.go:63:14: undefined: fmt"

### PR DESCRIPTION
**Pull request by AkihiroSuda**
The compilation error had ocurred because of a bad rebase during #2401 and #2413

Replaces #2415

### CODE REVIEW

**Comment by dims** [comment]
LGTM

**Comment by mrunalp** [comment]
LGTM

**Comment by mrunalp** [comment]
@kolyshkin ptal.

**Comment by kolyshkin** [comment]
LGTM

**Pull request merged**
