### PR TITLE
Bump spec and version to rc2

### PR DESCRIPTION
**Pull request by crosbymichael**
Lets just go ahead and release the rc2 with the updates in master.  The console and other things can come in rc3 or later.  We don't have to hold things up because we want more PRs. 

Signed-off-by: Michael Crosby <crosbymichael@gmail.com>

### CODE REVIEW

**Comment by mrunalp** [comment]
LGTM

**Comment by dqminh** [comment]
LGTM

**Comment by hqhq** [comment]
LGTM

**Comment by cyphar** [comment]
(late) LGTM

**Comment by cyphar** [comment]
I've written release notes and signed a tag for this version.

**Pull request merged**
