### PR TITLE
Fixed two typos

### PR DESCRIPTION
**Pull request by jhjeong-kr**
Signed-off-by: Jin-Hwan Jeong <jhjeong.kr@gmail.com>

### CODE REVIEW

**Comment by thaJeztah** [comment]
thanks! LGTM, but possibly the maintainers will ask you to squash your commits (not sure what the policy is in this repo)

**Comment by mrunalp** [comment]
Agree with @thaJeztah on squashing.

**Comment by jhjeong-kr** [comment]
It seems that I squashed them.

**Comment by dqminh** [comment]
LGTM

**Comment by jhjeong-kr** [comment]
I did it as you said

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
