### PR TITLE
ebpf: fix big endian issue for s390x

### PR DESCRIPTION
**Pull request by alicefr**
Same fix as https://github.com/containers/crun/commit/07bae05e613df2086966a3f1d763729a8677f6a9

This also needs cilium/ebpf#91

Signed-off-by: Alice Frosi <afrosi@de.ibm.com>

### CODE REVIEW

**Comment by kolyshkin** [comment]
@alicefr can you please amend the commit message with what is being done? Somethhing like escription from https://github.com/containers/crun/commit/07bae05e613df2086966a3f1d763729a8677f6a9 is good enough.

**Comment by AkihiroSuda** [comment]
Please update UT

**Comment by AkihiroSuda** [comment]
ping @alicefr

**Comment by alicefr** [comment]
@AkihiroSuda @kolyshkin  sorry for the delay. I update the comment

**Comment by alicefr** [comment]
Please be aware that you need also this PR before fixing the ebpf issue https://github.com/cilium/ebpf/pull/91

**Comment by alicefr** [comment]
This PR is not working on x86. Need to figure out what's wrong

**Comment by alicefr** [comment]
I changed the assembly so also the test cases need to be modified accordingly

**Comment by alicefr** [comment]
I accidentally closed this PR and I cannot reopen it. Even if I add new commits.

**Comment by AkihiroSuda** [comment]
I can't reopen either, please open a new one?

**Comment by alicefr** [comment]
@AkihiroSuda sorry for the mess here the new PR https://github.com/opencontainers/runc/pull/2381

**Pull request closed without merging**
