### PR TITLE
libcontainer: configs: create cgroup_unsupported.go in order to build on darwin as well

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by hqhq** [comment]
LGTM

**Comment by runcom** [comment]
Ping @mrunalp @LK4D4

**Comment by mrunalp** [comment]
We probably shouldn't have either windows/freebsd here at all but in a separate higher level resources. However, that could be fixed later. LGTM.

**Comment by runcom** [comment]
Yes, what you said it's a comment in the windows file to split the Config struct but yes can be done later

**Pull request merged**
