### PR TITLE
Remove sample configs from libcontainer

### PR DESCRIPTION
**Pull request by hqhq**
Sample configs are only for runc now, sample_configs fold in
libcontainer is not needed anymore, and we should add more
configs for runc.

Signed-off-by: Qiang Huang <h.huangqiang@huawei.com>

### CODE REVIEW

**Comment by crosbymichael** [comment]
I would probably just delete all the sample configs for now because the spec is still changing and it would be too hard to change all these configs every time.

**Comment by crosbymichael** [comment]
sorry, didn't mean to close, I hit the wrong button.

**Comment by hqhq** [comment]
@crosbymichael Sure, updated, just delete all the sample configs for now.

**Comment by estesp** [comment]
Somewhat of a minor nit, but for future reference of this PR, it might be nice to change PR title to commit message "title" as this is now only a removal, but the PR sounds like it is still adding something.

**Comment by hqhq** [comment]
@estesp You are right, forgot to change title, thanks for the remind.

**Comment by mrunalp** [comment]
LGTM

**Comment by crosbymichael** [comment]
@hqhq thanks!

**Pull request merged**
