### PR TITLE
MAINTAINERS: add Akihiro Suda to maintainers

### PR DESCRIPTION
**Pull request by thaJeztah**
I'm nominating Akihiro to be added as a maintainer for runc. Akihiro has been a
frequent contributor to this project, bringing expertise in important areas, such
as cgroups v2 and rootless containers.

Akihiro has experience with collaborating on, and maintaining various mainstream
open source projects in the container ecosystem, and as such would be a great
addition to the list of maintainers to help this project moving forward.

With this pull request, I invite the maintainers to vote on this PR, as described
in the [maintainers guide](https://github.com/opencontainers/runc/blob/602c85fdc6c73d614213fc1759f8e710e54047ca/MAINTAINERS_GUIDE.md#how-are-maintainers-added);

> The final vote to add a new maintainer should be approved by over 66% of the
> current maintainers with the chief maintainer having veto power. In case of a
> veto, conflict resolution rules expressed above apply. The voting period is
> five business days on the Pull Request to add the new maintainer.

@crosbymichael @mrunalp @dqminh @hqhq @cyphar PTAL

(For reference; I had a conversation with @AkihiroSuda before opening this PR (thanks!)).

### CODE REVIEW

**Comment by hqhq** [comment]
LGTM

**Comment by cyphar** [comment]
LGTM. (For PullApprove)

**Comment by thaJeztah** [comment]
^ wondering: is pull approve still needed now that GitHub allows configuring "X reviews are required" on protected branches (and I think even allows for requiring those reviews to not be outdated)?

**Comment by cyphar** [comment]
Maybe, though I think GitHub permits self-LGTMs (which aren't permitted for OCI projects -- at least at the moment).

**Comment by mrunalp** [comment]
LGTM

**Comment by cyphar** [comment]
> With this pull request, I invite the maintainers to vote on this PR, as described
> in the [maintainers guide](https://github.com/opencontainers/runc/blob/602c85fdc6c73d614213fc1759f8e710e54047ca/MAINTAINERS_GUIDE.md#how-are-maintainers-added);
> 
> > The final vote to add a new maintainer should be approved by over 66% of the
> > current maintainers with the chief maintainer having veto power. In case of a
> > veto, conflict resolution rules expressed above apply. The voting period is
> > five business days on the Pull Request to add the new maintainer.

As a complete aside, we really need to rework this section (and most of the maintainers guide). Most of the stuff in there hasn't been accurate for at least 5 years now -- there hasn't been a "chief maintainer" for god knows how long. And from memory we've never actually managed to complete a vote for adding a maintainer in five business days.

**Comment by thaJeztah** [comment]
ping @dqminh @crosbymichael PTAL 🙏

**Comment by crosbymichael** [comment]
LGTM

**Comment by caniszczyk** [comment]
thanks, invited you @AkihiroSuda to the team!

**Comment by AkihiroSuda** [comment]
Thank you!

**Comment by AkihiroSuda** [comment]
Could you also add me to `pullaprove`?

**Comment by caniszczyk** [comment]
@AkihiroSuda you should bet set when you joined @opencontainers/runc-maintainers 

I checked https://pullapprove.com/opencontainers/runc/settings/ and you appear there now ;)

**Comment by AkihiroSuda** [comment]
Thanks, but I'm not listed in https://pullapprove.com/opencontainers/runc/pull-request/2230/reviews/ yet. Maybe not synced for existing PRs.

**Comment by caniszczyk** [comment]
@AkihiroSuda try again, just force a resync

**Comment by AkihiroSuda** [comment]
Thanks, it works now

**Pull request merged**
