### PR TITLE
Updating bash completion for ps command

### PR DESCRIPTION
**Pull request by rajasec**
Updating bash completion for ps command.

Signed-off-by: rajasec <rajasec79@gmail.com>

### CODE REVIEW

**Comment by cyphar** [comment]
Can we add the bash completion for the host machine's `ps` command? Or is that just not going to work because it'd be managed by a separate package? :P

**Comment by rajasec** [comment]
it will work for the runc ps command. since we are putting in .bashrc I hope it will work with specific executable. I dont think it will work with host ps.

**Comment by cyphar** [comment]
No, I mean that it would be nice if `runc ps <tab>` would allow you to tab-complete the command-line options for `ps`. But it's probably not nicely doable in a distro-independent way.

**Comment by rajasec** [comment]
This PR will do runc ps <tab> allow to complete the container names, not the options of ps.

**Comment by cyphar** [comment]
I understand that, I was saying that it **would** be nice **if we could** complete `ps` options. And I'm wondering whether you know of a way we could do it without redefining all of the ps options ourselves (namely -- can we source the bash-completion for ps). My guess is that we probably can't but I thought I'd ask because you might know more than me about it.

LGTM. Doesn't matter.

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
