### PR TITLE
nsexec: don't use CLONE_PARENT and CLONE_NEWPID together

### PR DESCRIPTION
**Pull request by adfernandes**
This is a copy of
https://github.com/avagin/runc/commit/d31e97fa28345375b3f76bff64d12cdb07e03ba0
to address https://github.com/opencontainers/runc/issues/613

Signed-off-by: Andrew Fernandes <andrew@fernandes.org>

### CODE REVIEW

**Comment by avagin** [comment]
Could you save me as an author for this commit?
git commit --author 'Andrey Vagin <avagin@virtuozzo.com>' --amend

Thanks!

**Comment by mrunalp** [comment]
Also, it will be good to give the reasoning behind this in the commit message for posterity as researched by @avagin

**Comment by mrunalp** [comment]
@crosbymichael I think we should

**Comment by mrunalp** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
