### PR TITLE
Add Installation Guide with Ansible

### LINKED ISSUE #2302: Ansible Role for runc
I am now maintenance an Ansible Role for runc installation (https://github.com/alvistack/ansible-role-runc), by downloading the static binary release archive and extract it for following OS:
- Ubuntu 16.04/18.04/19.10
- CentOS/RHEL 7/8
- openSUSE 15.1

Could we also introduce this as an alternative installation method, e.g. after https://github.com/opencontainers/runc#building section?

### PR DESCRIPTION
**Pull request by hswong3i**
Provide additional installation options by using Ansible with https://github.com/alvistack/ansible-role-runc from source code.

Fixes #2302

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
I'm not sure we want this. runc has been already available as a standard package in almost all distros.

**Comment by kolyshkin** [comment]
Alas I know nothing about Ansible :(

**Comment by hswong3i** [comment]
> I'm not sure we want this. runc has been already available as a standard package in almost all distros.

In my use case I combine both runc + conmon + cri-o with Ansible Role in source code compile mode installation, in order to secure all 3 component could be installed with latest stable release from official, with support to both Ubuntu 18.04/19.10/20.04 or RHEL/CentOS 7/8 or openSUSE 15.1. Usually repo packages are outdated or not equally available on time.

Moreover, this Ansible Role could also demo how dependency dev packages should be installed (e.g. https://github.com/alvistack/ansible-role-runc/blob/master/vars/centos-8.yml and https://github.com/alvistack/ansible-role-runc/blob/master/vars/ubuntu-20.04.yml) and how the build/install step should be preform (e.g. https://github.com/alvistack/ansible-role-runc/blob/master/tasks/main.yml#L77-L98).

**Comment by AkihiroSuda** [comment]
Should be proposed to CRI-O repo then?

**Comment by hswong3i** [comment]
> Should be proposed to CRI-O repo then?

@AkihiroSuda the [PR](https://github.com/cri-o/cri-o/commit/a6dd748101b65fadb3f067ee14cb4bb3a029fe81) that for CRI-O already accepted ;-)

**Comment by hswong3i** [comment]
I give up on runc (https://github.com/alvistack/ansible-role-runc) and migrate all of my deployment to crun (https://github.com/alvistack/ansible-role-crun)

**Pull request closed without merging**
