### PR TITLE
Only allow single container operation

### PR DESCRIPTION
**Pull request by hqhq**
As per the discussions in #1156 , we think it's a bad
idea to allow multi container operations in runc. So
revert it.

Signed-off-by: Qiang Huang <h.huangqiang@huawei.com>

### CODE REVIEW

**Comment by crosbymichael** [comment]
@hqhq thanks for doing this PR so quickly

**Comment by mrunalp** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Comment by cyphar** [comment]
:+1:

**Pull request merged**
