### PR TITLE
Trivial changes

### PR DESCRIPTION
**Pull request by masahir0y**

### CODE REVIEW

**Review by AkihiroSuda — CHANGES_REQUESTED** [review]
> [.gitignore: ignore emacs backup and temporary files](https://github.com/opencontainers/runc/pull/3440/commits/adf6de925b489bf436212a12a2485c4c104a0a6e)

This should be in gitignore in your home directory

**Comment by masahir0y** [comment]
I do not know the policy for this project, but
I know some projects that ignore editor backup files,
for example, Linux kernel.
https://github.com/torvalds/linux/blob/v5.17/.gitignore#L133

Does the same apply to tag jump files?
I use gogtags (https://github.com/juntaki/gogtags)

**Comment by AkihiroSuda** [comment]
> I do not know the policy for this project, but I know some projects that ignore editor backup files, for example, Linux kernel. https://github.com/torvalds/linux/blob/v5.17/.gitignore#L133

Yes, but we do not have editor-specific config in our repo.

> Does the same apply to tag jump files? I use gogtags (https://github.com/juntaki/gogtags)

Yes.

**Review by kolyshkin — APPROVED** [review]
LGTM

**Pull request merged**
