### PR TITLE
Enables system properties.

### PR DESCRIPTION
**Pull request by mrunalp**
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by cgwalters** [comment]
I can't see your runc fork - can you make it public now that runc is public?

**Comment by cgwalters** [comment]
It looks like this needs a rebase on master too.

**Comment by mrunalp** [comment]
Yes, I will rebase this.

**Comment by mrunalp** [comment]
Closing in favor of #46

**Pull request closed without merging**
