### PR TITLE
readme: Mention the go 1.6 requirement in the README for building runc

### LINKED ISSUE #884: Cannot start container using instructions from README on latest build
I attempted to follow the instructions in the README to create a container from a docker image based on `busybox` using the latest commit ab10b6068b3f7ec99370eb66bf48592998cc9db1.

```
# mkdir rootfs
# docker export $(docker create busybox) | tar -C rootfs xvf -
# runc spec
# runc run test
```

Expected result: /bin/sh prompt
Actual result: idle, no output, dies on SIGINT

Using the repository version of `runc` on Fedora, I can `runc start test` as previous, with the compiled version from this repo, I get

`open /run/runc/test/state.json: no such file or directory`

While the `runc run test` is idle, I have
```
# runc ps test
UID        PID  PPID  C STIME TTY          TIME CMD
root     18960 18952  0 13:26 pts/5    00:00:00 /home/wtemple/.go/src/github.com/opencontainers/runc/runc init
```

Built with Fedora 23, BUILDTAGS="seccomp selinux", also tried with just BUILDTAGS="seccomp"

### PR DESCRIPTION
**Pull request by mrunalp**
Closes #884 

Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by mrunalp** [comment]
Waiting on #900 for build.

**Comment by cyphar** [comment]
Triggered rebuild since #900 is merged.

**Comment by cyphar** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
