### PR TITLE
logo added and readme updated

### PR DESCRIPTION
**Pull request by reallinfo**

### CODE REVIEW

**Comment by crosbymichael** [comment]
You need to sign your commits with the DOC.  you will have to squash and amend to sign them right.  See the contrib doc here for more info:

https://github.com/opencontainers/runc/blob/master/CONTRIBUTING.md#sign-your-work

**Comment by AkihiroSuda** [comment]
What's current status?

**Comment by cyphar** [comment]
You need to add a `Signed-off-by:` line to your commit(s) which indicates that you attest the [Developer Certificate of Origin](https://developercertificate.org/) a statement about your contributions that you *must read* before signing (don't worry, it's quite short and easy-to-read). You can add it to your commits with `git commit --amend -s`, and then doing a `git push --force`.

**Comment by AkihiroSuda** [comment]
ping @reallinfo

**Comment by AkihiroSuda** [comment]
Closing because of inactivity

**Pull request closed without merging**
