### PR TITLE
tests/int: nits and cleanups

### PR DESCRIPTION
**Pull request by kolyshkin**
~~_Based on and currently includes #3367 ~~and #3371~~. Draft until those are merged._~~

This is a set of bash code cleanups for integration tests, mostly done for correctness, uniformity, and readability.

Please review commit by commit, and see individual commit messages for details.

### CODE REVIEW

**Comment by kolyshkin** [comment]
As per comments, https://github.com/opencontainers/runc/pull/3367#discussion_r804121372, it makes sense to change CGROUP_UNIFIED to CGROUP_V1 and CGROUP_V2.

**Comment by kolyshkin** [comment]
Waiting for #3367 to be merged.

**Comment by kolyshkin** [comment]
@tianon PTAL 🙏🏻

**Review by tianon — APPROVED** [review]

**Comment by kolyshkin** [comment]
@thaJeztah @mrunalp PTAL (this is already blessed by @tianon).

**Comment by kolyshkin** [comment]
@thaJeztah @mrunalp @AkihiroSuda @cyphar  PTAL (this is already blessed by @tianon).

**Comment by kolyshkin** [comment]
@thaJeztah @mrunalp @AkihiroSuda @cyphar Very PTAL. Background story: I am working to add some tests and just caught myself redoing these cleanups from scratch. Believe me, it does not feel good at all.

**Review by mrunalp — APPROVED** [review]

**Review by thaJeztah — APPROVED** [review]
LGTM

sorry, for some reason missed the pings 🙀

**Pull request merged**
