### PR TITLE
update man page for `runc  update`

### PR DESCRIPTION
**Pull request by sak0**
update man pages for `runc update`
supplement to [pr1423](https://github.com/opencontainers/runc/pull/1423)

Signed-off-by: CuiHaozhi <cuihz@wise2c.com>

### CODE REVIEW

**Comment by cyphar** [comment]
Please squash your commits. Thanks!

**Comment by sak0** [comment]
@cyphar  Thanks  squashed :)

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by cyphar** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
