### PR TITLE
MAINTAINERS: add Kir Kolyshkin

### PR DESCRIPTION
**Pull request by AkihiroSuda**
@kolyshkin  has been the most active contributor recently:
https://github.com/opencontainers/runc/pulls?q=is%3Apr+author%3Akolyshkin+

Let's invite him to the maintainers officially.

- - -
https://github.com/opencontainers/runc/blob/bf0a8e17471347407fe9e856d4f3ff61beaf2fea/MAINTAINERS_GUIDE.md

> The final vote to add a new maintainer should be approved by over 66% of the current maintainers with the chief maintainer having veto power. In case of a veto, conflict resolution rules expressed above apply. The voting period is five business days on the Pull Request to add the new maintainer.

In addition to LGTM from @kolyshkin , this PR needs 4 LGTMs from the current 6 maintainers

- [x] @kolyshkin 
- [x] @crosbymichael 
- [x] @mrunalp 
- [ ] @dqminh 
- [x] @hqhq 
- [x] @cyphar 
- [X] @AkihiroSuda

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
Self LGTM (explicitly)

**Comment by hqhq** [comment]
LGTM

**Comment by mrunalp** [comment]
LGTM

**Comment by cyphar** [comment]
LGTM.

**Comment by cyphar** [comment]
We've hit 4 LGTMs, but I'd suggest waiting for @crosbymichael and @dqminh if they wish to raise any objections.

**Comment by crosbymichael** [comment]
LGMT

**Comment by kolyshkin** [comment]
hey @caniszczyk while we're at it, can you please remove Rohit and Victor from the [runc-maintainers](https://github.com/orgs/opencontainers/teams/runc-maintainers) team?
 - @rjnagal: commit  2efedb02aa611b109
- @vmarmol: commit  a020000185c1d2f5

**Comment by cyphar** [comment]
I think it's safe to say that @dqminh doesn't have an objections. I'll merge this now -- welcome to the team @kolyshkin!

**Comment by caniszczyk** [comment]
@kolyshkin removed @rjnagal and @vmarmol

**Pull request closed without merging**
