### PR TITLE
cleanup old hack dir

### PR DESCRIPTION
**Pull request by jfrazelle**
looks like this was left around from the libcontainer days ;)

Signed-off-by: Jessica Frazelle <acidburn@docker.com>

### CODE REVIEW

**Comment by crosbymichael** [comment]
LGTM

**Comment by hqhq** [comment]
Should we move this to runc instead of deleting it? It seems still useful.

**Comment by LK4D4** [comment]
@hqhq DCO is checked by a bot, for vet and fmt we have targets in Makefile.
LGTM

**Comment by hqhq** [comment]
@LK4D4 Got it, thanks :)

**Pull request merged**
