### PR TITLE
libcontainer: rm windows pieces

### PR DESCRIPTION
**Pull request by kolyshkin**
_(this used to be part of https://github.com/opencontainers/runc/pull/2695)_

This removes some Windows-only code from libcontainer. See individual commits for details.

### CODE REVIEW

**Review by mrunalp — APPROVED** [review]

**Comment by kolyshkin** [comment]
For context, this is `DO NOT MERGE` since @thaJeztah is currently looking into who's using this from Windows code. Once the Windows users are removed, this can be merged.

**Comment by kolyshkin** [comment]
rebased (for new CI)

**Comment by AkihiroSuda** [comment]
Is this still DNM?

**Comment by thaJeztah** [comment]
Ah, keep forgetting; I should try vendoring from this branch to see if (and where) things break

**Comment by AkihiroSuda** [comment]
> Once the Windows users are removed, this can be merged.

Can we merge this right now?
We don't guarantee Go compatibility of libcontainer. If something no longer compiles on Windows, the maintainers of that project just copy the deleted codes to their project.

**Comment by kolyshkin** [comment]
I'm fine with merging this, but we need to hear back from @thaJeztah as we don't want to break Docker

**Comment by thaJeztah** [comment]
Ah, sorry, forgot about this one; I think we should be fine, but opened https://github.com/docker/cli/pull/3011 and https://github.com/moby/moby/pull/42143, which vendor from this branch to see if things break

**Comment by thaJeztah** [comment]
@kolyshkin I opened https://github.com/kolyshkin/runc/pull/9 against your branch with some fixes that were needed to make it work (https://github.com/moby/moby/pull/42143). Also opened https://github.com/opencontainers/runc/pull/2851 with other changes related to that

**Comment by thaJeztah** [comment]
> @kolyshkin I opened [kolyshkin#9](https://github.com/kolyshkin/runc/pull/9) against your branch with some fixes that were needed to make it work ([moby/moby#42143](https://github.com/moby/moby/pull/42143)). Also opened #2851 with other changes related to that

@kolyshkin could you have a look at https://github.com/kolyshkin/runc/pull/9 ? ^^

**Comment by thaJeztah** [comment]
I rebased this one and included my patch from https://github.com/kolyshkin/runc/pull/9 in https://github.com/opencontainers/runc/pull/2888

**Comment by cyphar** [comment]
Looks like there's still a merge conflict?

**Comment by cyphar** [comment]
I'll close this in favour of #2888.

**Pull request closed without merging**
