### PR TITLE
ps: --format value check

### PR DESCRIPTION
**Pull request by sak0**
command ps: value of the option --format should be one of table or json.(default: table)

Signed-off-by: CuiHaozhi <cuihaozhi@chinacloud.com.cn>

### CODE REVIEW

**Comment by sak0** [comment]
shfmt can not testing on Go 1.6
https://github.com/mvdan/sh/commit/cbb3fa663a1cdbb007b3037c87df7d3591a1b1a3

**Comment by cyphar** [comment]
Please squash your commits and rebase on master (we dropped Go 1.6.x a few minutes ago).

**Comment by sak0** [comment]
thanks, may i close this PR and make new one?

**Comment by hqhq** [comment]
@sak0 You should always do a force push instead of closing and creating a new on.

**Comment by sak0** [comment]
@hqhq Thank you :)

**Comment by crosbymichael** [comment]
LGTM

**Comment by hqhq** [comment]
LGTM

**Pull request merged**
