### PR TITLE
join the cgroup after the initial setup finished

### PR DESCRIPTION
**Pull request by lifubang**
We should join the cgroup after the initial setup finished,
but before runc init clone new children processes. (#4427)

Because we should try our best to reduce the influence of
memory cgroup accounting from all runc init processes
before we start the container init process.

If we cherry pick this commit to release-1.1, it will eliminate
the impacts of memory accounting from `ensure_clone_binary`.

### CODE REVIEW

**Comment by kolyshkin** [comment]
This made me look into why initWaiter is added, and here's what I found:
 - added by commit 4ecff8d9 (see its description as for why);
 - since commit 0e9a3358 it might no longer be necessary to have initWaiter at all.
 
So I opened a draft PR to remove it (#4441).

**Comment by kolyshkin** [comment]
Frankly, I don't understand what this PR is doing, or what difference does it make, from looking in the `main` branch code.

**Comment by lifubang** [comment]
Like I mentioned in https://github.com/opencontainers/runc/pull/4439#discussion_r1797129372
If we removed this `initWaiter`, the cgroup resource accounting before `nl_parse(pipenum, &config)` in `runc init` maybe lost when we are joining the cgroup.
https://github.com/opencontainers/runc/blob/ea5f8e0445e80dc29acd9b5d57481a0e936af89b/libcontainer/nsenter/nsexec.c#L896

**Comment by lifubang** [comment]
> I don't understand what this PR is doing,

I think the `waitInit` chan waiting's place is wrong, it will also cause this unimportant race situation mentioned above, so I place it in the correct place. This is what this PR doing.
And I have test it, it will not introduce any performance issue in the main branch.

**Comment by lifubang** [comment]
The other aspect, keep this `initWaiter` also may be useful for future, for example, maybe for some times in futrue, we need to add some expensive function call like `ensure_cone_binary` in `nsexec`.

**Comment by kolyshkin** [comment]
Yes, I can understand why this is needed in 1.1.

I still can not understand why this is needed here in the main branch, what race it is fixing, what difference does it make.

Can you please explain the race in details to me? Like, draw two columns, one for runc parent, another for runc init, and write which one is doing what and how a race can happen.

Or, I will take another look next week (maybe I'm just dumb and tired).

> The other aspect, keep this `initWaiter` also may be useful for future, for example, maybe for some times in future, we need to add some expensive function call like `ensure_clone_binary` in `nsexec`.

This is not a good argument. First of all, we hope we'll have less code in nsexec, not more, and in general, the less locking and synchronization there is, the better.

**Comment by lifubang** [comment]
Yes, you are right, there is only one function call `setup_logpipe()` in `nsexec.c`, the race window is very small, it's not worth a sync now.

**Comment by rata** [comment]
@lifubang can you please explain what was the race anyways? I

**Pull request closed without merging**
