### PR TITLE
Remove unreachable code paths

### PR DESCRIPTION
**Pull request by saschagrunert**
Hey, I'm not sure if this kind of optimization is welcome but during my investigations I came across some unreachable code paths. I took the liberty to remove them. WDYT?

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
needs rebase

**Comment by saschagrunert** [comment]
Rebased on top of the latest master branch.

**Comment by AkihiroSuda** [comment]
LGTM

**Comment by saschagrunert** [comment]
> CI failing
> 
> ```
> # github.com/opencontainers/runc/libcontainer
> libcontainer/container_linux.go:457:26: not enough arguments in call to c.commandTemplate
> libcontainer/container_linux.go:457:30: undefined: childPipe
> Makefile:34: recipe for target 'runc' failed
> ```

Thanks for the hint, should be fixed now.

**Comment by AkihiroSuda** [comment]
LGTM (if green)

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
