### PR TITLE
support hierarchy setting for memory cgroup subsystem

### PR DESCRIPTION
**Pull request by ddongchen**
We should support setting hierarchy for memory cgroup subsystem.

### CODE REVIEW

**Comment by cyphar** [comment]
You need to add a `Signed-off-by:` line to your commit(s) which indicates that you attest the [Developer Certificate of Origin](https://developercertificate.org/) a statement about your contributions that you *must read* before signing (don't worry, it's quite short and easy-to-read). You can add it to your commits with `git commit --amend -s`, and then doing a `git push --force`.

**Comment by cyphar** [comment]
In addition, you're adding `libcontainer` changes without any other corresponding changes -- users won't be able to set that value.

As for the *spirit* of the change, I think that the idea is fine, but the execution is a bit more complicated than just setting `use_hierarchy`. In particular, I believe you need to set it in the root of the cgroup in order for the setting to be useful, which means that we have to modify global cgroup policy. Most distributions already set `use_hierarchy=1` by default (Ubuntu used to be well-known for not doing it, but they do it now). So I'm wondering in which cases you actually have had a distribution that was using the (broken) hierarchy in memcg.

**Comment by ddongchen** [comment]
@cyphar, The distribution in use is fedora, the **use_hierarchy** is 0 by default(maybe the version is too old, it's linux kernel 3.10). Therefore, we need to set the **use_hierarchy** for root cgroup or the related child cgroup. 
Besides, we should support the user to set **0** for **use_hierarchy**, if they do not want to static the children's usage.

**Comment by ddongchen** [comment]
I signed it!

**Comment by ddongchen** [comment]
I added Signed-off-by.
Thank you for the comment.

**Comment by AkihiroSuda** [comment]
Fedora switched away to cgroup v2.
Can we close this?

**Pull request closed without merging**
