### PR TITLE
fix typos by the result of golint checking 

### PR DESCRIPTION
**Pull request by YuPengZTE**
Signed-off-by: yupeng <yu.peng36@zte.com.cn>

### CODE REVIEW

**Comment by hqhq** [comment]
It's what we do, but that's not a big deal, so there are still lots of such cases in runc code. If you are doing this, do you mind grepping in runc code and fix them all in this PR?

**Comment by YuPengZTE** [comment]
@hqhq 
I do it by [golint](https://github.com/golang/lint). The result of checking error string is 
[error_ strings.txt](https://github.com/opencontainers/runc/files/621339/error_.strings.txt).

In
https://github.com/opencontainers/runc/blob/master/libcontainer/configs/config_unix.go/#L12
https://github.com/opencontainers/runc/blob/master/libcontainer/configs/config_unix.go/#L16
https://github.com/opencontainers/runc/blob/master/libcontainer/configs/config_unix.go/#L29
https://github.com/opencontainers/runc/blob/master/libcontainer/configs/config_unix.go/#L33
, a punctuation is in the middle of the sentence, so there is no need to fix them.

In docker, golint is imported, is there need to import golint here?

**Comment by YuPengZTE** [comment]
[golint4runc.txt](https://github.com/opencontainers/runc/files/621380/golint4runc.txt)
This is all of golint result. 
If in accordance with it to modify code, it may not be necessary.

**Comment by crosbymichael** [comment]
LGTM

**Comment by hqhq** [comment]
LGTM

**Pull request merged**
