### PR TITLE
libcontainer: integration: fix flaky pids limit tests

### PR DESCRIPTION
**Pull request by cyphar**
Because we are implemented in Go, the number of pids present in a
container is not very well-defined (other than it not being /much/
bigger than the limit you'd want to set). As a result, we need to make
the tests a bit less flaky in this regard.

Signed-off-by: Aleksa Sarai <asarai@suse.com>

/cc @LK4D4 @crosbymichael @vmarmol @mrunalp @dqminh

### CODE REVIEW

**Comment by dqminh** [comment]
Can you explain a bit why this is less flaky ?

**Comment by cyphar** [comment]
@dqminh Essentially, there's an overhead when we are setting up the container. This overhead doesn't go away until the processes have been completely cleaned up by the kernel (which usually doesn't happen before `sh` has called all of its processes). This overhead isn't constant (it depends on how many new threads Go spawns because syscalls are blocking), but it shouldn't reasonably be more than 32 processes. Our old pseudo-overhead of 4 processes isn't large enough on kernel 4.4 because the process has to be *completely* cleaned up, not just exited.

**Comment by crosbymichael** [comment]
LGTM

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
