### PR TITLE
Libcontainer: refactor capabilities code and remove RHEL6 workaround

### PR DESCRIPTION
**Pull request by thaJeztah**
See individual commit messages for details

### CODE REVIEW

**Comment by thaJeztah** [comment]
@kolyshkin @mrunalp ptal

**Comment by AkihiroSuda** [comment]
Can we update the README to clarify the current minimum kernel requirement? 3.10? (Does it work without Red Hat patches?)

**Comment by thaJeztah** [comment]
I don't think we test 3.10.x on anything other than RHEL 7 / CentOS 7 kernels. Not sure if there's still uses of runc on Debian Jessie (3.16); I know that kernel was somewhat problematic at some point.

Perhaps we should be explicit on the intent; something along the lines of "Runc support kernel 3.10 to facilitate RHEL7 and CentOS7. For other distributions, we recommend/support kernel 4.0 and up"

**Comment by thaJeztah** [comment]
FWIW; I'd be ok with keeping the RHEL6 hack if it's a concern (removing it is just a minor cleanup, so I'm not strongly attached to removing it)

**Review by kolyshkin — APPROVED** [review]
LGTM, and thanks!

**Comment by kolyshkin** [comment]
@AkihiroSuda @mrunalp PTAL

**Review by AkihiroSuda — APPROVED** [review]

**Pull request merged**
