### PR TITLE
execve runc init-boot after nsexec()

### PR DESCRIPTION
**Pull request by lifubang**
An alternative solution of #4193 .
Just test the CI, please help me to know what's wrong with `/proc/self/exe: error while loading shared libraries: libseccomp.so.2: cannot open shared object file: No such file or directory` in some tests.

### CODE REVIEW

**Comment by lifubang** [comment]
https://github.com/opencontainers/runc/pull/4193#issuecomment-2035856446
> Use fork(2) to replace clone(CLONE_PARENT) will cause runc more slower, I do a test in my machine, to start 100 containers, the total used time becomes 4.135s from 3.987s, which is increased by 148 ms, so it will increase 1.48 ms to start one container.

The time to run 100 containers:
CLONE_PARENT: 3.987s
fork: 4.135s
re-exec: 4.724s

**Comment by lifubang** [comment]
> Just test the CI, please help me to know what's wrong with `/proc/self/exe: error while loading shared libraries: libseccomp.so.2: cannot open shared object file: No such file or directory` in some tests.

@cyphar @AkihiroSuda @kolyshkin Could you please help to figure out why this error occurs? Thanks.

**Comment by cyphar** [comment]
Ah, if we are joining another container's mount namespace we can't load the right shared libraries. And also this would allow a container to attack the host because at the re-exec point we haven't applied most of the security labels and other restrictions.

Sorry, I should've thought about this when I suggested it. This would work with a static runc build but for dynamically linked builds this isn't workable.

Yeah, I think fork is the only workable option then...

**Comment by lifubang** [comment]
Thanks your explanation!

**Pull request closed without merging**
