### PR TITLE
man page update for delete command

### PR DESCRIPTION
**Pull request by rajasec**
Changed the status of container from destroyed to stopped in man page.
Signed-off-by: rajasec rajasec79@gmail.com

### CODE REVIEW

**Comment by hqhq** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Comment by crosbymichael** [comment]
@caniszczyk did we change something on this repo with the merge settings because its currently requiring you to approve via pullapprove and the new github review system before it can be merged?  

I cannot find the setting to change this for the repo so I don't think I made the change.

**Comment by crosbymichael** [comment]
@caniszczyk I actually found the setting under protected branches and removed it so that the repo is the same as the runtime spec relying on pullapprove only.

**Pull request merged**
