### PR TITLE
Dockerfile: update to bats-core

### PR DESCRIPTION
**Pull request by cyphar**
In the past few years, bats was effectively abandoned and has been
forked to bats-core. It has a vast array of improvements, and has
updated actual version.

Signed-off-by: Aleksa Sarai <asarai@suse.de>

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
CI failing?

**Comment by thaJeztah** [comment]
@cyphar could you rebase this one to see if CI still fails?

**Comment by AkihiroSuda** [comment]
needs rebase

**Comment by AkihiroSuda** [comment]
superseded by https://github.com/opencontainers/runc/pull/2307

**Pull request closed without merging**
