### PR TITLE
Add infomation about ocitools in runc spec

### PR DESCRIPTION
**Pull request by hqhq**
Signed-off-by: Qiang Huang <h.huangqiang@huawei.com>

### CODE REVIEW

**Comment by hqhq** [comment]
So we don't need to do any `runc spec` expansion as https://github.com/opencontainers/runc/pull/764 tried to do.

**Comment by cyphar** [comment]
I'd like it if we added the information to `runc spec --help` as well. Something like "if you want more control of the output `config.json` please use `ocitools`".

**Comment by hqhq** [comment]
@cyphar It is in `runc spec --help`.

**Comment by cyphar** [comment]
Oops. I misread the filename. ;)

LGTM.

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
