### PR TITLE
Refactor enum map range to slice range

### PR DESCRIPTION
**Pull request by ggaaooppeenngg**
grep -r "range map" shows 3 parts use map to
range enum types, use slice instead can get
better performance and less memory usage.

Signed-off-by: Peng Gao <peng.gao.dut@gmail.com>

### CODE REVIEW

**Comment by crosbymichael** [comment]
LGTM

Thanks!

**Comment by crosbymichael** [comment]
I'm getting build errors:

```
michael|~/runc > make
go build -i -ldflags "-X main.gitCommit="dbd7b3a5621c0497eb82768e62001134c183967d" -X main.version=1.0.0-rc1" -tags "seccomp" -o runc .
# github.com/opencontainers/runc/libcontainer
../development/gocode/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:234: undefined: pair in pair.k
../development/gocode/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:238: undefined: pair in pair.k
../development/gocode/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:240: undefined: pair in pair.v
Makefile:30: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by ggaaooppeenngg** [comment]
@crosbymichael  done.

**Comment by dqminh** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
