### PR TITLE
Removing tty0 tty1 from allowed devices

### PR DESCRIPTION
**Pull request by rajasec**
Removing the host devices tty0 and tty1 from allowed devices.

Signed-off-by: rajasec <rajasec79@gmail.com>

### CODE REVIEW

**Comment by mrunalp** [comment]
LGTM

**Comment by crosbymichael** [comment]
Can you explain why?

**Comment by rajasec** [comment]
@crosbymichael 
As this are host virtual consoles, so does not need to be part of container.

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
