### PR TITLE
libct/cg/fs2/freezer: optimize and fix

### PR DESCRIPTION
**Pull request by kolyshkin**
`fs2.setFreezer` improvements:

1. Optimize it to do 1 open instead of 3 (or 0 instead of 1 in case `config.Undefined` is passed).
2. Fix it to actually wait for freeze to be finished.

Please see individual commits for details.

Note: I chose to use simple wait/retry for re-reading `cgroup.events`. An implementation based on `poll(2)` or `inotify(7)` is possible, but it makes things more complicated. If needed, a poll- or inotify-based waiting can be add later.

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
> Note: I chose to use simple wait/retry for re-reading cgroup.events. An implementation based on poll(2) or inotify(7) is possible, but it makes things more complicated. If needed, a poll- or inotify-based waiting can be add later.

Could you mention inotify in the code comments as TODO (or just open an issue for inotify), then LGTM

**Comment by cyphar** [comment]
LGTM aside from Akihiro's nit.

**Comment by kolyshkin** [comment]
> Could you mention inotify in the code comments as TODO (or just open an issue for inotify), then LGTM

Added a `XXX` comment (as this is "maybe TODO" rather than a hard TODO).

(I actually did a poll(2)-based implementation but it looked so horrible I ditched it. Haven't tried inotify yet (although there's already an implementation in `libcontainter/notify_linux_v2.go` that can possibly be reused.)

**Review by cyphar — APPROVED** [review]
LGTM.

**Comment by kolyshkin** [comment]
Fedora CI failed during `vagrant up`; restarted

**Review by AkihiroSuda — APPROVED** [review]

**Pull request closed without merging**
