### PR TITLE
New netlink library

### PR DESCRIPTION
**Pull request by LK4D4**
I want to play with ipvlan networking with libcontainer, therefore I need new netlink library. I replaced all current calls with it.

### CODE REVIEW

**Comment by mrunalp** [comment]
:+1: I will test this in a bit.

**Comment by mrunalp** [comment]
Could you rebase so it is easier to test? :)

**Comment by crosbymichael** [comment]
Have you two been able to test this change? is it still wanted?

**Comment by mrunalp** [comment]
@LK4D4 Could you rebase this? :)

**Comment by LK4D4** [comment]
@mrunalp @crosbymichael rebased. I tested, it works ok. If we want to maintain libcontainer further, then probably this PR is good idea.

**Comment by crosbymichael** [comment]
LGTM

**Comment by mrunalp** [comment]
I did some basic testing and LGTM.

**Pull request merged**
