### PR TITLE
Bump CRIU to 3.12

### LINKED ISSUE #2068: make integration hangs on Ubuntu 19.04 (related to CRIU)
```console
$ make integration
...
docker run  -t --privileged --rm -v /lib/modules:/lib/modules:ro -v /home/suda/gopath/src/github.com/opencontainers/runc:/go/src/github.com/opencontainers/runc runc_dev:master make localintegration TESTPATH=
go build -buildmode=pie  -ldflags "-X main.gitCommit="a77c3195e91c3930b51092a52612cfe77576007b" -X main.version=1.0.0-rc8+dev " -tags "seccomp" -o runc .
go build -buildmode=pie  -ldflags "-X main.gitCommit="a77c3195e91c3930b51092a52612cfe77576007b" -X main.version=1.0.0-rc8+dev " -tags "seccomp" -o contrib/cmd/recvtty/recvtty ./contrib/cmd/recvtty
bats -t tests/integration
1..77
ok 1 runc update --kernel-memory (initialized)
ok 2 runc update --kernel-memory (uninitialized)
ok 3 runc create (no limits + no cgrouppath + no permission) succeeds
ok 4 # skip (test requires rootless) runc create (rootless + no limits + cgrouppath + no permission) fails with permission error
ok 5 # skip (test requires rootless) runc create (rootless + limits + no cgrouppath + no permission) fails with informative error
ok 6 runc create (limits + cgrouppath + permission on the cgroup dir) succeeds
ok 7 runc exec (limits + cgrouppath + permission on the cgroup dir) succeeds
ok 8 checkpoint and restore
ok 9 checkpoint --pre-dump and restore
not ok 10 checkpoint --lazy-pages and restore
# (in test file tests/integration/checkpoint.bats, line 196)
#   `[ "$status" -eq 1 ]' failed
# runc list (status=0):
# ID          PID         STATUS      BUNDLE      CREATED     OWNER
# runc spec (status=0):
#
# runc state test_busybox (status=0):
# {
#   "ociVersion": "1.0.1-dev",
#   "id": "test_busybox",
#   "pid": 10336,
#   "status": "running",
#   "bundle": "/tmp/busyboxtest",
#   "rootfs": "/tmp/busyboxtest/rootfs",
#   "created": "2019-06-06T06:58:29.691435658Z",
#   "owner": ""
# }
# runc list (status=0):
# ID             PID         STATUS      BUNDLE             CREATED                          OWNER
# test_busybox   10336       running     /tmp/busyboxtest   2019-06-06T06:58:29.691435658Z   root
# runc kill test_busybox KILL (status=0):
#
# runc delete test_busybox (status=0):
#
ok 11 checkpoint and restore in external network namespace
ok 12 checkpoint and restore with container specific CRIU config
(hang)
```

Ubuntu 19.04, kernel `5.0.0-16-generic #17-Ubuntu`, runc a77c3195e91c3930b51092a52612cfe77576007b

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Signed-off-by: Akihiro Suda <akihiro.suda.cz@hco.ntt.co.jp>

Seems to fix #2068 
cc @adrianreber

### CODE REVIEW

**Comment by adrianreber** [comment]
Looks good to me :+1:

**Comment by crosbymichael** [comment]
LGTM

**Comment by AkihiroSuda** [comment]
ping @cyphar

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
