### PR TITLE
Fixing file close

### PR DESCRIPTION
**Pull request by rajasec**
Defer to close the file

Signed-off-by: Rajasekaran <rajasec79@gmail.com>

### CODE REVIEW

**Comment by LK4D4** [comment]
@rajasec I sorta don't understand change. Why we need to defer `Close` if we know exact moment when we can close it and there  is no flow interruptions before that point?

**Comment by rajasec** [comment]
@LK4D4 
I agree with your point on exact moment when we can close it, this change would be small ( not major) effective in error handling of file handling after each open call. You don't need to add explicit close after system.Setns (i.e the reason I've removed the close after system.Setns) . This will ensure that the file descr is closed while the function ends irrespective of any errors or any flow interruptions.

if ns.Path != "" {
			f, err := os.OpenFile(ns.Path, os.O_RDONLY, 0)
			if err != nil {
				return err
			}
			defer f.Close()
			err = system.Setns(f.Fd(), uintptr(ns.Syscall()))
			if err != nil {
				return err

**Comment by LK4D4** [comment]
Previous code ensured closing as well. I think here close is ok. There is no rule that you must close only in defer :)

**Comment by rajasec** [comment]
Thanks. I'll close this PR.

**Pull request closed without merging**
