### PR TITLE
Add name to cgroup subsystem and set order

### PR DESCRIPTION
**Pull request by crosbymichael**
Fixes #327

### CODE REVIEW

**Comment by YujiOshima** [comment]
@crosbymichael It's looks so smart change. Thanks!

**Comment by crosbymichael** [comment]
@YujiOshima thanks for reviewing it !!!

**Comment by mrunalp** [comment]
LGTM

**Comment by hqhq** [comment]
lgtm, thanks.

**Comment by mrunalp** [comment]
We should probably make the same changes for systemd as well.

**Comment by crosbymichael** [comment]
@mrunalp updated systemd

**Comment by mrunalp** [comment]
LGTM (pending jenkins) If it doesn't come back in a bit, I will run the tests locally.

**Comment by mrunalp** [comment]
@LK4D4 ping

**Comment by mrunalp** [comment]
LGTM reping @LK4D4 :)

**Comment by crosbymichael** [comment]
@LK4D4 i added the error return value so that you don't have the `nil` check anymore on `Get`

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
