### PR TITLE
[1.1] release: add runc.keyring file

### PR DESCRIPTION
**Pull request by cyphar**
Backport of:

 * #3824
 * #3836 
 * #3840 
 * #3844 

In order to allow any of the maintainers to cut releases for runc,
create a keyring file that distributions can use to verify that releases
are signed by one of the maintainers.

The format matches the gpg-offline format used by openSUSE packaging,
but it can be easily imported with `gpg --import` so any distribution
should be able to handle this keyring format wtihout issues.

Each key includes the GitHub handle of the associated user, and a new
verification step is added to CI to ensure that the key is actually one
of the keys the user has registered with GitHub (as well as being a
maintainer).

Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>

### CODE REVIEW

**Comment by kolyshkin** [comment]
1. I was hoping we won't be making any more 1.1 releases, instead concentrating on releasing 1.2.0-rc. Surely this might not be true...
2. Do we need to maintain runc.keyring in two branches? I mean, we can just refer to https://raw.githubusercontent.com/opencontainers/runc/main/runc.keyring

**Comment by AkihiroSuda** [comment]
> 1. I was hoping we won't be making any more 1.1 releases, instead concentrating on releasing 1.2.0-rc. Surely this might not be true...

Probably we still have to make a couple of 1.1 releases.


> 2. Do we need to maintain runc.keyring in two branches? I mean, we can just refer to https://raw.githubusercontent.com/opencontainers/runc/main/runc.keyring

No

**Comment by kolyshkin** [comment]
> I was hoping we won't be making any more 1.1 releases, instead concentrating on releasing 1.2.0-rc. Surely this might not be true...

Surely. I think we need to backport #3842

**Comment by kolyshkin** [comment]
Guess we also need to backport https://github.com/opencontainers/runc/pull/3840

**Comment by cyphar** [comment]
> Do we need to maintain runc.keyring in two branches?

I think it would be a good idea because it would mean we'd have `runc.keyring` in the released tarball for the next 1.1.z release. We won't need to update `runc.keyring` very regularly, so this is probably going to be a once-off thing (1.2.0+ will get `runc.keyring` from `main`).

**Review by kolyshkin — APPROVED** [review]
LGTM

**Comment by kolyshkin** [comment]
@cyphar this needs a rebase

**Comment by kolyshkin** [comment]
> @cyphar this needs a rebase

(nevermind, I was able to make github merge it)

**Pull request merged**
