### PR TITLE
Vagrantfile.fedora: upgrade Fedora to 38

### PR DESCRIPTION
**Pull request by AkihiroSuda**

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
```
Bringing machine 'default' up with 'libvirt' provider...
==> default: Box 'fedora/38-cloud-base' could not be found. Attempting to find and install...
    default: Box Provider: libvirt
    default: Box Version: >= 0
==> default: Loading metadata for box 'fedora/38-cloud-base'
    default: URL: https://vagrantcloud.com/fedora/38-cloud-base
==> default: Adding box 'fedora/38-cloud-base' (v38.20230413.1) for provider: libvirt
    default: Downloading: https://vagrantcloud.com/fedora/boxes/38-cloud-base/versions/38.20230413.1/providers/libvirt.box

An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
```

**Comment by kolyshkin** [comment]
This looks like https://github.com/hashicorp/vagrant/issues/12921 (plus a combination of some server-side changes, I guess).

The code in question was added 5 years ago in vagrant 2.1.3 (https://github.com/hashicorp/vagrant/commit/447e58dac3edc77f655379729d172a3503d7019c) , and it was fixed (by https://github.com/hashicorp/vagrant/pull/12925/commits/c7ef689d86294bcdb8ae5d31ddabcba416e3382d) in vagrant 2.3.1.

Now, apparently we use vagrant 2.2.19 in CI, thus the issue.

**Comment by AkihiroSuda** [comment]
- https://github.com/opencontainers/runc/pull/3848

**Comment by kolyshkin** [comment]
Filed a bug to Ubuntu: https://bugs.launchpad.net/vagrant/+bug/2017828

**Pull request closed without merging**
