### PR TITLE
Remove sniffTest

### PR DESCRIPTION
**Pull request by hqhq**
We have integration test now, not ideal though, but it
surely can replace sniffTest.

Signed-off-by: Qiang Huang <h.huangqiang@huawei.com>

### CODE REVIEW

**Comment by cyphar** [comment]
> I don't think snifftest is needed anymore, it's all covered by integration test, so I tried to remove it in #785 WDYT?

I don't really have a strong opinion, but it does appear redundant to have a sniff test that is then replicated in an integration test.

/cc @duglin -- do you have any reason why we should keep it in? In #554 you mention that the sniff tests were just meant to be a stopgap until we had a proper testing framework -- I think bats qualifies.

**Comment by duglin** [comment]
I agree and if there is some tests in sniff that's missing from integration then we should add it.
so +1 from me

**Comment by cyphar** [comment]
In that case, LGTM.

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
