### PR TITLE
Changing OCF to OCI in README

### PR DESCRIPTION
**Pull request by rajasec**
Changed to OCI in README
Signed-off-by: rajasec <rajasec79@gmail.com>

### CODE REVIEW

**Comment by hqhq** [comment]
LGTM

**Comment by cyphar** [comment]
LGTM

**Comment by hqhq** [comment]
Yeah, but don't know who's maintaining that.
And pullapprove seems not work properly, team info from organization is not synced to projects. I've sent an email to a pullapprove guy to get some help.

**Comment by cyphar** [comment]
As a separate point, I'd like to know who the artist (and copyright holder) are for the [runC hamster](https://runc.io//images/hamster.png). My guess is that @crosbymichael probably knows the answer to both questions.

**Comment by thaJeztah** [comment]
Artist is Laurel http://bloglaurel.com, but don't know about copyright holder

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
