### PR TITLE
[1.2] runc delete: fix for rootless cgroup + ro cgroupfs

### PR DESCRIPTION
**Pull request by lifubang**
Backport: 

- #4523
- https://github.com/opencontainers/runc/pull/4526

----
This is an alternative to #4520.

----

An issue with runc 1.2.0 was reported to buildkit and then here (#4518),
in which `runc delete` returns with an error, with the log saying:
    
> unable to destroy container: unable to remove container's cgroup: open /sys/fs/cgroup/snschvixiy3s74w74fjantrdg: no such file or directory
    
Apparently, what happens is runc is running with no cgroup access
(because /sys/fs/cgroup is mounted read-only). In this case error to
create a cgroup path (in runc create/run) is ignored, but cgroup removal
(in runc delete) is not.
    
This is caused by commit d3d7f7d, which changes the cgroup removal
logic in `RemovePath`, and contains a bug. In the current code, if the
initial rmdir has failed (in this case with `EROFS`), but the subsequent
`os.ReadDir` returns `ENOENT`, that error it is ultimately returned
(instead of being ignored -- since the path does not  exist, there is
nothing to remove).
    
This PR fixes the issue in 3 commits:
1. A minimal but sufficient fix for the issue, targeted for quick review and backport to v1.2.2.
2. An improvement to RemovePath logic (originally suggested by @thaJeztah [here](https://github.com/opencontainers/runc/pull/4520#pullrequestreview-2426512896)
3. An improvement to RemovePath comments, better explaining what's going on.

Only the first commit is changing the logic and fixing the issue -- the rest is mostly
cosmetic and "nice to have".

Fixes: #4518.

TODO: add a test case.

### CODE REVIEW

**Comment by kolyshkin** [comment]
Can we please add a backport of #4526 here (once it's merged)? I saw #4527 but logically it belongs here.

**Comment by lifubang** [comment]
> Can we please add a backport of #4526 here (once it's merged)? I saw #4527 but logically it belongs here.

Added, #4527 is used to verify the test is correct or not.

**Review by kolyshkin — APPROVED** [review]
One nit: PR description does not mention #4526 backport.

Otherwise LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM

**Pull request merged**
