### PR TITLE
VERSION: release 1.1.8 (Support RISC-V)

### PR DESCRIPTION
**Pull request by AkihiroSuda**
## [1.1.8] - 2023-07-20

> 海纳百川 有容乃大

### Added

* #3905

### Fixed

* #3879
* #3877
* #3891
* #3892
* #3916
* #3917
* #3918
* #3932
* #3921

### Changed

* #3878
* #3909

### CODE REVIEW

**Review by kolyshkin — APPROVED** [review]
I've checked that everything we wanted is merged, and that the changelog is adequate, so we're good to go.

LGTM

**Review by cyphar — APPROVED** [review]
LGTM. Any ideas for a name @AkihiroSuda? :smile_cat:

**Review by lifubang — APPROVED** [review]

**Comment by lifubang** [comment]
> Any ideas for the release name

Could you consider chinese? How about "海纳百川 有容乃大"? This is a homophone about container technology.

The original meaning:
1. The sea can hold the water from thousands of rivers, it's big because of its capacity.
2. A person is great when he can be tolerant and forgiving to many other people.

Consider '容' as 'Container', and we make this release mainly to support RISC-V, it means:
We accept everything running in the container, if you have master container technology, you will own a great power and capacity.

Feel free to refuse it.

**Comment by cyphar** [comment]
https://github.com/opencontainers/runc/releases/tag/v1.1.8

**Pull request merged**
