### PR TITLE
Add network speed limit function,based on Traffic Control' TBF implem…

### PR DESCRIPTION
**Pull request by liuwharton**
Ovs network speed limit is not stable,So choose tc speed limit.
Tc's TBF speed limit consumption of resources.
tc_tbf.c get in the iproute/tc's source code

Signed-off-by: liuwharton whartonliu@gmail.com

### CODE REVIEW

**Comment by hqhq** [comment]
@liuwharton What's the usage with your PR? runC already supported net_cls cgroup, what the difference between your PR and people use net_cls + tc to control network speed limit?

**Comment by liuwharton** [comment]
@hqhq Used net_cls + tc ,need to operate two steps. My PR let docker support the network speed limit, only one step can be completed speed limit effect.

**Comment by liuwharton** [comment]
Modify tc_tbf.c  file,diff  new_file old_file,bash command diff output is as follows:
78,82c78,82
<     // burst,1m rate corresponding 1k burst
<     unsigned burst=rate_mbit * 1024;
<     //  latency = 70
<     opt.limit=70*rate_mbit*125+burst;
<     opt.buffer=(burst/1024/rate_mbit)*128000;
---
>     // burst 
>     unsigned burst=rate_bit/1000;
>     //  latency = 70 ,burst= ratebit/1000
>     opt.limit=70*rate_bit+burst;
>     opt.buffer=rate_bit/burst * 128;

**Comment by cyphar** [comment]
I'm closing this PR since it's been inactive for over 2 years. As @hqhq said, it's not really clear what additional benefit this gives over `net_cls`. However here is my main comment if you want to continue working on this: This should be written in Go, not C. We already use a Go netlink library, and with `golang.org/x/sys/unix` there are very few things you cannot do in Go which you would traditionally use C for.

**Pull request closed without merging**
