### PR TITLE
VERSION: release 1.0.0-rc8

### PR DESCRIPTION
**Pull request by cyphar**
Signed-off-by: Aleksa Sarai <asarai@suse.de>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Comment by thaJeztah** [comment]
@mrunalp ptal 🤗

**Comment by mrunalp** [comment]
LGTM

**Comment by cyphar** [comment]
Huh, and @mrunalp's LGTM isn't triggering pullapprove. (Though, I can just merge and push anyway.)

Still waiting on a few more people to vote on the motion (@crosbymichael I didn't see a mail from you on the ML).

**Comment by andrewhsu** [comment]
SGTM w.r.t. getting changes into runc release that will help selinux to work with docker

**Comment by mrunalp** [comment]
pullapprove hasn't been very reliable on this repo. cc: @caniszczyk

**Comment by thaJeztah** [comment]
pullapprove looks to be good now (perhaps was just slow)

**Comment by cyphar** [comment]
Whoa whoa whoa, the vote on the list wasn't finished! And the merge commit isn't signed!

**Pull request merged**
