### PR TITLE
go.mod: golang.org/x/*: use tagged versions

### PR DESCRIPTION
**Pull request by AkihiroSuda**
- https://github.com/golang/net/compare/6772e930b67b...v0.1.0
- https://github.com/golang/sys/compare/f11e5e49a4ec...v0.1.0

### CODE REVIEW

**Review by kolyshkin — APPROVED** [review]
LGTM assuming CI is green

**Review by kolyshkin — APPROVED** [review]
still LGTM

**Comment by kolyshkin** [comment]
@thaJeztah @cyphar PTAL

**Review by thaJeztah — APPROVED** [review]
LGTM 👍

**Pull request merged**
