### PR TITLE
Remove hard-coded default for tcp connections

### PR DESCRIPTION
**Pull request by crosbymichael**
Signed-off-by: Michael Crosby <crosbymichael@gmail.com>

### CODE REVIEW

**Comment by boucher** [comment]
I just noticed this. I haven't really tested these changes yet, but I was planning to submit this soon and propose inverting all the params: https://github.com/opencontainers/runc/compare/master...boucher:criu-opts

**Comment by mrunalp** [comment]
LGTM

**Comment by crosbymichael** [comment]
ping @LK4D4

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
