### PR TITLE
Fixing #1809

### PR DESCRIPTION
**Pull request by frezbo**
Signed-off-by: Noel Georgi <18496730+frezbo@users.noreply.github.com>

@AkihiroSuda @cyphar I think its time to add some simple PR checks, I can think of travis or something.

### CODE REVIEW

**Comment by frezbo** [comment]
Hmm seems we have a travis, wonder how we got this merged in?

**Comment by AkihiroSuda** [comment]
Thanks but dupe of https://github.com/opencontainers/runc/pull/1808

>  I think its time to add some simple PR checks, I can think of travis or something.

As mentioned in https://github.com/opencontainers/runc/pull/1808 this was caused by merge conflict.
So unlikely to be checkable on CI.

**Comment by frezbo** [comment]
ahh yes, thanks.

**Comment by cyphar** [comment]
A simple way of fixing it would be to only allow PRs that have been rebased to be merged. I do this in `umoci` but I think it starts pissing people off when you ask them to rebase a PR 50 times. :wink:

**Pull request closed without merging**
