### PR TITLE
Simplify and fix os.MkdirAll() usage

### PR DESCRIPTION
**Pull request by kolyshkin**
Please review; I find it moderately serious as missing error from MkdirAll() can lead to some other errors at a later stage, possibly hard to track down to the cause.

### CODE REVIEW

**Comment by kolyshkin** [comment]
Here's an example
 http://play.golang.org/p/xcuYZ1YtyZ

**Comment by LK4D4** [comment]
@kolyshkin You're right, I actually don't see how it can return `EEXIST` in any case.
LGTM

**Comment by kolyshkin** [comment]
@LK4D4 It actually can return EEXIST in a case of the following race (which I was lazy to explain in details, but since you asked for it...).

First, MkdirAll calls stat() and gets ENOENT, so it goes on to check and create all the parents. At this time, someone else creates a file under the same name as the last MkdirAll component. Finally, MkdirAll calls Mkdir to create that last component, Mkdir returns EEXIST which MkdirAll passes to the caller.

**Comment by LK4D4** [comment]
@kolyshkin Totally, thanks for explanation!

**Pull request merged**
