### PR TITLE
use criu cgroup mode const from go-criu

### PR DESCRIPTION
**Pull request by XiaodongLoong**
Signed-off-by: liuxiaodong <liuxiaodong@loongson.cn>

### CODE REVIEW

**Comment by kolyshkin** [comment]
@adrianreber PTAL

**Comment by kolyshkin** [comment]
> and CRIU defaults to SOFT if nothing is set

so it's not just useless but also has wrong value. Yeah I guess it makes sense to remove it

**Comment by kolyshkin** [comment]
Ideally though, we should get those values from go-criu, rather than hardcoding it ourselves. WDYT @adrianreber ?

**Comment by adrianreber** [comment]
> Ideally though, we should get those values from go-criu, rather than hardcoding it ourselves. WDYT @adrianreber ?

Sounds like a good idea. I just checked and they are already exported in go-criu:

https://github.com/checkpoint-restore/go-criu/blob/master/rpc/rpc.pb.go#L25

runc could just use those values.

**Comment by XiaodongLoong** [comment]
OK, I would use those values from go-criu.

**Comment by kolyshkin** [comment]
@XiaodongLoong you forgot to change the commit message and the PR description. The code LGTM.

**Comment by XiaodongLoong** [comment]
@kolyshkin I changed the commit message and PR description. PTAL

**Pull request merged**
