### PR TITLE
log improve,with --log flag, cli will log to special place where user set

### PR DESCRIPTION
**Pull request by keloyang**
https://github.com/opencontainers/runc/pull/1089 only deal with cli.ErrWriter, this pr will add cli.App.Writer too. And with --log flag, cli will log to special places where user set.

Signed-off-by: Shukui Yang <yangshukui@huawei.com>

### CODE REVIEW

**Comment by cyphar** [comment]
For future reference, you don't need to open a new PR each time you change a patchset. Just use `git push --force` and GitHub will display the new set of commits. As for the actual patchset, can you explain what problem it actually fixes (or rather, what was broken before this patch) -- I'm not sure that we use `cli.App.Writer` anywhere inside runC. Thanks.

**Comment by keloyang** [comment]
@cyphar thanks for your reply.
```
default cli.App:
func NewApp() *App {
	return &App{
                                ...
				Writer:       os.Stdout,
	}
}

cli print log:  fmt.Fprintf(a.Writer, ...
```
cli.App.Writer use os.Stdout by default, so cli print common log to stdout,with this pr ,if user set --log flag,
cli.App.Writer can be changed and cli can log to  the special place where user set.

**Comment by mlaventure** [comment]
@keloyang this doesn't seem to work:

```
$ sudo ../runc --log /tmp/my-log.json --log-format json run top .
container_linux.go:247: starting container process caused "exec: \"foo\": executable file not found in $PATH"
$ cat /tmp/my-log.json 
{"level":"warning","msg":"os: process already finished","time":"2016-10-10T07:24:02-07:00"}
```

**Comment by keloyang** [comment]
@mlaventure, thanks, I reproduce it and update done
```
root@ubuntu:~/workspace/runc-test# ./runc --log test.json --log-format json run aa     
root@ubuntu:~/workspace/runc-test# cat test.json 
{"level":"warning","msg":"os: process already finished","time":"2016-10-11T10:47:09+08:00"}
container_linux.go:247: starting container process caused "exec: \"bash\": executable file not found in $PATH"
```

**Comment by mlaventure** [comment]
@keloyang your example is still invalid, the last line of the log file is not in json format.

**Comment by keloyang** [comment]
yes, I ignore it , I think the pr can be closed. thank you.

**Pull request closed without merging**
