### PR TITLE
capabilities.Caps: use a map for capability-types

### PR DESCRIPTION
**Pull request by thaJeztah**
This extracts the refactoring commits from https://github.com/opencontainers/runc/pull/2854

### CODE REVIEW

**Comment by thaJeztah** [comment]
@kolyshkin @AkihiroSuda ptal

**Comment by thaJeztah** [comment]
oh! need to fix something; 

```
--- FAIL: TestSeccompDenyGetcwdWithErrno (0.25s)
=== RUN   TestSeccompDenyGetcwd
    seccomp_test.go:128: container_linux.go:367: starting container process caused: panic from initialization: assignment to entry in nil map, goroutine 1 [running, locked to thread]:
        runtime/debug.Stack(0xc0001af688, 0x8d7a80, 0x9e0050)
        	/opt/hostedtoolcache/go/1.15.10/x64/src/runtime/debug/stack.go:24 +0x9f
        github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func2(0xc0001afea8)
        	/home/runner/work/runc/runc/libcontainer/factory_linux.go:386 +0x57
        panic(0x8d7a80, 0x9e0050)
        	/opt/hostedtoolcache/go/1.15.10/x64/src/runtime/panic.go:975 +0x47a
        github.com/opencontainers/runc/libcontainer/capabilities.New(0xc000020380, 0x0, 0x0, 0xc00007c600)
        	/home/runner/work/runc/runc/libcontainer/capabilities/capabilities.go:44 +0xd1
```

**Review by kolyshkin — APPROVED** [review]
LGTM but this might be post-1.0 material

**Comment by kolyshkin** [comment]
CI hit a snag with centos7 yum repo -- restarted.

**Comment by AkihiroSuda** [comment]
We might want https://github.com/opencontainers/runc/pull/2854 in rc94 or 1.0 GA, so let's merge this to facilitate merging 2854

**Review by AkihiroSuda — APPROVED** [review]

**Pull request merged**
