### PR TITLE
Release runc 1.1.6

### PR DESCRIPTION
**Pull request by kolyshkin**
## [1.1.6] - 2023-04-11

> In this world nothing is certain but death and taxes.
### Compatibility

* This release can no longer be built from sources using Go 1.16. Using a
  latest maintained Go 1.20.x or Go 1.19.x release is recommended.
  Go 1.17 can still be used.

### Fixed

* systemd cgroup v1 and v2 drivers were deliberately ignoring `UnitExist` error
  from systemd while trying to create a systemd unit, which in some scenarios
  may result in a container not being added to the proper systemd unit and
  cgroup. (#3780, #3806)
* systemd cgroup v2 driver was incorrectly translating cpuset range from spec's
  `resources.cpu.cpus` to systemd unit property (`AllowedCPUs`) in case of more
  than 8 CPUs, resulting in the wrong AllowedCPUs setting. (#3808)
* systemd cgroup v1 driver was prefixing container's cgroup path with the path
* of PID 1 cgroup, resulting in inability to place PID 1 in a non-root cgroup.
   (#3811)
* runc run/start may return "permission denied" error when starting a rootless
  container when the file to be executed does not have executable bit set for
  the user, not taking the `CAP_DAC_OVERRIDE` capability into account. This is
  a regression in runc 1.1.4, as well as in Go 1.20 and 1.20.1 (#3715, #3817)
* Various CI fixes and improvements, mostly to ensure Go 1.19.x and Go 1.20.x
  compatibility.

### CODE REVIEW

**Review by austinvazquez — APPROVED** [review]

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by AkihiroSuda — APPROVED** [review]

**Review by hqhq — APPROVED** [review]
LGTM

**Review by cyphar — APPROVED** [review]
LGTM. I'll do the release after the long weekend. (I've also written a script and am working on a CI setup for us to be able to have more than one person sign releases.)

**Comment by cyphar** [comment]
@kolyshkin Done. I've rebased it here, but I wonder if you'd also want to update the changelog in the release commit? I can prep the release as soon as you've fixed it up.

**Review by thaJeztah — APPROVED** [review]
still LGTM

**Review by cyphar — APPROVED** [review]
LGTM.

**Pull request merged**
