### PR TITLE
Vagrantfile: remove podman

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Podman is no longer used in CI

### CODE REVIEW

**Comment by kolyshkin** [comment]
LGTM

**Comment by AkihiroSuda** [comment]
Weird

```
not ok 8 checkpoint and restore 
# (from function `simple_cr' in file tests/integration/checkpoint.bats, line 54,
#  in test file tests/integration/checkpoint.bats, line 71)
#   `simple_cr' failed
# runc list (status=0):
# ID          PID         STATUS      BUNDLE      CREATED     OWNER
# runc spec (status=0):
# 
# runc run -d --console-socket /tmp/console.sock test_busybox (status=0):
# 
# runc state test_busybox (status=0):
# {
#   "ociVersion": "1.0.2",
#   "id": "test_busybox",
#   "pid": 35577,
#   "status": "running",
#   "bundle": "/tmp/busyboxtest",
#   "rootfs": "/tmp/busyboxtest/rootfs",
#   "created": "2020-04-29T02:01:50.953961808Z",
#   "owner": ""
# }
# runc --criu /usr/local/sbin/criu checkpoint --work-path ./work-dir test_busybox (status=1):
# time="2020-04-29T02:01:51Z" level=error msg="container is not destroyed"
# time="2020-04-29T02:01:51Z" level=error msg="criu failed: type NOTIFY errno 0\nlog file: work-dir/dump.log"
# criu failed: type NOTIFY errno 0
# log file: work-dir/dump.log
# (00.001987) Will take cgroup namespace in the image
# (00.001989) Add cgroup ns 13 pid 35577
# (00.001996) Lock network
# (00.001999) Running network-lock scripts
# (00.002001) 	RPC
# (00.002880) Error (criu/util.c:610): exited, status=1
# (00.003472) Error (criu/util.c:610): exited, status=1
# (00.003496) Error (criu/net.c:2613): Locking network failed: iptables-restore returned -1. This may be connected to disabled CONFIG_NETFILTER_XT_MARK kernel build config option.
# (00.003518) Unlock network
# (00.003521) Running network-unlock scripts
# (00.003524) 	RPC
# (00.004386) Error (criu/util.c:610): exited, status=1
# (00.005097) Error (criu/util.c:610): exited, status=1
# (00.005131) Unfreezing tasks into 1
# (00.005136) 	Unseizing 35577 into 1
# (00.005189) Error (criu/cr-dump.c:1743): Dumping FAILED.
# runc list (status=0):
# ID             PID         STATUS      BUNDLE             CREATED                          OWNER
# test_busybox   0           stopped     /tmp/busyboxtest   2020-04-29T02:01:50.953961808Z   root
# runc kill test_busybox KILL (status=1):
# time="2020-04-29T02:01:51Z" level=error msg="container not running"
# container not running
# runc delete test_busybox (status=0):
# 
```

**Comment by AkihiroSuda** [comment]
CI green

**Comment by cyphar** [comment]
LGTM.

**Comment by AkihiroSuda** [comment]
meld into https://github.com/opencontainers/runc/pull/2362

**Pull request closed without merging**
