### PR TITLE
checkpoint: add pre-dump support

### PR DESCRIPTION
**Pull request by adrianreber**
This is based on existing pull requests to implement pre-dump support in
runc. In addition to rebasing this tries to address the open questions
in the previous pull request.

One questions was why the code was no longer waiting (cmd.Process.Wait())
for CRIU in the pre-dump case. This is related to how CRIU expects a
pre-dump to work. Once a pre-dump is started the CRIU RPC process goes
into a loop where it either expects further pre-dumps or the final dump.
From CRIU's point of view this makes sense as it expects the user (runc)
to make as many pre-dumps as necessary and then the final dump.
In its final implementation that is probably also what runc should do.
In this first approach the incremental checkpoints are created manually
by runc as well as the final checkpoint. Therefore the code is still not
waiting for CRIU to end, because it never will. But if we get the RPC
message that the pre-dump was successful CRIU is just terminated.

Instead of passing the pre-dump as additional variable to Checkpoint()
the information about doing a pre-dump is now part of criuOpts.

If referencing a parent image for pre-dump mode the option TrackMem is
now passed to CRIU as it is required.

Examples:

 1. Dump:
  runc checkpoint <container-id> --pre-dump --image-path parent
 2. Final Dump:
  runc checkpoint <container-id> --image-path image --parent-path ../parent
 3: Restore:
  runc restore <container-id> --image-path image

In one test the initial dump was 182M.  The final dump only 6.6M which
decreased the downtime to the time required to transfer 6.6M instead of
182M.

Signed-off-by: Adrian Reber <areber@redhat.com>

### CODE REVIEW

**Comment by adrianreber** [comment]
This is a rebase of #1001 and related to #986

**Comment by adrianreber** [comment]
@avagin can please have a look

**Comment by hqhq** [comment]
@adrianreber AFAICS, https://github.com/opencontainers/runc/pull/1001 is still under discussion and just lack of review after it's last push, so you shouldn't cherry it if @x1022as is still interested in improving it.

**Comment by avagin** [comment]
@adrianreber have you looked at the new libphaul? 
https://github.com/criupatchwork/criu/commit/3fdad140efc49540c513f60786c2d2c26d38587a

**Comment by adrianreber** [comment]
@avagin, yes I looked at that GO implementation of p.haul and I think that in the end this should be the way to do pre-copy migration in runc. I also chatted with @xemul on IRC about it.

My goal with this PR (or #1001) was to get the initial pre-dump version merged and then look how the p.haul based approach works. The logic to do multiple pre-dumps until certain thresholds (number of iterations or number of dirty pages) have been reached sounds like an important improvement.

I have also some patches to use the FEATURE_CHECK RPC mechanism to verify that criu can actually do dirty page tracking which I wanted to use instead of comparing versions.

As a first step, however, I would like to see #1001 or this PR merged.

**Comment by adrianreber** [comment]
Closing as #1001 has been changed to address all open reviewers questions. Thanks @x1022as

**Pull request closed without merging**
