### PR TITLE
Use uint64 for resources to keep consistency with runtime-spec

### PR DESCRIPTION
**Pull request by hqhq**
Signed-off-by: Qiang Huang <h.huangqiang@huawei.com>

### CODE REVIEW

**Comment by mrunalp** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Comment by justincormack** [comment]
This breaks use of the value `-1` which is valid.

**Comment by crosbymichael** [comment]
@justincormack do you want to submit a PR to revert this?

**Comment by hqhq** [comment]
@justincormack `-1` should be usable, can you elaborate what use of value `-1` is broken?

**Pull request merged**
