### PR TITLE
Return a more meaningful error when namespaces are disabled

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Dan Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
This is to help fix a problem found in https://github.com/docker/docker/pull/19265

**Comment by jfrazelle** [comment]
awesome i hit this the other day

On Wed, Mar 30, 2016 at 1:17 PM, Daniel J Walsh <notifications@github.com>
wrote:

> This is to help fix a problem found in docker/docker#19265
> <https://github.com/docker/docker/pull/19265>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/opencontainers/runc/pull/711#issuecomment-203614264>
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by crosbymichael** [comment]
LGTM

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
