### PR TITLE
Revert "Set temporary single CPU affinity before cgroup cpuset transition"

### PR DESCRIPTION
**Pull request by kolyshkin**
This reverts #3923, for reasons outlined in https://github.com/opencontainers/runc/pull/3923#issuecomment-2118520894. A short version below.

---

There's too much logic here figuring out which CPUs to use. Runc is a low level tool and is not supposed to be that "smart". What's worse, this logic is executed on every exec, making it slower. Some of the logic in (*setnsProcess).start is executed even if no annotation is set, thus making ALL execs slow.

Also, this should be a property of a process, rather than annotation.

The plan is to rework this.

This reverts commit afc23e33971b657c4a09c54b16c6139651171aad.

### CODE REVIEW

**Comment by kolyshkin** [comment]
Now, this needs to be reverted before the 1.2 release, as otherwise we'll have to support this.

**Comment by lifubang** [comment]
I see the runtime- spec PR(https://github.com/opencontainers/runtime-spec/pull/1253) has been approved, so it maybe merged recently? How about let the revert commit, bump runtime-spec commit and the new implementation commit completed in one PR.
It looks more make sense, but not very important.

**Comment by kolyshkin** [comment]
> How about let the revert commit, bump runtime-spec commit and the new implementation commit completed in one PR.

Makes sense (although upper-level runtime change is also needed for the whole thing to work again).

Marking this one a draft for the time being.

**Comment by lifubang** [comment]
Because #3923 has not been in any release, and the related PR(https://github.com/opencontainers/runtime-spec/pull/1253) has not been merged yet, so we need to merge this revert PR first if we want to draft 1.2.0-rc2.
@kolyshkin @AkihiroSuda  WDYT

**Review by AkihiroSuda — APPROVED** [review]

**Review by rata — APPROVED** [review]
LGTM

The runtime-spec PR this was implementing was closed (not merged), the new PR is still open. Reverting this seems the right thing to do here.

@kolyshkin do you agree on marking this ready for review and merging?

**Comment by kolyshkin** [comment]
Yes, we need to merge it as we can't have this in a released version (and it blocks some other work). Once https://github.com/opencontainers/runtime-spec/pull/1253 is merged I'll work on implementing it to replace this one.

**Review by lifubang — APPROVED** [review]

**Review by lifubang — APPROVED** [review]

**Comment by lifubang** [comment]
We can prepare release 1.2.0-rc2 now.

**Pull request merged**
