### PR TITLE
libcontainer: merge common syscall implementations

### PR DESCRIPTION
**Pull request by tklauser**
There are essentially two possible implementations for Setuid/Setgid on
Linux, either using SYS_SETUID32/SYS_SETGID32 or SYS_SETUID/SYS_SETGID,
depending on the architecture (see golang/go#1435 for why Setuid/Setgid
aren currently implemented for Linux neither in syscall nor in
golang.org/x/sys/unix).

Reduce duplication by merging the currently implemented variants and
adjusting the build tags accordingly.

Signed-off-by: Tobias Klauser <tklauser@distanz.ch>

### CODE REVIEW

**Comment by cyphar** [comment]
LGTM.

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Comment by crosbymichael** [comment]
@cyphar you will have to re-lgtm

**Comment by cyphar** [comment]
LGTM.

**Pull request merged**
