### PR TITLE
Check args numbers before application start

### PR DESCRIPTION
**Pull request by WeiZhang555**
Add a general args number validator for all client commands.

Signed-off-by: Zhang Wei zhangwei555@huawei.com

### CODE REVIEW

**Comment by hqhq** [comment]
Janky failed.

**Comment by WeiZhang555** [comment]
Fixed

**Comment by WeiZhang555** [comment]
ping @cyphar @hqhq @crosbymichael @mrunalp

**Comment by crosbymichael** [comment]
Can you rebase please?

Changes LGTM

**Comment by WeiZhang555** [comment]
@crosbymichael Rebased :sunglasses:

**Comment by hqhq** [comment]
LGTM

**Comment by cyphar** [comment]
LGTM

**Pull request merged**
