### PR TITLE
golang compiler adds "src" in the end of GOPATH, so README.md file mu…

### PR DESCRIPTION
**Pull request by jhjeong-kr**
…st be impoved as followings

      github.com/opencontainers -> src/github.com/opencontainers
Also, "Introduction page" of runc github need to be updated(seems to be done automatically).

Signed-off-by: Jin-Hwan Jeong <jhjeong.kr@gmail.com>

### CODE REVIEW

**Comment by lizf-os** [comment]
This is a duplicate of #100

**Comment by jhjeong-kr** [comment]
I missed it because the file still remains unchanged, so I patched it.

**Comment by estesp** [comment]
The second commit is not necessary as runc/libcontainer is expected to be built with Go 1.4 which allows for the `range` construct with no "left hand side" (https://golang.org/ref/spec#RangeClause)

**Comment by crosbymichael** [comment]
Closing because we merged #100.

Thanks!

**Pull request closed without merging**
