### PR TITLE
bash completion step for update command

### PR DESCRIPTION
**Pull request by rajasec**
Adding the bash completion step for update command

Signed-off-by: rajasec <rajasec79@gmail.com>

### CODE REVIEW

**Comment by rajasec** [comment]
@mrunalp 
Looks like janky not started the build. I could not get the reason out.

**Comment by cyphar** [comment]
I've restarted the build.

**Comment by rajasec** [comment]
Thanks @cyphar

**Comment by cyphar** [comment]
As for the actual PR, I don't use bash so I can't really test it.

**Comment by marcosnils** [comment]
> I don't use bash so I can't really test it.

curious about what you use? 

Just tested it and it works as described.

**Comment by cyphar** [comment]
@marcosnils The one true shell ZSH. ;)

**Comment by crosbymichael** [comment]
LGTM

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
