### PR TITLE
libcontainer: use Major/Minor from x/sys/unix

### PR DESCRIPTION
**Pull request by tklauser**
The Major and Minor functions were added for Linux in golang/sys@85d1495
which is already vendored in. Use these functions instead of the local
re-implementation.

Signed-off-by: Tobias Klauser <tklauser@distanz.ch>

### CODE REVIEW

**Comment by cyphar** [comment]
LGTM.

**Comment by tklauser** [comment]
> [I should probably use this for umoci as well...]

There you go: openSUSE/umoci#194 ;)

**Comment by TomSweeneyRedHat** [comment]
LGTM, nice little tweak.

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
