### PR TITLE
Add PullApprove support

### PR DESCRIPTION
**Pull request by caniszczyk**
Enforce 2 LGTMs for pull requests.

### CODE REVIEW

**Comment by mrunalp** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Comment by hqhq** [comment]
Don't we need a new team like `runc-maintainers` for reviewers?

**Comment by cyphar** [comment]
Actually, shouldn't this team be `tdc-maintainers` (which is the maintainers of this project)?

**Comment by hqhq** [comment]
@cyphar `tdc-maintainers` doesn't fit `MAINTAINERS` in this repo either, we might need to create a new team.

**Comment by cyphar** [comment]
Hmmm. Yeah, fair point. I've request to join `runtime-spec-maintainers` in the meantime. We should really split all of the maintainer groups for each project into separate projects IMO.

**Pull request merged**
