### PR TITLE
MAINTAINERS: add Sebastiaan van Stijn

### PR DESCRIPTION
**Pull request by kolyshkin**
Sebastiaan is one of the most active contributors recently:
https://github.com/opencontainers/runc/graphs/contributors?from=2019-08-11&to=2021-08-11&type=c

- - -
From https://github.com/opencontainers/runc/blob/602c85fdc6c73d614213fc1759f8e710e54047ca/MAINTAINERS_GUIDE.md

> The final vote to add a new maintainer should be approved by over 66% of the current maintainers with the chief maintainer having veto power. In case of a veto, conflict resolution rules expressed above apply. The voting period is five business days on the Pull Request to add the new maintainer.

In addition to LGTM from @thaJeztah himself, this PR needs at least 5 LGTMs (66%) from the current 7 maintainers.

- [x] @thaJeztah 
- [x] @crosbymichael 
- [x] @mrunalp 
- [x] @dqminh 
- [x] @hqhq 
- [x] @cyphar 
- [x] @AkihiroSuda
- [x] @kolyshkin

### CODE REVIEW

**Review by hqhq — APPROVED** [review]

**Comment by hqhq** [comment]
LGTM

**Review by AkihiroSuda — APPROVED** [review]
👍

**Review by thaJeztah — APPROVED** [review]
thanks! happy to help within my capabilities

LGTM

**Comment by thaJeztah** [comment]
(also wondering if the "chief maintainer" part is still relevant; didn't know it was still in there)

**Comment by cyphar** [comment]
The chief maintainer concept is something that's been on paper in the rules but hasn't actually applied in practice. I planned to rework the governance documents after we did 1.0 to better match how the runc maintenance rules work in practice (as well as redesigning how we do releases), but I didn't get around to it.

**Review by cyphar — APPROVED** [review]
LGTM.

**Comment by kolyshkin** [comment]
I've seen some other project[s] remove the concept of the chief maintainer (don't remember where, but maybe it was some containerd or moby project? can't find it now). I guess we should do that, too.

**Review by mrunalp — APPROVED** [review]
LGTM

**Comment by kolyshkin** [comment]
Wow, we have the required votes already, that was fast! 

Still have to wait until the voting period is over (middle of next week) to see if there's any objections, unless everyone votes before that.

**Comment by TomSweeneyRedHat** [comment]
LGTM
I'm not a voter, but an excellent choice

**Comment by thaJeztah** [comment]
> Still have to wait until the voting period is over (middle of next week) to see if there's any objections, unless everyone votes before that.

_/me heads out to the shop to buy cupcakes to bribe the remaining voters_ 😂

**Comment by dims** [comment]
woohooo! +100 to @thaJeztah (Not Binding!)

**Review by crosbymichael — APPROVED** [review]

**Comment by crosbymichael** [comment]
@cyphar @thaJeztah Yep, there is no chief maintainer anymore and something that I don't believe in either as maintainership is earned by doing. Just a relic of the past, we can remove it :)

**Review by dqminh — APPROVED** [review]

**Comment by dqminh** [comment]
LGTM :tada:

**Comment by kolyshkin** [comment]
> _/me heads out to the shop to buy cupcakes to bribe the remaining voters_

Looks like the plan worked perfectly 😉 🎉

**Pull request merged**
