### PR TITLE
add test case with create existed container

### PR DESCRIPTION
**Pull request by chchliang**
Signed-off-by: chchliang <chen.chuanliang@zte.com.cn>

### CODE REVIEW

**Comment by cyphar** [comment]
Hi, thanks for your contribution! Did you also want to create an integration test for this (in `tests/`)?

**Comment by chchliang** [comment]
@cyphar 
Here is unit test with container id have existed,i think unnecessary add an integration test,thanks.

**Comment by crosbymichael** [comment]
LGTM

**Comment by AkihiroSuda** [comment]
LGTM, but could you rebase and force push to trigger CI again?
Also, please sign the commit with your full name.

**Comment by AkihiroSuda** [comment]
ping @chchliang

**Comment by kolyshkin** [comment]
The code has changed a lot since this PR was created, so let's close this one.

@chchliang if you want to work on this, please create a new PR, and add the test in libcontainer/integration

**Pull request closed without merging**
