### PR TITLE
Replace github.com/codegangsta/cli by github.com/urfave/cli

### PR DESCRIPTION
**Pull request by mrunalp**
The package got moved to a different repository

Signed-off-by: Mrunal Patel <mpatel@redhat.com>

### CODE REVIEW

**Comment by dqminh** [comment]
ah ugly :(

LGTM

**Comment by wking** [comment]
Is the new library a drop-in replacement (with just extensions?).  I
hadn't checked for backwards-imcompatable changes.

**Comment by cyphar** [comment]
LGTM

**Comment by mrunalp** [comment]
@wking From the README
```
Notice: This is the library formerly known as github.com/codegangsta/cli -- Github will automatically redirect requests to this repository, but we recommend updating your references for clarity.
```

**Comment by wking** [comment]
On Mon, Jun 06, 2016 at 12:00:27PM -0700, Mrunal Patel wrote:
> @wking From the README
> ```
> Notice: This is the library formerly known as
> github.com/codegangsta/cli -- Github will automatically redirect
> requests to this repository, but we recommend updating your
> references for clarity.
> ```

Ok, that sounds close enough to “we're backwards compatible” to me ;).

**Comment by cyphar** [comment]
LGTM. If someone pulls the code it'll forward to this repo anyway.

**Comment by hqhq** [comment]
Docker is replacing cli with [cobra](https://github.com/spf13/cobra), should we consider to do this as well in runc if it's really some improvement? Haven't got time to look into it...

**Comment by mrunalp** [comment]
@hqhq Moving to a different cli could be discussed separately. This is just to update references as the repo we are using moved to a different location.

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
