### PR TITLE
epbf: update github.com/cilium/ebpf

### LINKED ISSUE #2316: s390x cgroupv2 runc error
@AkihiroSuda @giuseppe @kolyshkin 

Using the latest upstream kernel and runc. s390x could not start runc with cgroupv2.

runc spec
runc run root

WARN[0001] signal: killed                               
ERRO[0001] container_linux.go:349: starting container process caused "process_linux.go:439: container init caused \"process_linux.go:405: setting cgroup config for procHooks process caused \\\"error while setting cgroup v2: [can't load program:\\\\n    github.com/cilium/ebpf.newProgramWithBTF\\\\n        /root/go/pkg/mod/github.com/cilium/ebpf@v0.0.0-20200319110858-a7172c01168f/prog.go:151\\\\n  - permission denied: 0: (69) r1 = *(u16 *)(r2 +0)\\\\nR2 !read_ok\\\\nprocessed 1 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0]\\\"\"" 
container_linux.go:349: starting container process caused "process_linux.go:439: container init caused \"process_linux.go:405: setting cgroup config for procHooks process caused \\\"error while setting cgroup v2: [can't load program:\\\\n    github.com/cilium/ebpf.newProgramWithBTF\\\\n        /root/go/pkg/mod/github.com/cilium/ebpf@v0.0.0-20200319110858-a7172c01168f/prog.go:151\\\\n  - permission denied: 0: (69) r1 = *(u16 *)(r2 +0)\\\\nR2 !read_ok\\\\nprocessed 1 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0]\\\"\""

### PR DESCRIPTION
**Pull request by alicefr**
Update ebpf to include PR https://github.com/cilium/ebpf/pull/91.
The update is needed to fix #2316.

Signed-off-by: Alice Frosi <afrosi@de.ibm.com>

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
LGTM, do you need to update the code in `libcontainer/cgroups/ebpf/devicefilter` as well, or is this PR enough to fix the issue?

**Comment by alicefr** [comment]
@AkihiroSuda no we don't need to update the `libcontainer/cgroups/ebpf/devicefilter`. The ebpf package  was generating the wrong position for the registers. Of couse you need also the PR #2381 . There are 2 bugs actually. Using the latest bug + #2389 + #2381, I am able to run runc correctly:
```sh
$ uname -rm
5.5.17-200.fc31.s390x s390x
$ git log --pretty=oneline --abbrev-commit -4
4b125793 (HEAD -> upstrea_master) epbf: update github.com/cilium/ebpf
41b94ae8 test: update devicefilter tests
5364987a ebpf: fix big endian issue for s390x
2b31437c (origin/master, origin/HEAD) Merge pull request #2281 from AkihiroSuda/rootless-systemd
$ ./runc run --bundle test-runc test
/ # 
```
@cailca might confirm that the 2 PRs solve his issue

**Comment by cyphar** [comment]
Would you mind just pushing this change in #2381, rather than having it be a separate PR? But LGTM otherwise.

**Comment by alicefr** [comment]
@cyphar yes, I can

**Comment by alicefr** [comment]
Merged this PR with  #2381

**Pull request closed without merging**
