### PR TITLE
update to use pointer fields by following the spec

### PR DESCRIPTION
**Pull request by chanwit**
The `spec` has been recently updated to use `*uint64`, `*string` and `*uint16`. This PR updates related codes in `runc` accordingly.

Signed-off-by: Chanwit Kaewkasi <chanwit@gmail.com>

### CODE REVIEW

**Comment by runcom** [comment]
was working on the same thing :) thanks!

**Comment by chanwit** [comment]
@runcom No problem. The `spec` changes just has bit me :)

**Comment by chanwit** [comment]
janky is broken somehow. :-(

**Comment by cyphar** [comment]
@chanwit You need to update the `godep` revision used.

**Comment by chanwit** [comment]
Everything seems to be working now.

kindly ping @crosbymichael @cyphar @runcom

**Comment by crosbymichael** [comment]
Something is broken on my system with this change.  I'll try to look into the error and see what is going on but it seems to be something around the cgroup changes and cpuset.

```
runc start
WARN[0000] signal: killed                               
FATA[0000] Container start failed: [9] System error: write /sys/fs/cgroup/cpuset/user.slice/user-1000.slice/session-c2.scope/redis/cgroup.procs: no space left on device 
```

**Comment by mrunalp** [comment]
Needs rebase.

**Comment by crosbymichael** [comment]
This will be updated when we bump to spec version v.3.  Thanks for the PR.

**Pull request closed without merging**
