### PR TITLE
keyring: update key expiries

### PR DESCRIPTION
**Pull request by cyphar**
```
gpg --quick-set-expire C9C370B246B09F6DBCFC744C34401015D1D2D386 2030-03-25 '*'
```

Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>

### CODE REVIEW

**Comment by cyphar** [comment]
@AkihiroSuda Your key expired last year -- did you want to update your key to fix this?

```
pub   rsa3072 2019-07-25 [SC] [expires: 2023-11-02]
      C020EA876CE4E06C7AB95AEF49524C6F9F638F1A
uid           [ultimate] Akihiro Suda <akihiro.suda.cz@hco.ntt.co.jp>
uid           [ultimate] Akihiro Suda <suda.kyoto@gmail.com>
sub   rsa3072 2019-07-25 [E] [expires: 2023-11-02]
```

**Comment by AkihiroSuda** [comment]
> @AkihiroSuda Your key expired last year -- did you want to update your key to fix this?
> 
> ```
> pub   rsa3072 2019-07-25 [SC] [expires: 2023-11-02]
>       C020EA876CE4E06C7AB95AEF49524C6F9F638F1A
> uid           [ultimate] Akihiro Suda <akihiro.suda.cz@hco.ntt.co.jp>
> uid           [ultimate] Akihiro Suda <suda.kyoto@gmail.com>
> sub   rsa3072 2019-07-25 [E] [expires: 2023-11-02]
> ```

Updated: https://github.com/AkihiroSuda.gpg `[expires: 2025-07-27]`

**Comment by cyphar** [comment]
@AkihiroSuda Done.

**Review by AkihiroSuda — APPROVED** [review]
Thanks for updating mine as well

**Review by lifubang — APPROVED** [review]

**Comment by kolyshkin** [comment]
1.1 backport: #4177

**Pull request merged**
