### PR TITLE
Fix integration test for events

### PR DESCRIPTION
**Pull request by hqhq**
Signed-off-by: Qiang Huang <h.huangqiang@huawei.com>

### CODE REVIEW

**Comment by hqhq** [comment]
We missed this in https://github.com/opencontainers/runc/pull/780 , we should add integration test to CI, @crosbymichael @mrunalp anyone can do that?

**Comment by cyphar** [comment]
@hqhq #783 will enable the integration for all `make test` runs.

**Comment by crosbymichael** [comment]
LGTM

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
