### PR TITLE
Enable dependabot

### PR DESCRIPTION
**Pull request by kolyshkin**
This should enable a bot that auto-creates PRs to update dependencies.

For more info, see
https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically

Once enabled, dependabot work should be seen at
https://github.com/opencontainers/runc/network/updates
(as well as new PRs).

For a demo, see
* https://github.com/kolyshkin/runc/pulls?q=is%3Apr+label%3Adependencies (PRs opened by dependabot)
* https://github.com/kolyshkin/runc/network/updates (raw dependabot logs)

[v2: disable urlfave/cli updates]

Signed-off-by: Kir Kolyshkin <kolyshkin@gmail.com>

### CODE REVIEW

**Comment by kolyshkin** [comment]
This is how it would look like:
* https://github.com/kolyshkin/runc/network/updates
* https://github.com/kolyshkin/runc/pulls

**Comment by thaJeztah** [comment]
Wondering if it has a config to open pull requests from a fork, instead of pushing branches to the main repository (also: is it ok to have a bot do a DCO sign-off?)

**Comment by kolyshkin** [comment]
> Wondering if it has a config to open pull requests from a fork, instead of pushing branches to the main repository

Apparently not :( but the branches it create are very distinguishable (e.g. `bd38dependabot/go_modules/github.com/urfave/cli-1.22.5`

> (also: is it ok to have a bot do a DCO sign-off?)

As long as that bot won't sue you in court later I think we're good :trollface:

On a more serious note, this is a very minor change which by no means should be considered IP or be copyrightable.

**Comment by kolyshkin** [comment]
> > Wondering if it has a config to open pull requests from a fork, instead of pushing branches to the main repository
> 
> Apparently not :( but the branches it create are very distinguishable (e.g. `bd38dependabot/go_modules/github.com/urfave/cli-1.22.5`

It looks like it also auto-deletes those branches when a PR is merged or closed (see https://github.com/kolyshkin/runc/pull/16 and https://github.com/kolyshkin/runc/pull/13)

**Review by AkihiroSuda — APPROVED** [review]

**Review by cyphar — APPROVED** [review]
LGTM.

**Pull request closed without merging**
