### PR TITLE
Protect against blocked fifo when parent exits early

### PR DESCRIPTION
**Pull request by robbmanes**
In the rare case the parent runc process that execs the "runc init"
exits early for any reason, make sure we do not block on opening
the fifo pipe forever.

Fixes https://github.com/opencontainers/runc/issues/2586

Signed-off-by: Robb Manes <robbmanes@protonmail.com>

### CODE REVIEW

**Comment by cyphar** [comment]
NACK. `runc` has two separate stages -- "create" and "start". The FIFO is used to block the container from starting after `create` is done until `start` is called. The intention is to allow arbitrary user scripts to modify the container state before the container process starts. Adding a 10-second timeout would break this.

A nicer solution might be to have some way for the init process to indicate that it is done with setup and that the container should start waiting for the `start` signal (otherwise, exit).

**Comment by robbmanes** [comment]
Understood, thanks for the review and explanation.

**Comment by kolyshkin** [comment]
From `fifo(7)`:

>      When a process tries to write to a FIFO that is not opened for read
>       on the other side, the process is sent a SIGPIPE signal.

The default SIGPIPE handler aborts the program, and it doesn't look like it's changed, so apparently we're not getting SIGPIPE. Is this because we set up a custom handler?

Looking...

**Comment by cyphar** [comment]
@kolyshkin We don't try to write to the FIFO -- the end-stage of `runc init` is trying to open the FIFO with `O_RDONLY`. This blocks until someone else opens it for writing. The issue is (as far as I understand) that the other half of `runc init` dies or has a non-zero exit code, leading to the process sticking around.

@robbmanes When this happens, does the container show up in `runc list`? Can you `runc kill` it?

**Comment by robbmanes** [comment]
> @robbmanes When this happens, does the container show up in `runc list`? Can you `runc kill` it?

Yes on both counts; it appears in `runc list` and is killable with `runc kill`.  That's how we currently are working around this at the moment; scripts that check for long-lived `runc init` processes and kills them with `runc kill`.

Also noting we don't know exactly the scenario where the parent is removed early or why in this particular instance, but I don't think it necessarily matters for this scenario we're describing.  Thanks!

**Comment by robbmanes** [comment]
This was explained to me a bit more by a peer.

So in this case, it appears the container engine in question is *likely* failing to issue `runc start` entirely (or it is prematurely exiting); specifically, we're using the `cri-o` runtime, so https://github.com/cri-o/cri-o/pull/4198 resolves a problem in `cri-o` where upon container creation failure we appropriately end the `runc init` processes as we do not issue `runc start` to them (specifically commit https://github.com/cri-o/cri-o/pull/4198/commits/b8dc2878a608a26145101d91678928ea742514ee).

I am not sure there is a way to make `runc init` more resilient here then; it is blocking on the pipe, yes, but the container engine in question isn't appropriately issuing start and just lets it linger, so would we call that a misuse/error in use of `runc`?  I'd assume yes, so I am not sure there is anything to fix here.  Feedback on this appreciated, and sorry for the bad PR here in either scenario.  Thanks!

**Pull request closed without merging**
