### PR TITLE
update date in README

### PR DESCRIPTION
**Pull request by xlgao-zju**
update date in README from 2014 to 2015

Signed-off-by: xlgao-zju <xlgao@zju.edu.cn>

### CODE REVIEW

**Comment by crosbymichael** [comment]
LGTM

**Comment by hqhq** [comment]
LGTM

**Comment by thaJeztah** [comment]
I wonder if this is correct; perhaps it should be either 2014 (if that's the year the original code was written), or 2014-2016. But IANAL, so worth checking

**Comment by hqhq** [comment]
@thaJeztah Thanks, after some checking, I think you are right, according to https://softwarefreedom.org/resources/2012/ManagingCopyrightInformation.html

```
U.S. Copyright law wasn’t designed with free software in mind. Its model is the one-time or occasional publication of “editions” or installments of a work, not the near-constant publication of small changes to a publicly available work. Because of this, it’s difficult to generalize about what the copyrightable unit of a free software project or contribution is.
```

I think we should keep the copyright notification as it was. I'll revert it.

**Pull request merged**
