### PR TITLE
Bump x/sys and update syscall for initial Risc-V support

### PR DESCRIPTION
**Pull request by carlosedp**
Updating projects using libraries that were recently updated to support Risc-V architecture. This PR adds initial support so libraries that depend on opencontainers/runc build with no errors like Kubernetes and K3s.

Runc itself depends on cgo so it still can't be built.

Go upstream work is tracked on: golang/go#27532
Risc-V software support tracker on https://github.com/carlosedp/riscv-bringup

Signed-off-by: Carlos de Paula <me@carlosedp.com>

### CODE REVIEW

**Comment by crosbymichael** [comment]
LGTM

**Comment by carlosedp** [comment]
Bump... news on this @crosbymichael ?

**Comment by crosbymichael** [comment]
ping @opencontainers/runc-maintainers

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
