### PR TITLE
[1.1] cgroups: systemd: skip adding device paths that don't exist

### PR DESCRIPTION
**Pull request by cyphar**
Backport of #3498.

Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>

### CODE REVIEW

**Review by kolyshkin — APPROVED** [review]
LGTM given that CI is green

**Comment by kolyshkin** [comment]
@thaJeztah @AkihiroSuda PTAL

**Review by kolyshkin — APPROVED** [review]
LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM

**Pull request merged**
