### PR TITLE
Update to version 0.1.0

### PR DESCRIPTION
**Pull request by crosbymichael**
This also bumps the spec to v0.5.0 with the release of runc 0.1.0

### CODE REVIEW

**Comment by wking** [comment]
On Tue, Apr 12, 2016 at 01:37:20PM -0700, Michael Crosby wrote:
>     M Godeps/_workspace/src/github.com/opencontainers/specs/specs-go/version.go (2)

You probably want to update this to follow the ‘specs’ →
‘runtime-spec’ rename [1].

[1]: https://github.com/opencontainers/runtime-spec/blob/v0.5.0/ChangeLog#L6-L7

**Comment by crosbymichael** [comment]
@wking fixed

**Comment by tianon** [comment]
LGTM :heart:

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
