### PR TITLE
add spec file for RPM building

### PR DESCRIPTION
**Pull request by InformatiQ**

### CODE REVIEW

**Comment by jfrazelle** [comment]
If we add this I would like it to work / be structured the same way as in docker, but that's just my opinion

**Comment by mrunalp** [comment]
I agree with @jfrazelle

**Comment by InformatiQ** [comment]
@jfrazelle what is the docker structure? 
link!

**Comment by jfrazelle** [comment]
so the addition of the spec file is great :)

We also need to add the scripts for building and such, like https://github.com/docker/docker/blob/master/hack/make/build-rpm which I can work on, then we can add this as a package in our yum repository.

**Comment by InformatiQ** [comment]
so the plan is to replicate the make.sh tree from docker in runc

**Comment by jfrazelle** [comment]
In hopefully the most minimal way, I'll try to work on it some

**Comment by InformatiQ** [comment]
should i remove the Makefile changes out of this PR
and I can start working on the make.sh structure in a second one

**Comment by jfrazelle** [comment]
SGTM thanks !

**Comment by whosthatknocking** [comment]
I use a very similar [spec](https://gist.github.com/whosthatknocking/151b4bbaa65416bce5b1) file. It would be nice to follow tags for any major milestones.

**Comment by markllama** [comment]
Does it make sense also to include a `%package devel` and place the sources in `%{gopath}/github.com/opencontainers/runc` ?

**Comment by markllama** [comment]
runc is simple enough that I'm not sure it needs more than the existing Makefile.  It certainly doesn't need a complex build/install process.

**Comment by lsm5** [comment]
@markllama if it's to be included in vanilla Fedora it would have its own process, but ya, for inclusion in runC's own yum repos that are not a part of Fedora, up to the maintainers to decide :)

**Pull request closed without merging**
