### PR TITLE
Update github.com/opencontainers/specs to a7b50925d8996923d99e

### PR DESCRIPTION
**Pull request by mrunalp**
This leaves out the internal conversions as we may need to consider
docker backward compatibility for those changes.

Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by mrunalp** [comment]
@crosbymichael @LK4D4 @hqhq ping

**Comment by hqhq** [comment]
@mrunalp Don't we want to change fields in `Resources` to be pointer as specs defined? I think that's the point we use pointers in specs.

Or are you planning to do this in a following-up PR?

**Comment by mrunalp** [comment]
@hqhq Yes, I think we can do those changes in a follow up.

**Comment by hqhq** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
