### PR TITLE
Fix the value corresponding to rlimitmap [key]

### PR DESCRIPTION
**Pull request by wanghuaiqing2010**
These values depend on the specific arch

Signed-off-by: wanghuaiqing <wanghuaiqing@loongson.cn>

### CODE REVIEW

**Comment by wanghuaiqing2010** [comment]
@allencloud  could you help review the request.

Test on X86

[root@centos7-x86 ~]# docker run -it --ulimit nofile=42 busybox /bin/ash
/ #
/ # ps -a
PID USER TIME COMMAND
1 root 0:00 /bin/ash
13 root 0:00 ps -a
/ #
/ #
/ # cat ./proc/1/limits
Limit Soft Limit Hard Limit Units
Max cpu time unlimited unlimited seconds
Max file size unlimited unlimited bytes
Max data size unlimited unlimited bytes
Max stack size 8388608 unlimited bytes
Max core file size unlimited unlimited bytes
Max resident set unlimited unlimited bytes
Max processes unlimited unlimited processes
Max open files 42 42 files                    ====>Correctly set this to 42 
Max locked memory 65536 65536 bytes
Max address space unlimited unlimited bytes
Max file locks unlimited unlimited locks
Max pending signals 256401 256401 signals
Max msgqueue size 819200 819200 bytes
Max nice priority 0 0
Max realtime priority 0 0
Max realtime timeout unlimited unlimited us
/ #
/ #

Test on mips

[root@localhost ~]# docker run -it --ulimit nofile=42 loongnix/busybox ash
/ #
/ #
/ # cat /proc/1/limits
Limit Soft Limit Hard Limit Units
Max cpu time unlimited unlimited seconds
Max file size unlimited unlimited bytes
Max data size unlimited unlimited bytes
Max stack size 8388608 unlimited bytes
Max core file size unlimited unlimited bytes
Max open files 1048576 1048576 files
Max address space unlimited unlimited bytes
Max resident set 42 42 bytes                  ====》Incorrectly set this to 42
Max processes unlimited unlimited processes
Max locked memory 65536 65536 bytes
Max file locks unlimited unlimited locks
Max pending signals 29987 29987 signals
Max msgqueue size 819200 819200 bytes
Max nice priority 0 0
Max realtime priority 0 0
Max realtime timeout unlimited unlimited us



The error on mips is caused by the following reasons.

RLIMIT_NOFILE is 7 on x86
RLIMIT_NOFILE is 5 on mips64el
RLIMIT_RSS  is 5 on x86
RLIMIT_RSS  is 7 on mips64el

The value of RLIMIT_NOFILE is not a const value,
It depends on the arch.

**Comment by wanghuaiqing2010** [comment]
@ adrianreber Could you help me review the request

**Comment by hqhq** [comment]
LGTM

**Comment by wanghuaiqing2010** [comment]
@hqhq Thank you for your review.

**Comment by wanghuaiqing2010** [comment]
@all Could other reviewers help me review the code？

**Comment by cyphar** [comment]
LGTM.

**Comment by cyphar** [comment]
Please don't request reviews from a bunch of people (*especially* people who are unrelated to `runc`) -- it just ends up looking like spam.

**Pull request closed without merging**
