### PR TITLE
nsenter: fix leaking unused log fd used for early bootstrap

### PR DESCRIPTION
**Pull request by jiazhang0**
Signed-off-by: Jia Zhang <zhang.jia@linux.alibaba.com>

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
Could you rebase and push to  retrigger CI?

**Comment by AkihiroSuda** [comment]
LGTM if green

**Comment by jiazhang0** [comment]
> LGTM if green
> 
> [Approved with PullApprove](https://pullapprove.com/opencontainers/runc/pull-request/2202/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=opencontainers/runc)

Pushed.

**Comment by AkihiroSuda** [comment]
LGTM

**Comment by jiazhang0** [comment]
It looks like this log fd is still useful for runc init process after bootstrap. Sorry I missed it. Closed.

**Pull request closed without merging**
