### PR TITLE
adding go get instruction to readme

### PR DESCRIPTION
**Pull request by vsoch**
Trying this again... so very hard...

Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

### CODE REVIEW

**Comment by crosbymichael** [comment]
LGTM

**Comment by vsoch** [comment]
Silly question - do you know how to change the automatic signature? Mine automatically appears like this when I add the `-s` to the commit:

```
Signed-off-by: vsoch <vsochat@stanford.edu>
```
And Google searching, as is the case with anything with "Github" returns a bunch of Github repositories that don't answer my question. The closest I figured out was that it has something to do with the GPG key documentation, and I am guessing that there is a setting somewhere that needs to be edited, although I didn't find it. I'm also happy to sign and then amend the commit to make it have my full name. What is your strategy?

**Comment by crosbymichael** [comment]
@vsoch it should be in your gitconfig

https://github.com/crosbymichael/.dotfiles/blob/master/gitconfig#L1

**Comment by vsoch** [comment]
Beautiful! Thank you @crosbymichael

**Comment by hqhq** [comment]
LGTM

**Pull request merged**
