### PR TITLE
Add annotations to list and state output

### PR DESCRIPTION
**Pull request by crosbymichael**
Signed-off-by: Michael Crosby <crosbymichael@gmail.com>

### CODE REVIEW

**Comment by duglin** [comment]
For reference, I'm assuming this is related to, and trying to address, https://github.com/opencontainers/runtime-spec/issues/480
Thanks - I think that helps.

**Comment by crosbymichael** [comment]
uhh, yes, i totally did this for that ;)

**Comment by duglin** [comment]
don't burst my bubble

**Comment by mrunalp** [comment]
LGTM

**Comment by dqminh** [comment]
LGTM

**Pull request merged**
