### PR TITLE
Update criu_opts_linux.go

### PR DESCRIPTION
**Pull request by allencloud**
fix a typo.

### CODE REVIEW

**Comment by cyphar** [comment]
You need to add a `Signed-off-by:` line to your commit(s) which indicates that you attest the [Developer Certificate of Origin](https://developercertificate.org/) a statement about your contributions that you *must read* before signing (don't worry, it's quite short and easy-to-read). You can add it to your commits with `git commit --amend -s`, and then doing a `git push --force`.

**Comment by allencloud** [comment]
OK, I will try that. Since I update this directly on github.

**Comment by allencloud** [comment]
Any update?

**Comment by hqhq** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
