### PR TITLE
selinux: add SelinuxSetEnforceMode implementation

### PR DESCRIPTION
**Pull request by ahmetalpbalkan**
Adding `setenforce` implementation and updated tests.

### CODE REVIEW

**Comment by mrunalp** [comment]
@rhatdan PTAL

**Comment by rhatdan** [comment]
LGTM, but not sure why it is important.

**Comment by ahmetalpbalkan** [comment]
@rhatdan I'm trying to use the package in another project, it's quite useful. :-)

**Comment by ahmetalpbalkan** [comment]
(jenkins seemed to  be busted, so I amended the commit with a new number and pushed again)

**Comment by mrunalp** [comment]
LGTM

**Comment by rhatdan** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
