### PR TITLE
Cleanup Godeps

### PR DESCRIPTION
**Pull request by hqhq**
`godep save` and `godep update` don't copy `*_test.go` files and
`testdata` directories by default, and we have no reason to keep
them in Godeps.

This is what I did:
1. A clean GOPATH with no vendors in
2. godep restore
3. remove Godeps dir in the repo
4. godep save

Note that I'm using the latest godep, so we also vendored all
necessary licese files because of https://github.com/tools/godep/pul/301

Signed-off-by: Qiang Huang <h.huangqiang@huawei.com>

### CODE REVIEW

**Comment by hqhq** [comment]
ping @mrunalp @crosbymichael @LK4D4

**Comment by dqminh** [comment]
LGTM

**Comment by mrunalp** [comment]
When we update the package in Godeps, won't the test files be pulled in again?

**Comment by LK4D4** [comment]
@mrunalp I think godep deletes them.
LGTM

**Comment by mrunalp** [comment]
@LK4D4 thanks! LGTM

**Pull request merged**
