### PR TITLE
remove deadcode

### PR DESCRIPTION
**Pull request by jfrazelle**
Signed-off-by: Jessica Frazelle <acidburn@docker.com>

### CODE REVIEW

**Comment by marcosnils** [comment]
@jfrazelle is this the result of `unused`?

**Comment by jfrazelle** [comment]
https://github.com/remyoudompheng/go-misc/tree/master/deadcode
and
https://github.com/gordonklaus/ineffassign/blob/master/list :)

On Thu, Mar 17, 2016 at 1:34 PM, Marcos Nils <notifications@github.com>
wrote:

> @jfrazelle <https://github.com/jfrazelle> is this the result of unused?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/opencontainers/runc/pull/653#issuecomment-198070220>
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by jfrazelle** [comment]
pretty cool right

On Thu, Mar 17, 2016 at 1:37 PM, Jessica Frazelle <me@jessfraz.com> wrote:

> https://github.com/remyoudompheng/go-misc/tree/master/deadcode
> and
> https://github.com/gordonklaus/ineffassign/blob/master/list :)
>
> On Thu, Mar 17, 2016 at 1:34 PM, Marcos Nils <notifications@github.com>
> wrote:
>
>> @jfrazelle <https://github.com/jfrazelle> is this the result of unused?
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/opencontainers/runc/pull/653#issuecomment-198070220>
>>
>
>
>
> --
>
>
> Jessie Frazelle
> 4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
> pgp.mit.edu
> <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by jfrazelle** [comment]
There are some build tag related bugs so it needs a bit of a manual touch
but nice

On Thu, Mar 17, 2016 at 1:37 PM, Jessica Frazelle <me@jessfraz.com> wrote:

> pretty cool right
>
> On Thu, Mar 17, 2016 at 1:37 PM, Jessica Frazelle <me@jessfraz.com> wrote:
>
>> https://github.com/remyoudompheng/go-misc/tree/master/deadcode
>> and
>> https://github.com/gordonklaus/ineffassign/blob/master/list :)
>>
>> On Thu, Mar 17, 2016 at 1:34 PM, Marcos Nils <notifications@github.com>
>> wrote:
>>
>>> @jfrazelle <https://github.com/jfrazelle> is this the result of unused?
>>>
>>> —
>>> You are receiving this because you were mentioned.
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/opencontainers/runc/pull/653#issuecomment-198070220>
>>>
>>
>>
>>
>> --
>>
>>
>> Jessie Frazelle
>> 4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
>> pgp.mit.edu
>> <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>
>>
>
>
>
> --
>
>
> Jessie Frazelle
> 4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
> pgp.mit.edu
> <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by marcosnils** [comment]
@jfrazelle I wondered if you were using this instead: https://github.com/dominikh/go-unused

**Comment by jfrazelle** [comment]
Ah neat!

On Thu, Mar 17, 2016 at 1:43 PM, Marcos Nils <notifications@github.com>
wrote:

> @jfrazelle <https://github.com/jfrazelle> I wondered if you were using
> this instead: https://github.com/dominikh/go-unused
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/opencontainers/runc/pull/653#issuecomment-198074630>
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by crosbymichael** [comment]
LGTM

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
