### PR TITLE
Windows: Remove nsenter dependency

### PR DESCRIPTION
**Pull request by jhowardmsft**
Signed-off-by: John Howard <jhoward@microsoft.com>

Removes the dependency of nsenter on Windows.

### CODE REVIEW

**Comment by mrunalp** [comment]
This should also use linux instead of !windows.

**Comment by jhowardmsft** [comment]
Yup. Updated.

**Comment by LK4D4** [comment]
LGTM

**Comment by wking** [comment]
On Fri, Jun 26, 2015 at 06:17:32PM -0700, John Howard (Microsoft) wrote:
>     M main.go (1)
>     A main_unix.go (5)

I was just poking around to see if/how nsenter was wired up, and it
looks like libcontainer/nsenter/nsenter_unsupported.go was intended to
catch cases like this.  For example see 22eb88ec (Fix nsenter package
on unsupported platforms, 2015-05-2015).  I think we should get the
nsenter_unsupported.go approach working (I'm not sure why it was
broken on Windows) and drop main_unix.go.  That seems to scale better
in the face of a number of nsenter consumers, since whether nsenter
works on a given platform is something that the nsenter devs should
know well, but may not necessarily be something that nsenter consumers
care about.

**Pull request merged**
