### PR TITLE
Adds support for System Properties.

### PR DESCRIPTION
**Pull request by mrunalp**
Replaces #7 
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by mrunalp** [comment]
@LK4D4 @crosbymichael PTAL

**Comment by LK4D4** [comment]
Heh, we need CI and tests :)

**Comment by mrunalp** [comment]
Yes, very soon :)

**Comment by mrunalp** [comment]
Closing in favor of #73

**Pull request closed without merging**
