### PR TITLE
remove `-i` option to avoid failure of jenkins in non-interactive mode.

### PR DESCRIPTION
**Pull request by FengtuWang**
Signed-off-by: Fengtu Wang <wangfengtu@huawei.com>

### CODE REVIEW

**Comment by FengtuWang** [comment]
Use `make test` in jenkins cause `cannot enable tty mode on non tty input`. It seems that this option is not needed here.

**Comment by FengtuWang** [comment]
My jenkins can't run an interactive shell.So when i use 'make test' command in jenkins's shell, it print error message 'cannot enable tty mode on non tty input' as '-i' option can only used in an interactive environment. Jenkins in our upstream CI didn't have such problem because it didn't use 'make test' command in the shell. It use 'docker run' command directly instand, no option '-i' as well. Maybe someone's jenkins can resolve such problem by some plugins, but not mine. As this option seems no use, i'd like to remove it.

**Comment by FengtuWang** [comment]
I think we should keep '-i' option in  'make shell' command. This command seems to be designed for interactive situation, because it just start a container and enter bash. Other commands should be input manually.

**Comment by hqhq** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
