### PR TITLE
Add -q to list to print only container IDs

### PR DESCRIPTION
**Pull request by mrunalp**
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by hqhq** [comment]
Maybe update man page as well?

**Comment by laijs** [comment]
Since it has the `--format` (`-f), I think we can make it as one of the format
like this: `--format quiet`  or `--format container-id-only`

**Comment by mikebrow** [comment]
Looks good to me.

**Comment by mrunalp** [comment]
Updated man page.

**Comment by mrunalp** [comment]
@laijs I think typically commands have a separate `quiet` option so I like it better than adding this to quiet. Also format with specific headers is different since it includes the header in the output whereas output of quiet excludes that and is convenient for processing.

**Comment by mrunalp** [comment]
@crosbymichael @LK4D4 PTAL

**Comment by LK4D4** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
