### PR TITLE
Revert "Remove sample configs from libcontainer"

### PR DESCRIPTION
**Pull request by mrunalp**
This should fix the tests as they are failing on sample configs missing.

Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by mrunalp** [comment]
@LK4D4 @crosbymichael PTAL
cc: @jfrazelle

**Comment by jfrazelle** [comment]
green!! \o/

**Comment by estesp** [comment]
yay :)

**Comment by crosbymichael** [comment]
shouldn't we updates the tests because we don't really care about the serialization and deserialization of this config?

**Comment by mrunalp** [comment]
@crosbymichael I can do that.

**Comment by mrunalp** [comment]
@crosbymichael Should we just remove those 3 tests?

**Comment by mrunalp** [comment]
Created #109 to remove the deserialization tests.

**Pull request closed without merging**
