### PR TITLE
Fix libcontainer's dependencies

### PR DESCRIPTION
**Pull request by gitido**
Runc vendors all of its dependencies, but obviously doesn't vendor
itself. As a result, when modules in libcontainer are imported, they are
resolved in GOPATH.

Fix this by simply adding a symlink from the vendored runc directory to
runc itself.

Signed-off-by: Ido Yariv <ido@wizery.com>

### CODE REVIEW

**Comment by crosbymichael** [comment]
@gitido there are a few test failures because of import paths.

**Comment by LK4D4** [comment]
And I don't understand change at all.

**Comment by crosbymichael** [comment]
@LK4D4 it's so u don't have to clone into your GOPATH, you can just `make` anywhere

**Comment by gitido** [comment]
I'm not sure about the test failures, will need to take a closer

**Comment by LK4D4** [comment]
But `/runc` in `.gitignore`?
And why we use vendoring tool which depends on GOPATH if we don't want to use GOPATH? And why you want to setup GOPATH and then run runc from other places?

**Comment by gitido** [comment]
@LK4D4 The /runc change in .gitignore is there so git will ignore the runc binary, but not the new symlink (if we just have 'runc' there, it'll ignore both).

If you git clone github.com/opencontainers/runc and then hit make, the build might break depending on whatever version you have in your GOPATH. If 'go get' would be used instead, that wouldn't be an issue, but then the build breaks because the internal GOPATH is only set by the makefile.

**Comment by marcosnils** [comment]
@gitido 
- `go git github.com/opencontainers/runc`
- `cd $GOPATH/src/github.com/opencontainers/runc`
- make

Do we want to simplify this?

**Comment by gitido** [comment]
@marcosnils this requires building in your GOPATH, which is fine, but not always desirable. This patch fixes the following:
* cd /tmp && git clone git://github.com/opencontainers/runc
* cd /tmp/runc
* make

**Comment by LK4D4** [comment]
@gitido But you should not have GOPATH in this case at all. And it won't work then with link or without.

**Comment by gitido** [comment]
@LK4D4 You must still have GOPATH set, but this will let you build runc anywhere, and not just in your GOPATH.
For instance, if you have runc cloned elsewhere (say, your private github fork, and not as another git remote), changing libcontainer in that copy will have no effect on the build, since it'll still use the files in your GOPATH.

This isn't an important PR, it's just something I ran into when working on the code. We can close and forget if you prefer (the former is already done) ;)

**Comment by hqhq** [comment]
@gitido I like this, `make` runc everywhere is pretty useful, but I don't think we should change `Godeps/` like this, it's generated automatically by godep, should not be edited.

I posted an new approach #328 , see if that's a better option.

**Pull request closed without merging**
