### PR TITLE
Add Andrey Vagin as maintainer

### PR DESCRIPTION
**Pull request by LK4D4**
This is PR to collect needed 66% of votes to make Andrey(@avagin) maintainer of opencontainers organization. He is one of the most prominent contributors to libcontainer and linux containers overall.
ping @crosbymichael @mrunalp @vmarmol @rjnagal @vishh @dqminh @philips @vbatts

### CODE REVIEW

**Comment by dqminh** [comment]
LGTM.

@avagin suggestions are always very helpful.

**Comment by vishh** [comment]
LGTM

**Comment by thaJeztah** [comment]
passers-by vote :+1:

**Comment by mrunalp** [comment]
LGTM. @avagin has made tremendous contributions to libcontainer/runc.

**Comment by avagin** [comment]
LGTM. Thank you all for the trust.

**Comment by crosbymichael** [comment]
LGTM

**Comment by thaJeztah** [comment]
Congrats, @avagin :tada:

**Pull request merged**
