### PR TITLE
Handle threaded cgroup types

### PR DESCRIPTION
**Pull request by Bacto**
Resolve https://github.com/opencontainers/runc/issues/3821

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
Can we have an integration test?

**Comment by AkihiroSuda** [comment]
> @AkihiroSuda what do you mean by integration test? 

These tests
https://github.com/opencontainers/runc/tree/main/tests/integration

> Should I do something on my side?

Yes, please.
Usually we expect an integration test to be accompanied with a bug fix so that we can catch potential regression in future.

**Comment by kolyshkin** [comment]
@Bacto please squash your commits.

**Comment by kolyshkin** [comment]
Rebased to latest HEAD to get CI fixes

**Comment by kolyshkin** [comment]
We still don't have the integration test :(

**Comment by kolyshkin** [comment]
So, I think the way the code should work is try to read cgroup.procs and if there's "operation not supported" error, switch to cgroup.threads. This way it is faster than reading an extra file (cgroup.type).

**Comment by kolyshkin** [comment]
There are couple of linter issues to be addressed as well.

**Comment by kolyshkin** [comment]
@Bacto please let us know if you want to keep working on this.

**Comment by kolyshkin** [comment]
As I said in #3821 (https://github.com/opencontainers/runc/issues/3821#issuecomment-2116470943), I think this is not a correct fix.

**Pull request closed without merging**
