### PR TITLE
io_v2.go: remove blkio v1 code

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Signed-off-by: Akihiro Suda <akihiro.suda.cz@hco.ntt.co.jp>

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
@giuseppe PTAL

**Comment by giuseppe** [comment]
LGTM

**Comment by rhatdan** [comment]
LGTM
@crosbymichael @mrunalp @cyphar PTAL

**Comment by crosbymichael** [comment]
LGTM

**Comment by dqminh** [comment]
LGTM

**Pull request merged**
