### PR TITLE
Fix absolute path getting for runc binary

### PR DESCRIPTION
**Pull request by LK4D4**
ping @estesp

### CODE REVIEW

**Comment by estesp** [comment]
Yes, this is more correct, and fixes issues/PRs noted in #35 and #36

**Comment by mrunalp** [comment]
Yes, I think this approach is better. Testing.

**Comment by mrunalp** [comment]
All 3 cases work:
1. Relative ./runc
2. Absolute /usr/bin/runc
3. From PATH runc

LGTM

**Comment by hitsumabushi** [comment]
:+1:
This pr is better than #36.

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
