### PR TITLE
[1.1] bump Fedora, Vagrant, bats

### PR DESCRIPTION
**Pull request by kolyshkin**
This is a backport of #3848, #3815 (modulo #3823) and #3880 to release-1.1 branch.

Purely CI changes here (F37->F38, newer Vagrant, newer bats, some test/int CI fixes).

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by kolyshkin** [comment]
Need to backport #3880 as well

**Comment by kolyshkin** [comment]
Draft until I add a backport of #3880.

**Comment by kolyshkin** [comment]
OK @opencontainers/runc-maintainers  this one is ready

**Review by AkihiroSuda — APPROVED** [review]

**Pull request merged**
