### PR TITLE
Container config verification for memory swap and cpu in unsupported kernels

### PR DESCRIPTION
**Pull request by rajasec**
This is different implementation for checking the memory swap when kernel is not supported. Earlier PR #249 had the implementation in libcontainer. As part of this PR, I've moved the logic to start.go.
When memory.memsw is not supported/enabled in kernel, this will give the warning message to user and gracefully start the container.

Signed-off-by: Rajasekaran <rajasec79@gmail.com>

### CODE REVIEW

**Comment by crosbymichael** [comment]
I don't think at this level we should give a warning and start anyways.  If you have a setting and u don't have the infrastructure to support it then we fail and they have to change the config.  I don't think it's runc's responsibility to check for things like this.  We should just try out best to fulfill what the user asked for.  

@mrunalp @LK4D4 what do you think?

**Comment by mrunalp** [comment]
@crosbymichael I agree

**Comment by rajasec** [comment]
@crosbymichael 
Thanks for the comment. When I tried to work with swap, I faced this problem.. Agree with your point, it should not be runc responsibility to handle the configs.
I saw similar behavior in Docker, where they gracefully start the container if swap is not enabled part of kernel configs. I thought similar fix could solve the problem for runc.

**Comment by crosbymichael** [comment]
@rajasec yes i understand.  It's the same thing in docker, we change the "config" at the docker level and libcontainer just tries to set the values as it is giving.  Thanks for the pr tough!

**Pull request closed without merging**
