### PR TITLE
checkpoint/restore commands support 'file-locks' option.

### PR DESCRIPTION
**Pull request by mapk0y**
Signed-off-by: mapk0y <mapk0y@gmail.com>

### CODE REVIEW

**Comment by mrunalp** [comment]
From http://criu.org/Advanced_usage#File_locks_C.2FR
```
Some app may use file locks for synchronization. Generally they will use flock or posix file locks, which 
were achieved by flock or fcntl system calls. For dump/restore, it is hard to be handled perfectly, because 
we can't guarantee all potential users are dumped for a specific file lock. Right now, we assume that all 
file lock users are taken into dump, and we should use the --file-locks option on both dump and restore 
stages if our app may use any file locks. Remember that file locks dump/restore is only safe for container 
dumping in theory.
```
@avagin Could you please review this?

**Comment by avagin** [comment]
LGTM

**Comment by mrunalp** [comment]
@avagin Thanks! LGTM

**Comment by mapk0y** [comment]
@avagin Thank you for supplements :smile:

**Pull request merged**
