### PR TITLE
Update runc with types from spec repository

### PR DESCRIPTION
**Pull request by crosbymichael**
This also does some general cleanup like removing the apparmor profile generation from libcontainer so that this can be done at a higher level and consumed by libcontainer.

### CODE REVIEW

**Comment by LK4D4** [comment]
Shouldn't we add `opencontainers/specs` to Godep?

**Comment by crosbymichael** [comment]
@LK4D4 done

**Comment by LK4D4** [comment]
LGTM
at least it compiles :)

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
