### PR TITLE
Allow + in container id

### PR DESCRIPTION
**Pull request by pankit**
Signed-off-by: pankit thapar <pankit@umich.edu>

### CODE REVIEW

**Comment by pankit** [comment]
@GordonTheTurtle Is this missing something? I have signed off this commit.
Let me know your feedback.

**Comment by pankit** [comment]
@crosbymichael @hqhq Can you please help me understand what is missing?

**Comment by marcosnils** [comment]
@pankit your commit can't be merged. You need to rebase with master in order to merge.

**Comment by pankit** [comment]
@marcosnils when I had sent the request, I had no conflicts. I am actually on a forked repo. Here: https://github.com/pankit/runc

**Pull request closed without merging**
