### PR TITLE
cli: migrate cli framework to "cobra" and "pflag"

### LINKED ISSUE #752: runc exec command parsing
Using runc exec fails when "container command" need an option.

For example : 

```
cmd="ls -l"
runc exec ${containerid} ${cmd}
```

gives

```
Incorrect Usage.

NAME:
   runc exec - execute new process inside the container

USAGE:
   runc exec [command options] <container-id> <container command>

Where "<container-id>" is the name for the instance of the container and
"<container command>" is the command to be executed in the container.

For example, if the container is configured to run the linux ps command the
following will output a list of processes running in the container:

       # runc exec <container-id> ps

OPTIONS:
   --console                    specify the pty slave path for use with the container
   --cwd                    current working directory in the container
   --env, -e [--env option --env option]    set environment variables
   --tty, -t                    allocate a pseudo-TTY
   --user, -u                   UID (format: <uid>[:<gid>])
   --process, -p                path to the process.json
   --detach, -d                 detach from the container's process
   --pid-file                   specify the file to write the process id to
   --process-label              set the asm process label for the process commonly used with selinux
   --apparmor                   set the apparmor profile for the process
   --no-new-privs               set the no new privileges value for the process
   --cap, -c [--cap option --cap option]    add a capability to the bounding set for the process
   --no-subreaper               disable the use of the subreaper used to reap reparented processes

flag provided but not defined: -l
```

### PR DESCRIPTION
**Pull request by forever043**
This PR migrate cli framework to [cobra](https://github.com/spf13/cobra) and [pflag](https://github.com/spf13/pflag), which can fix #752 and #788 more appropriately.

All codes related to the old framework are removed.

### CODE REVIEW

**Comment by hqhq** [comment]
@opencontainers/runc-maintainers Is this cobra cli idea sounds good to you? If yes, do you think we should do this step by step as this PR or do all substitution in one PR?

**Comment by cyphar** [comment]
I am +1 on using a different CLI library as long as it solves our problems with `--` handling (not to mention fixing `runc ps` so that it's actually useful). However, I think I would prefer doing the substitution in a single PR otherwise you end up with `master` having different CLI semantics for different subcommands (which is icky). But then again, the cost of doing a big PR is that nobody can track what's going on.

I do like the idea of just piggybacking on top of the existing framework and then removing the framework boilerplate once all of the conversions are done.

**Comment by crosbymichael** [comment]
+1 to what @cyphar said.  

@forever043 if you are interested in doing this and the rest of the maintainers think it is a good idea, we would want to make this change in one PR so that we are not using two cli packages at the same time.  

I think if you can split the commands into separate commits and have the ground work done in the fist commit it would be much easier for us to review when we make that change.  

Let me know what you think.

**Comment by forever043** [comment]
@crosbymichael got it! And I will do this :)

**Comment by hqhq** [comment]
This is a significant change we should include in 1.0, I'll add the milestone.

**Comment by cyphar** [comment]
We do want to release 1.0 at some point, right @hqhq? :wink:

**Comment by hqhq** [comment]
@cyphar Sure we do :wink: , let's focus on that and speed it up, I see the major block is your rootless container PRs, I'll review them once I can.

**Comment by cyphar** [comment]
I think we can delay rootless for 1.1.0, but we need to get console handling and nsenter fixed (from my view). Once those are fixed then rootless becomes a much smaller patchset.

**Comment by forever043** [comment]
hi all, @hqhq @cyphar @crosbymichael,
All commands are converted to cobra.
And I have to modify the 'runc foo -h' tests (		a2db5cf) because the error message is hard-coded in cobra.
Hope everything is ok :)

**Comment by hqhq** [comment]
@forever043 For a patchset, you must make sure it won't break bisect, which means it should be compileable and pass all test cases.

**Comment by cyphar** [comment]
Basically what @hqhq said. If your PR works in its current state, please rebase it to make sure that every commit builds and passes the tests (in other words, is bisectable).

**Comment by forever043** [comment]
@hqhq @cyphar, rebase finished, and every commit can build and pass the tests :)

**Comment by crosbymichael** [comment]
With the updated `cli` package fixing the `--` issues and arg parsing, is there a reason to write the entire cli on pflags and cobra?

**Comment by hqhq** [comment]
I don't know, but IIRC it's mentioned that there are bunch of advantages for cobra when docker choose it to replace the old cli package. @forever043 can you collect the advantages of cobra so we can decide if it's worth doing the replacement? Anyway it can be decided post-1.0.

**Comment by crosbymichael** [comment]
@hqhq well comparing docker's old cli package to cobra is an unfair comparison.  I think that gap is much closer when you compare cli vs cobra after this last update.

**Comment by crosbymichael** [comment]
Sorry that you did all this work but I think making the change does not benefit us that much and will just add code churn when its not needed.  The cli package was updated to handle `--` correctly and meets all our requirement.s

**Pull request closed without merging**
