### PR TITLE
typo fix

### PR DESCRIPTION
**Pull request by kennethlimcp**

### CODE REVIEW

**Comment by mrunalp** [comment]
Could you please squash the commits?

**Comment by kennethlimcp** [comment]
@mrunalp any clue on how to do that? I tried doing it but it failed. My first time trying to squash a commit :D

**Comment by LK4D4** [comment]
@kennethlimcp you should read about `git rebase -i` :)

**Comment by kennethlimcp** [comment]
@LK4D4 thanks! Managed to do it :D

**Comment by thaJeztah** [comment]
Changes LGTM (if the unrelated whitespace changes are not a problem)

Unfortunately, it looks like this needs another rebase :cry: (GitHub complains about merge conflicts)

**Comment by mrunalp** [comment]
Yep, this requires a rebase now.

**Comment by mrunalp** [comment]
@kennethlimcp You should fetch the latest from the master, rebase your branch onto it and resolve the merge conflicts and repush :)

**Comment by thaJeztah** [comment]
In case it's helpful; the Docker documentation also has some instructions on how to rebase; https://docs.docker.com/project/work-issue/ (section "Pull and rebase frequently")

**Comment by kennethlimcp** [comment]
Well someone changed and it was pulled - https://github.com/opencontainers/runc/commit/3ba8b5e706ebf342915fad79ee3d8c74dd6e0f5c

Shall just manually open another PR for the other fix then ;)

**Comment by thaJeztah** [comment]
thanks @kennethlimcp!

**Pull request closed without merging**
