### PR TITLE
Add VERSION file to contain the version info

### PR DESCRIPTION
**Pull request by hqhq**
We need this because we need to get version info out of
go code, eg. build rpm package.

Signed-off-by: Qiang Huang <h.huangqiang@huawei.com>

### CODE REVIEW

**Comment by cyphar** [comment]
I'm going to be honest. The way we autogenerate this at SUSE is that we have a [few shell scripts](https://github.com/SUSE/package_sync_github_build_service) that parse out the version from the `.go` files. ;)

This is a welcome improvement.

**Comment by cyphar** [comment]
LGTM

**Comment by mrunalp** [comment]
LGTM
@crosbymichael PTAL

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
