### PR TITLE
Add gitcommit to runc builds

### PR DESCRIPTION
**Pull request by crosbymichael**
Signed-off-by: Michael Crosby <crosbymichael@gmail.com>

### CODE REVIEW

**Comment by marcosnils** [comment]
@crosbymichael https://github.com/opencontainers/runc/pull/244#issuecomment-138417210 ?

**Comment by crosbymichael** [comment]
@marcosnils i honestly have no clue what is going on in that thread.  

I think it's good to have to git version compiled into the runc binary so that you know the exact commit that it was built from.  Its also very simple to do.

**Comment by mlaventure** [comment]
if git errors out, use "local" instead?

**Comment by crosbymichael** [comment]
i guess we can just remove that part if there is no git, that maybe the best outcome for everyone?

**Comment by crosbymichael** [comment]
Ok, i changed it to exclude the commit information if it cannot be retrieved, i.e. you don't have git or the git checkout.

**Comment by marcosnils** [comment]
@crosbymichael LGTM!

**Comment by crosbymichael** [comment]
@marcosnils thanks for the review

**Comment by mrunalp** [comment]
LGTM

**Comment by hqhq** [comment]
LGTM

**Pull request merged**
