### PR TITLE
VERSION: update to 1.0.0-rc9

### PR DESCRIPTION
**Pull request by cyphar**
Signed-off-by: Aleksa Sarai <asarai@suse.de>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Comment by hqhq** [comment]
LGTM

**Comment by cyphar** [comment]
Still waiting for one of @dqminh or @mrunalp to make the 2/3rd requirement (which we definitely need to drop once we 1.0 -- this is getting a little bit silly).

**Comment by mrunalp** [comment]
LGTM

**Comment by cyphar** [comment]
Good enough for me. :wink:

**Comment by mrunalp** [comment]
AFK so best I can do for now 🙂

**Pull request merged**
