### PR TITLE
Adding architecture to seccomp spec

### PR DESCRIPTION
**Pull request by rajasec**
@mheon @crosbymichael 

While I have added the architecture, it did not reflect in state.json file later as architecture was missing in the spec, I have added the architecture to spec and configs for parsing.

Later When I referred your PR, you have also mentioned it needs an PR. Was an coincident. : )

If you have already worked on this effort. I'll close this PR right way.

Signed-off-by: Rajasekaran <rajasec79@gmail.com>

### CODE REVIEW

**Comment by mheon** [comment]
See https://github.com/opencontainers/specs/pull/200

**Comment by rajasec** [comment]
@mheon 
I saw the PR. Thanks for notification. 
In addition to the spec, I have added in spec.go to parse and set as part of config..
is that already done ?

**Comment by mheon** [comment]
@rajasec Technically, there does need to be translation between the string constants understood by the libseccomp bindings, and the string constants listed in the spec. The bindings use more generic names like "AMD64" while the spec uses the libseccomp constants' names ("SCMP_ARCH_X86_64")

**Comment by rajasec** [comment]
@mheon 
As you are already working on, I'll close this PR. Thanks for your response.

**Pull request closed without merging**
