### PR TITLE
Fix kmem accouting when use with cgroupsPath

### PR DESCRIPTION
**Pull request by hqhq**
Fixes: #1347
Fixes: #1083

The root cause of #1083 is because we're joining an
existed cgroup whose kmem accouting is not initialized,
and it has child cgroup or tasks in it.

Fix it by checking if the cgroup is first time created,
and we should enable kmem accouting if the cgroup is
craeted by libcontainer with or without kmem limit
configed. Otherwise we'll get issue like #1347

Signed-off-by: Qiang Huang <h.huangqiang@huawei.com>

### CODE REVIEW

**Comment by hqhq** [comment]
ping @crosbymichael @mrunalp

**Comment by cyphar** [comment]
Hmm, this looks okay as a first step to fix that issue, but I'm a bit worried that this will break `runc update` (unless I'm misreading how the update code works).

**Comment by cyphar** [comment]
LGTM. I thought this would break the `runc update` code, but I was wrong.

**Comment by dqminh** [comment]
LGTM

**Comment by dqminh** [comment]
I assume the errors from rh-atomic-bot is because it was misconfigured ? Doesnt look like it does anything.

**Comment by cyphar** [comment]
I'm fairly sure that @rh-atomic-bot is broken because they didn't correctly script the Dockerfile we use. I would ignore it until it starts passing on PRs that we know work.

**Pull request merged**
