### PR TITLE
upgrade Go to 1.15

### PR DESCRIPTION
**Pull request by AkihiroSuda**

### CODE REVIEW

**Comment by kolyshkin** [comment]
We will need to remove 1.13.x as well since it will become unsupported once 1.15 is out.

**Comment by kolyshkin** [comment]
1.15rc2 is out

**Comment by mrunalp** [comment]
1.15 out now

**Comment by AkihiroSuda** [comment]
Ready for review

**Comment by kolyshkin** [comment]
@AkihiroSuda we can also remove the whole `-mod=vendor` / `$(MOD_VENDOR)` from the Makefile. Fine to do it later though.

**Pull request merged**
