### PR TITLE
release: update libseccomp to 2.5.3, minor script fixes

### PR DESCRIPTION
**Pull request by kolyshkin**
1. Update libseccomp to 2.5.3
    It was released about a month ago. I don't see anything major
    in the changelog but it makes sense to keep tracking upstream deps.

2. script/release_*.sh: fix usage
3. script/seccomp.sh: fix argc check

### CODE REVIEW

**Review by cyphar — DISMISSED** [review]
LGTM.

**Comment by cyphar** [comment]
Ah this has a conflict with #3309. Since you're touching `release.sh` can you also fix the `usage` issue in `release_sign.sh`?

**Comment by cyphar** [comment]
Ah this has a conflict with #3309. Since you're touching `release.sh` can you also fix the `usage` issue in `release_sign.sh`? I need to write a changelog for this release anyway, so I will be setting up the release tomorrow so if we get this merged before then I'll include this in rc1 (if not, we can include it in the actual release).

**Comment by kolyshkin** [comment]
> can you also fix the `usage` issue in `release_sign.sh`?

done, PTAL @cyphar

**Comment by cyphar** [comment]
DCO is missing in commit two. ;)

**Comment by kolyshkin** [comment]
> DCO is missing in commit two. ;)

yup. fixed

**Review by AkihiroSuda — APPROVED** [review]

**Review by cyphar — APPROVED** [review]
LGTM

**Pull request merged**
