### PR TITLE
tests/integration: nits

### PR DESCRIPTION
**Pull request by kolyshkin**
Most notable one is spec.bats simplification and speedup.

The rest is nits and minor fixes.  Please see individual commits for details.

### CODE REVIEW

**Comment by kolyshkin** [comment]
Interesting... my changes resulting in spec generated by `runc spec --rootless` being validated (which was not performed before), and the validation fails with the following error:

```
The document is not valid. see errors :
 - linux.resources.pids: limit is required
```

Indeed, runtime-spec says pids.limit is required: 
https://github.com/opencontainers/runtime-spec/blob/80db136d65fc1a90b1bbbcc964a4b354b7aad0b2/schema/config-linux.json#L53

@AkihiroSuda mind to take a look? Or should we NOT run this for the rootless case?

**Comment by AkihiroSuda** [comment]
Shouldn't be required even for rootful, I guess

**Comment by kolyshkin** [comment]
OK this is caused by https://github.com/opencontainers/runc/blob/d636ad6256f9194b0f4c6ee181e75fb36e3446d8/tests/integration/helpers.bash#L108

**Comment by kolyshkin** [comment]
@mrunalp @AkihiroSuda PTAL

**Review by AkihiroSuda — APPROVED** [review]

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
