### PR TITLE
Fix setting OomScoreAdj from OCI spec

### PR DESCRIPTION
**Pull request by tonistiigi**
cc @crosbymichael 

Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>

### CODE REVIEW

**Comment by LK4D4** [comment]
LGTM

**Comment by mrunalp** [comment]
This should be clubbed with the other cgroups settings in `createCgroupConfig`

**Comment by hqhq** [comment]
@mrunalp `OomScoreAdj` is not a cgroup field but a system wide variable. So I think it should be kept out of cgroup stuff, but I don't know if it's kind of **resource**. In runC it's not in `Resource` but in specs it's in. Hard to say which one is better.

**Comment by mrunalp** [comment]
@hqhq Yep, you are right. I agree it is hard to put it anywhere but resource for now in the spec for now.

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
