### PR TITLE
Remount /sys/fs/cgroup as RO if MS_RDONLY was passed

### PR DESCRIPTION
**Pull request by LK4D4**
Now I tried this with docker, all is okay after fix of abs cgroup-parent.
Now it looks like on host.

### CODE REVIEW

**Comment by LK4D4** [comment]
ping @mrunalp @rjnagal @vmarmol

**Comment by rjnagal** [comment]
This removes the ability to create subcontainers. Is that intentional?

**Comment by LK4D4** [comment]
@rjnagal Actually I tested it with subcontainers. All cgroups will be writable if you won't pass `MS_RDONLY`.

**Comment by rjnagal** [comment]
ok, I need to read the neighboring code some more :)
Aren't we appending MS_RDONLY to default flags?

**Comment by LK4D4** [comment]
@rjnagal No, defaut flags is `syscall.MS_NOEXEC | syscall.MS_NOSUID | syscall.MS_NODEV`. We can add `MS_RDONLY` to `Flags` when create `Mount` with type `cgroup` and then all cgroups will be readonly(this is default in docker).

**Comment by rjnagal** [comment]
So in docker, subcontainer creation will failed? [ Sorry, I'll take a better look in a while ]

**Comment by LK4D4** [comment]
@rjnagal It would failed anyway without --privileged. With --privileged all will be okay.

**Comment by LK4D4** [comment]
@rjnagal Also, it is like on host. `/sys/fs/cgroup` mounted as ro, cgroups themselves as rw.

**Comment by rjnagal** [comment]
ah, that's the but I was missing. Everything is mounted rw on my host :)

**Comment by LK4D4** [comment]
@rjnagal Maybe that's makes no sense then :) But it is maybe makes sense to add this ability, when MS_RDONLY is passed. Like without --privileged you can't create you own cgroup.
WDYT?

**Comment by rjnagal** [comment]
Blocking creation of cgroup by non-privileged containers sounds good. You get that today if your container is not running as root as all cgroup files are root owned by default.

**Comment by LK4D4** [comment]
@rjnagal I'll change PR a little, so it won't be mounted as RO always.

**Comment by LK4D4** [comment]
@rjnagal So, now if you pass `MS_RDONLY` you won't be able to change and create cgroups. In opposite case you will be able to do both.

**Comment by mrunalp** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
