### PR TITLE
trying again - updating code of conduct links

### PR DESCRIPTION
**Pull request by vsoch**
Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

This will close #1996

### CODE REVIEW

**Comment by cyphar** [comment]
Looks good, but can you change the commit description? You can do that like this:

```
% git commit --amend -sm "whatever"
% git push <remote> <branch> --force
```

**Comment by rst0git** [comment]
> Looks good, but can you change the commit description (`trying again` isn't all that descriptive)?

There is a very useful guide on how to write git commit messages:
https://chris.beams.io/posts/git-commit/

**Comment by vsoch** [comment]
I think I did - did you refresh the page? The message I see is `updating code of conduct and security links`

**Comment by vsoch** [comment]
@rst0git thank you! The embarrassing detail is that I've read that post. Definitely a good time for a refresher :)

**Comment by rst0git** [comment]
> I think I did - did you refresh the page? The message I see is `updating code of conduct and security links`

The title of the pull request (on GitHub) is independent from the commit message. Thus, the commit message is now `updating code of conduct and security links` but the title is still the old one.
If you want, you can change it from the "Edit" button in the top-right corner of this web-page.

**Comment by vsoch** [comment]
So your issue is with the title of the pull request?

**Comment by rst0git** [comment]
> So your issue is with the title of the pull request?

No, never mind, I misread your message.

**Comment by cyphar** [comment]
LGTM.

**Comment by vsoch** [comment]
We changed the code of conduct location, so don’t merge yet!

**Comment by vsoch** [comment]
okey - the links are live and now I've updated the code of conduct to be the location discussed in the call:
 - https://github.com/opencontainers/org/blob/master/CODE_OF_CONDUCT.md

The security is the same:
 - https://github.com/opencontainers/org/blob/master/security

**Comment by cyphar** [comment]
LGTM.

**Comment by cyphar** [comment]
Needs a rebase, probably because I just merged #2001.

**Comment by vsoch** [comment]
Nope messed it up, I'll try again.

**Pull request closed without merging**
