### PR TITLE
support unbindable,runbindable for rootfs propagation

### PR DESCRIPTION
**Pull request by Mashimiao**
Signed-off-by: Ma Shimiao <mashimiao.fnst@cn.fujitsu.com>

### CODE REVIEW

**Comment by hqhq** [comment]
LGTM

**Comment by Mashimiao** [comment]
ping @cyphar  @mrunalp

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by cyphar** [comment]
While I'm fine with this, I'm wondering whether this mode will actually work as expected?

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
