### PR TITLE
Upgrade go-criu to v6

### PR DESCRIPTION
**Pull request by snprajwal**
The v6.0.0 release of go-criu has deprecated the `rpc` package in favour
of the `crit` package. This commit provides the changes required to use
this version in runc.

Signed-off-by: Prajwal S N <prajwalnadig21@gmail.com>

### CODE REVIEW

**Review by AkihiroSuda — DISMISSED** [review]

**Review by kolyshkin — COMMENTED** [review]
@adrianreber @rst0git PTAL

**Comment by snprajwal** [comment]
@kolyshkin there's some stuff being added to v6.1.0 that'll make this PR a lot simpler. Converting this to a draft temporarily to prevent merging.

**Comment by snprajwal** [comment]
Kinda weird how GitHub refuses to let me request a review from more than one person :eyes:

**Review by AkihiroSuda — APPROVED** [review]

**Comment by adrianreber** [comment]
Looks good to me.

**Review by kolyshkin — APPROVED** [review]
LGTM

**Pull request merged**
