### PR TITLE
Remove @avagin as a maintainer

### PR DESCRIPTION
**Pull request by avagin**
Unfortunately I don't have enough time to be a maintainer of runc.
I am not going to disappear from the community and as before
I always ready to help with anything.

Signed-off-by: Andrei Vagin <avagin@openvz.org>

### CODE REVIEW

**Comment by crosbymichael** [comment]
LGTM

@avagin thanks!

**Comment by thaJeztah** [comment]
Thanks @avagin !

**Comment by mrunalp** [comment]
@avagin thanks for all your work! 
LGTM

**Comment by mrunalp** [comment]
LGTM

**Comment by hqhq** [comment]
Thanks @avagin

**Comment by cyphar** [comment]
Thanks @avagin for all of your work. Good luck with CRIU and the rest of the crazy stuff you're working on.

**Pull request merged**
