### PR TITLE
Delete xattr related code

### PR DESCRIPTION
**Pull request by danail-branekov**
This is a follow-up from https://github.com/opencontainers/runc/pull/1633

Selinux related code has been moved to the selinux package
(https://github.com/opencontainers/selinux) and therefore xattr related
code can be deleted from libcontainer

Signed-off-by: Danail Branekov <danailster@gmail.com>

### CODE REVIEW

**Comment by dqminh** [comment]
LGTM.

Thanks for making the changes !

**Comment by cyphar** [comment]
LGTM.

**Comment by cyphar** [comment]
Heh, I was in the middle of the merge. :wink:

**Comment by dqminh** [comment]
> Heh, I was in the middle of the merge.

Oh no, race conditions in real life ! Sorry :stuck_out_tongue_closed_eyes:

**Comment by cyphar** [comment]
🏃

**Pull request merged**
