### PR TITLE
Add the most basic sniff tests of runc

### PR DESCRIPTION
**Pull request by duglin**
just so that we're not merging code into master w/o any tests at all.
I expect this to be removed once we have a real testing infrastructure.

Signed-off-by: Doug Davis <dug@us.ibm.com>

### CODE REVIEW

**Comment by cyphar** [comment]
Ironically janky is broken, while the tests all pass. :P

**Comment by duglin** [comment]
yea its because it hangs for some reason on janky but not locally - could be a sign of an issue....

**Comment by hqhq** [comment]
I would like to see this to be something like runc level integration test, which can test every runc command with all kinds of different configs. This is a start which is good :+1:  but I don't think it's a good framework to be expanded on :(
ping @jfrazelle I thought she may be working on this too, any thoughts?

**Comment by duglin** [comment]
@hqhq agreed, which is why I said "I expect this to be removed once we have a **real** testing infrastructure."

**Comment by crosbymichael** [comment]
LGTM

**Comment by LK4D4** [comment]
Fairly large binary in repo for thing which will be removed :) I think download it would be lesser evil, also I think that libcontainer tests already download it somewhere.

**Comment by cyphar** [comment]
+1 on downloading the tar of busybox (just steal the script from Docker). Apart from that, this looks like a good first step on improving our testing. We still need to add more tests that actually check that resource limits are enforced.

**Comment by duglin** [comment]
remove the tar file - downloaded it from dockerhub instead

**Comment by duglin** [comment]
#600 fixes the test issue - its unrelated to this PR.

**Comment by duglin** [comment]
rebased

**Comment by duglin** [comment]
ping @mrunalp @vbatts

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
