### PR TITLE
ci: temporary set vagrant to 2.4.1-1

### PR DESCRIPTION
**Pull request by lifubang**
https://github.com/hashicorp/vagrant/pull/13532

### CODE REVIEW

**Review by kolyshkin — APPROVED** [review]
lgtm; thanks!

**Review by rata — APPROVED** [review]
LGTM, thanks!

**Comment by rata** [comment]
When a new version is released, we can update. Just in case at some point we need it, there is also this other work-around using an env var: https://github.com/hashicorp/vagrant/issues/13527#issuecomment-2453595641

**Comment by pakosaan** [comment]
> When a new version is released, we can update. Just in case at some point we need it, there is also this other work-around using an env var: [hashicorp/vagrant#13527 (comment)](https://github.com/hashicorp/vagrant/issues/13527#issuecomment-2453595641)

i did that but another error occured:
```
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
/opt/vagrant/embedded/lib/ruby/3.3.0/rubygems/specification.rb:2245:in `raise_if_conflicts': Unable to activate fog-core-2.6.0, because excon-0.112.0 conflicts with excon (~> 1.0) (Gem::ConflictError)
	from /opt/vagrant/embedded/lib/ruby/3.3.0/rubygems/specification.rb:1383:in `activate'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.2/lib/vagrant/bundler.rb:769:in `block in activate_solution'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.2/lib/vagrant/bundler.rb:766:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.2/lib/vagrant/bundler.rb:766:in `activate_solution'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.2/lib/vagrant/bundler.rb:606:in `internal_install'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.2/lib/vagrant/bundler.rb:358:in `install'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.2/lib/vagrant/plugin/manager.rb:141:in `block in install_plugin'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.2/lib/vagrant/plugin/manager.rb:151:in `install_plugin'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.2/plugins/commands/plugin/action/install_gem.rb:33:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.2/lib/vagrant/action/warden.rb:38:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.2/lib/vagrant/action/builder.rb:183:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.2/lib/vagrant/action/runner.rb:104:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.2/lib/vagrant/util/busy.rb:22:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.2/lib/vagrant/action/runner.rb:104:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.2/plugins/commands/plugin/command/base.rb:17:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.2/plugins/commands/plugin/command/install.rb:73:in `block in execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.2/plugins/commands/plugin/command/install.rb:72:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.2/plugins/commands/plugin/command/install.rb:72:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.2/plugins/commands/plugin/command/root.rb:69:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.2/lib/vagrant/cli.rb:67:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.2/lib/vagrant/environment.rb:319:in `cli'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.2/bin/vagrant:258:in `<main>'
```

**Pull request merged**
