### PR TITLE
enable travis for multi-arch

### PR DESCRIPTION
**Pull request by alicefr**
Enable running the tests on arm64, ppc64le and s390x.

Fixes: https://github.com/opencontainers/runc/issues/2383

Signed-off-by: Alice Frosi <afrosi@de.ibm.com>

### CODE REVIEW

**Comment by alicefr** [comment]
Vagrant is only avaiable for x86

**Comment by alicefr** [comment]
Is it possible to run part of the test suite without vagrant?

**Comment by kolyshkin** [comment]
Many tests are run not on Vagrant but inside a podman container. We only use Vagrant for cgroupv2 tests, which require a very recent kernel and distro.

**Comment by kolyshkin** [comment]
You'll also need to add more arches to `tests/integration/multi-arch.bash` in order to be able to run integration tests (`/tests/integration/`).

**Comment by alicefr** [comment]
it's a little bit more complicated because on the native architecture we're missing some dependencies in  https://github.com/opencontainers/runc/blob/master/Dockerfile#L15-L18

**Comment by kolyshkin** [comment]
Yeah, I think the crossbuild should either be restricted to be run on amd64. Better yet, since we are now actually testing it on different platforms, we don't need it any longer.

The only thing that bugs me is in crossbuild we buld for three different ARMs (including 32-bit arm6 and arm8 aka hf), while in travis we only have arm64. Not sure how important it is bit maybe we can cross-build 32-bit arm on 64-bit arm?

**Comment by AkihiroSuda** [comment]
If it is completed you can run tests outside Docker as in https://github.com/opencontainers/runc/blob/0f7ffbebeb9e3e697dd0efc6f4ab9dc14054960e/.travis.yml#L16-L22

**Comment by alicefr** [comment]
@AkihiroSuda I'll try that out. Sorry I was on vacation and busy with other stuff. Not sure why the CI is using x86 images instead of the built one. I need to have a closer look.

**Comment by AkihiroSuda** [comment]
Travis isn't responding, could you push again?

**Comment by alicefr** [comment]
Let's check if by re-triggering travis will run

**Comment by alicefr** [comment]
any idea what I'm doing wrong because travis doesn't start?

**Comment by AkihiroSuda** [comment]
Not sure, could you try reopening a new PR?

**Comment by alicefr** [comment]
yes, I can try!

**Comment by alicefr** [comment]
Opened this: https://github.com/opencontainers/runc/pull/2477 . Let's see if this solves the issue

**Comment by alicefr** [comment]
@AkihiroSuda it seems that travis didn't like the arch in the script. I removed that and travis CI started. There was a parsing issue. I'll close the second PR as it's a simple copy of this.

**Comment by alicefr** [comment]
The PR is not ready yet. I had to modify the Dockerfile to get the right dependencies for x86. I also had to split the test for each architecture because travis matrix doesn't allow to define multiple architecture for the same entry. Right now, I have some issue with the tests on the other architecture. I need to investigate a little deeper. I guess they're getting a wrong image/binary

**Comment by alicefr** [comment]
For ppc64le and s390x, I'm missing the hello-world tarball: https://github.com/opencontainers/runc/tree/master/tests/integration/testdata

**Comment by AkihiroSuda** [comment]
@alicefr https://github.com/docker-library/hello-world

**Comment by AkihiroSuda** [comment]
Travis not responding, please open a new one

**Pull request closed without merging**
