### PR TITLE
Release 1.1.3

### PR DESCRIPTION
**Pull request by kolyshkin**
Let's cook 1.1.3. Copy-paste from the CHANGELOG.md below.

----

## [1.1.3] - 2022-06-08

> In the beginning there was nothing, which exploded.

### Fixed
 * Our seccomp `-ENOSYS` stub now correctly handles multiplexed syscalls on
   s390 and s390x. This solves the issue where syscalls the host kernel did not
   support would return `-EPERM` despite the existence of the `-ENOSYS` stub
   code (this was due to how s390x does syscall multiplexing). (#3478)
 * Retry on dbus disconnect logic in libcontainer/cgroups/systemd now works as
   intended; this fix does not affect runc binary itself but is important for
   libcontainer users such as Kubernetes. (#3476)
 * Inability to compile with recent clang due to an issue with duplicate
   constants in libseccomp-golang. (#3477)
 * When using systemd cgroup driver, skip adding device paths that don't exist,
   to stop systemd from emitting warnings about those paths. (#3504)

 * Socket activation was failing when more than 3 sockets were used. (#3494)
 * Various CI fixes. (#3472, #3479)

### Added
 * Allow to bind mount /proc/sys/kernel/ns_last_pid to inside container. (#3493)

### Changed
 * runc static binaries are now linked against libseccomp v2.5.4. (#3481)

### CODE REVIEW

**Comment by cyphar** [comment]
I'd like to backport #3451 first. Also when do we want to do a runc 1.2 release?

**Comment by kolyshkin** [comment]
> Also when do we want to do a runc 1.2 release?

I say let's try to do it in June. There are some PRs in the milestone.

**Comment by kolyshkin** [comment]
> I'd like to backport #3451 first.

Changelog entry added.

**Comment by kolyshkin** [comment]
@cyphar @AkihiroSuda @thaJeztah PTAL

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks for preparing!

**Comment by AkihiroSuda** [comment]
Is this still WIP/DNM?

**Comment by kolyshkin** [comment]
> Is this still WIP/DNM?

Can't be committed until we know the release date (and that depends on @cyphar). Otherwise not a WIP.

**Comment by cyphar** [comment]
Just waiting for #3504 to be merged and then this is ready IMHO.

**Comment by thaJeztah** [comment]
Both were merged 👍

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by cyphar — APPROVED** [review]
LGTM.

**Pull request merged**
